examples/defi/radiswap/src/lib.rs
A cleaner solution would be to define initial lp supply as a fixed variable and not an input to the init and when adding liquidity into an empty pool mint the on creation defined initial lp supply.
However, I assumed there may be a usecase where based on token supplies and to prevent overflow or other errors the user may want to define the intial ratio.
I am not sure one would need to update the LP based on the current updated tokens in the pool. If not, the logic can be removed from the swap method.
=> radiswap: Fix add_liquidity into empty pool bug

assets/template/tests/lib.rs
Fixes the `TransactionBuilder` to use both `drop_all_bucket_refs` and
`deposit_all_buckets(account)` in the `Hello::new` function call of
`test_hello` unit test.  This is now consistent for both transactions
in the unit test and matches how `resim call-function` works.
Fixes #71
=> Add deposit_all_buckets... to new-package template

scrypto-derive/src/auth.rs
Instead of generating a block, generate a closure with the
same body.  This way, the body can include a return statement.
Fixes #76
=> Use a closure in the auth macro for compatibility

scrypto-derive/src/auth.rs, scrypto-tests/tests/auth.rs
Don't use a let binding at all so the closure can be called regardless
of Fn or FnMut type.  Also drops the closure as soon as possible which
leads to better inlining and less chance of lifetime/borrow issues later
Fixes #84
=> Fix auth macro failure when capturing &mut self

examples/core/flat-admin/src/lib.rs, examples/defi/radiswap/src/lib.rs, examples/defi/regulated-token/src/lib.rs, examples/defi/synthetics/src/lib.rs, examples/nft/magic-card/src/lib.rs, radix-engine/tests/bucket/src/bucket.rs, radix-engine/tests/resource_def/src/resource_def.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/resource_def.rs
Following https://github.com/radixdlt/radixdlt-scrypto/issues/65, we're replacing `ResourceDef::burn(bucket: Bucket, auth: Option<BucketRef>)` with two APIs:
* `ResourceDef::burn(bucket: Bucket)` - For resource with flag `FREELY_BURNABLE`
* `ResourceDef::burn_with_resource(bucket: Bucket, auth: BucketRef)` - For all resources
=> Update burn APIs

radix-engine/src/model/mod.rs, radix-engine/src/model/validated_data.rs, transaction-manifest/src/decompiler.rs
Command:
```shell
resim call-method 02045ae9a11a80df853143b94868672b2ad7e26753e5bdc0b9a9b9 buy_gumball 1,030000000000000000000000000000000000000000000000000004 --manifest out.rtm
```
Before:
```rust
CLONE_BUCKET_REF BucketRef(1u32) BucketRef("badge1");
CALL_METHOD Address("0293c502780e23621475989d707cd8128e4506362e5fed6ac0c00a") "withdraw" Decimal("1") Address("030000000000000000000000000000000000000000000000000004") BucketRef(512u32);
TAKE_FROM_WORKTOP Decimal("1") Address("030000000000000000000000000000000000000000000000000004") Bucket("bucket1");
CALL_METHOD Address("02045ae9a11a80df853143b94868672b2ad7e26753e5bdc0b9a9b9") "buy_gumball" Bucket(513u32);
CALL_METHOD_WITH_ALL_RESOURCES Address("0293c502780e23621475989d707cd8128e4506362e5fed6ac0c00a") "deposit_batch";
```
After:
```rust …
```
=> Resolve bucket name in call args

simulator/src/scrypto/cmd_new_package.rs
The tests folder was incorrectly named after recent refactoring. This caused `scrypto test` not running any test.
=> Fix an issue with scrypto new-package

scrypto/src/types/decimal.rs
Created the dec! macro to simplify Decimal creation.
```rust
dec!(5).to_string() = "5"
dec!(1.23).to_string() = won't compile
dec!("1.23").to_string() = "1.23"
dec!(123, -2).to_string() = "1.23"
dec!(123, 2).to_string() = "12300"
dec!(170_141_183_460_469_231_732, 0) = won't compile
dec!(1, 4_294_967_296) = panic!("Overflow of arg2.")
```
=> Macro to simplify Decimal creation

radix-engine/src/engine/process.rs, radix-engine/src/model/bucket.rs, radix-engine/src/model/transaction.rs, radix-engine/src/model/validated_transaction.rs, radix-engine/src/transaction/builder.rs, radix-engine/src/transaction/executor.rs, radix-engine/src/transaction/validator.rs, radix-engine/tests/account.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/bucket_ref.rs, scrypto/src/resource/vault.rs, scrypto/src/types/non_fungible_key.rs, transaction-manifest/examples/call.rtm, transaction-manifest/src/ast.rs, transaction-manifest/src/decompiler.rs, transaction-manifest/src/generator.rs, transaction-manifest/src/lexer.rs, transaction-manifest/src/parser.rs
This PR introduces a  new instruction `TAKE_NON_FUNGIBLES_FROM_WORKTOP` to support taking non-fungibles from worktop.
=> Add support for taking non-fungibles from worktop

scrypto/src/types/big_decimal.rs
We have dec! to create Decimals easily. Now we have bdec! to create BigDecimals easily.
=> bdec! macro is added to create BigDecimals from number literals easily

scrypto-tests/tests/math.rs, scrypto/src/lib.rs, scrypto/src/prelude/mod.rs, scrypto/src/types/big_decimal.rs, scrypto/src/types/decimal.rs
This is to make `dec!` and `bdec!` work both inside the crate and outside.
=> Externalise dec and bdec macros

radix-engine/Cargo.toml, radix-engine/src/engine/process.rs, radix-engine/tests/authorization_component.rs, radix-engine/tests/package.rs, radix-engine/tests/package/Cargo.toml, radix-engine/tests/package/src/lib.rs
Cleaned up processing of return value:
* Removed call to `scrypto_free` which is unnecessary since process will get garbage collected.
* Removed memcopy of returned value and instead process the value directly from the buffer.
=> Refactor read of return value

scrypto/src/math/decimal.rs
We did not check for overflow in Decimal::add() and sub() methods.
Now we do! ;)
=> Decimal overflow detection added for sub() and add() methods

assets/account/src/lib.rs, assets/system/src/lib.rs, radix-engine/src/engine/process.rs, radix-engine/src/engine/track.rs, radix-engine/src/ledger/traits.rs, radix-engine/src/model/resource_manager.rs, radix-engine/src/transaction/builder.rs, radix-engine/tests/authorization_component.rs, radix-engine/tests/authorization_resource.rs, radix-engine/tests/component/src/auth_component.rs, radix-engine/tests/component/src/chess.rs, radix-engine/tests/component/src/cross_component.rs, radix-engine/tests/component/src/reentrant_component.rs, radix-engine/tests/core/src/call.rs, radix-engine/tests/non_fungible.rs, sbor-tests/Cargo.toml, sbor-tests/tests/any.rs, sbor/Cargo.toml, sbor/src/any.rs, sbor/src/describe.rs, scrypto-abi/Cargo.toml, scrypto-abi/src/abi.rs, scrypto-derive/Cargo.toml, scrypto-tests/Cargo.toml, scrypto/Cargo.toml, scrypto/src/component/system.rs, scrypto/src/prelude/mod.rs, scrypto/src/resource/authorization.rs, simulator/Cargo.toml, simulator/src/resim/cmd_mint.rs
Changes:
- Remove unnecessary serde annotation and use snake case for field names
- Use week feature dependency (YEAH!)
On the down side,  you now need rust `v1.60` or above. 
Run `rustup update` to update your toolchain.
=> Use snake case for JSON property names

radix-engine/Cargo.toml, radix-engine/src/engine/track.rs
Resim is no longer sorting resource addresses in the order in which they were created which makes it harder for users to later reuse these addresses.
In v0.3.0, when viewing a receipt of a transaction, the resource addresses shown there would be sorted according to which resource was created first. However, this is not the case as of commit [8117d9fffc753f8af9c10ec0b3335610080827ba](https://github.com/radixdlt/radixdlt-scrypto/tree/8117d9fffc753f8af9c10ec0b3335610080827ba) in the develop branch. 
As an example, let's say that we would like to create 6 tokens named Token A though F. The following is a portion of the receipt we get after creating these 6 tokens:
```
Logs: 6
├─ [INFO ] Resource Address of Token A is 0399da10517093bdd534b3d5a46df314cb0f561ba6b590884006ad
├─ [INFO ] Resource …
```
=> Resim new entities sorting

assets/system/src/lib.rs, radix-engine/src/engine/track.rs, radix-engine/src/model/package.rs, radix-engine/tests/component/src/component.rs, radix-engine/tests/component/src/cross_component.rs, radix-engine/tests/component/src/reentrant_component.rs, radix-engine/tests/non_fungible/src/lib.rs, radix-engine/tests/resource/src/lib.rs, radix-engine/tests/resource_creator/src/resource_creator.rs, scrypto-derive/src/blueprint.rs, scrypto/src/component/system.rs, scrypto/src/prelude/mod.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/non_fungible.rs, scrypto/src/resource/system.rs
New names:
- `borrow_package`, 
- `borrow_component`, 
- `borrow_resource_manager`
=> Rename borrow macros

simulator/src/ledger/dumper.rs, simulator/src/resim/cmd_call_method.rs, simulator/src/resim/cmd_export_abi.rs, simulator/src/resim/cmd_generate_key_pair.rs, simulator/src/resim/cmd_new_account.rs, simulator/src/resim/cmd_publish.rs, simulator/src/resim/cmd_reset.rs, simulator/src/resim/cmd_set_current_epoch.rs, simulator/src/resim/cmd_set_default_account.rs, simulator/src/resim/cmd_show.rs, simulator/src/resim/cmd_show_configs.rs, simulator/src/resim/cmd_show_ledger.rs, simulator/src/resim/mod.rs
Currently, resim functions which emit output to the console use println! to do so. This means they can only send output to the console. Other applications might wish to redirect the output to other IO objects such as files, network streams, or anything else that implements the std::io:Write trait.
Changes made here replaced the uses of println! with writeln! to use an output object such that what was previously:
println!("This is some text") ;
becomes
writeln!(out, "This is some text") ;
The "out" in this case can be a stdout, a file; or a TcpStream
Doing this allows the TCP server to use the same functions used by local resim without resorting to copying files for this purpose and then having them be out of sync.
=> Change resim output to use **writeln!** instead of **println!**

simulator/src/ledger/dumper.rs, simulator/src/resim/cmd_call_function.rs, simulator/src/resim/cmd_call_method.rs, simulator/src/resim/cmd_export_abi.rs, simulator/src/resim/cmd_generate_key_pair.rs, simulator/src/resim/cmd_mint.rs, simulator/src/resim/cmd_new_account.rs, simulator/src/resim/cmd_new_badge_fixed.rs, simulator/src/resim/cmd_new_badge_mutable.rs, simulator/src/resim/cmd_new_token_fixed.rs, simulator/src/resim/cmd_new_token_mutable.rs, simulator/src/resim/cmd_publish.rs, simulator/src/resim/cmd_run.rs, simulator/src/resim/cmd_set_default_account.rs, simulator/src/resim/cmd_show.rs, simulator/src/resim/cmd_show_configs.rs, simulator/src/resim/cmd_show_ledger.rs, simulator/src/resim/cmd_transfer.rs, simulator/src/resim/config.rs, simulator/src/resim/mod.rs, simulator/src/rtmc/mod.rs
This PR enables `--signing-keys` for all transaction-based commands, as PTE terminal won't allow account switch. This gives users an alternative approach to simulate different accounts.
=> Support --singing-keys for all transaction-based commands

radix-engine/src/model/resource_manager.rs, radix-engine/tests/bucket.rs, radix-engine/tests/bucket/src/bucket.rs
The `Bucket::new()` function calls the `create_empty_bucket` function on the resource manager for the creation of empty buckets. However, this function was not in the list of allowed functions which meant that any call to `Bucket::new()` would result in a `MethodAuthorization::Unsupported` error.
This PR adds the `create_empty_bucket` function to the allowed functions on the resource manager and adds tests for the empty bucket creation.
=> Fixed a bug with creating empty buckets

.gitignore, .vscode/settings.json, README.md, sbor/Cargo.toml
Rust Analyzer is the recommended VSCode extension for Rust, but had some issues running with this repo, notably:
* It didn't like that `serde` was both a dependency and a feature - see https://doc.rust-lang.org/cargo/reference/features.html
* It didn't pick up the Cargo.toml files
* The .vscode folder is intended to be team-shared, workspace settings - so I've removed this from the .gitignore
* I've added a "rust-analyzer.linkedProjects" section to the .vscode settings so that it picks up the Cargo.toml files
* I've fixed the serde feature to now use `dep:serde`, so rust-analyzer is happy (see also https://doc.rust-lang.org/cargo/reference/features.html )
=> Rust analyzer fixes

radix-engine/src/engine/process.rs, scrypto/src/engine/api.rs, scrypto/src/resource/proof_rule.rs
This pull request adds the ability to check whether a given vector of `Proof`s satisfies an `AccessRule` or not, inside of Scrypto. Example usage looks as follows:
```rust
pub fn is_allowed(proofs: Vec<Proof>)  {
let rule: AccessRule = rule!(
require_amount(dec!("20"), RADIX_TOKEN)
);
info!("Proofs satisfy AuthRule: {:?}", rule.check(&proofs[..])); 
}
```
=> Added the ability to check an access rule from Scrypto

radix-engine/src/engine/errors.rs, radix-engine/src/model/transaction_processor.rs, radix-engine/src/wasm/errors.rs, radix-engine/tests/bucket.rs, radix-engine/tests/component.rs, radix-engine/tests/kv_store.rs, radix-engine/tests/package.rs, radix-engine/tests/proof.rs, radix-engine/tests/resource.rs, radix-engine/tests/vault.rs, simulator/src/resim/mod.rs
The requirement of RuntimeErrors to be cloneable is not allowing us to save some non-cloneable information in errors. This PR removes cloning from errors since it is not really needed.
=> Remove error cloning and partialEq

radix-engine/tests/abi/Cargo.toml, radix-engine/tests/arguments.rs, radix-engine/tests/arguments/Cargo.toml, radix-engine/tests/arguments/src/lib.rs, sbor/src/path.rs
This PR is in response to #366 where `Proof`s and `Bucket`s wrapped in `Option` would lead to a panic in the Radix Engine.
=> Fix for Proofs and Buckets wrapped with an Option.

radix-engine/tests/non_fungible/src/lib.rs, radix-engine/tests/vault.rs, radix-engine/tests/vault/src/vault.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/proof.rs, scrypto/src/resource/vault.rs
I often find myself get the first `NonFungibleId`. Why cant I use `non_fungible().id()`? Because it assumes I have knowledge of the struct. In cases where you dont have knowledge of this, this would be a nice simple addition. Its also consistent with the api combinations of having `non_fungibles()` and `non_fungible()` so it makes sense to have `non_fungible_ids` and `non_fungible_id`
=> Add non_fungible_id() convenience method for bucket/vault/proofs

radix-engine/src/engine/call_frame.rs, radix-engine/src/engine/track.rs, radix-engine/src/engine/track_support.rs, radix-engine/src/ledger/memory.rs, radix-engine/src/ledger/traits.rs, radix-engine/src/state_manager/commit_receipt.rs, radix-engine/src/state_manager/staging.rs, radix-engine/src/state_manager/state_diff.rs, simulator/src/ledger/radix_engine_db.rs
Replaced the `OutputId` derived from a CommittedTransactionHash with a simple incrementing version. This is possible with the assumption that `Address` is itself a unique identifier.
This simple change also allows us to remove an unneeded `spaces` database which we needed previously to maintain the `OutputId` of the space.
=> Cleanup output ids

scrypto/src/resource/proof.rs
This PR adds a number of different proof validation modes that can be used with the `Proof` type. In addition to adding more complex ways of performing proof validation, this PR still keeps the 90% case (validating against a resource address) fairly easy and frictionless.
=> Improved Proof Validation

radix-engine/src/ledger/memory.rs
This is a small PR implementing the `QueryableSubstateStore` trait for the `InMemorySubstateStore` type. This is done in response to #358.
=> Implemented the `QueryableSubstateStore` trait for the `InMemorySubstateStore`

radix-engine/src/engine/kernel.rs, radix-engine/src/engine/native_interpreter.rs, radix-engine/src/engine/node.rs, radix-engine/src/engine/node_ref.rs, radix-engine/src/engine/wasm_runtime.rs, radix-engine/src/fee/fee_table.rs, radix-engine/src/ledger/bootstrap.rs, radix-engine/src/model/abi_extractor.rs, radix-engine/src/model/component.rs, radix-engine/src/model/mod.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/tests/metering.rs, scrypto-unit/src/test_runner.rs, simulator/src/ledger/dumper.rs
- Renamed fee table entries to be consistent with our architecture
- Added costing for `drop_node`, `take_substate`, `check_access_rule`, and `instantiate_wasm`
- Added transaction base fee
- Renamed `Component` to `ComponentInfo` (`rust-analyzer` complains by wrongly linking to the `Component` in Scrypto)
=> Add missed costings

radix-engine/benches/transaction.rs, radix-engine/tests/component.rs, scrypto-tests/tests/import.rs, scrypto/src/component/component.rs, scrypto/src/macros.rs, transaction/src/manifest/generator.rs
As we have recently discussed, this is a small PR to remove the `FromStr` trait from the `ComponentAddress` type.
=> Remove `FromStr` trait from the `ComponentAddress` type.

format.sh
The ./format.sh script now works again even if the code doesn't compile
=> Update format.sh to use global scrypto CLI

build.sh, radix-engine/benches/transaction.rs, radix-engine/src/transaction/preview_executor.rs, radix-engine/tests/preview.rs, radix-engine/tests/transaction.rs, scrypto-unit/src/test_runner.rs, transaction/src/validation/transaction_validator.rs
Preview tests were breaking when I integrated with the engine - this is why.
Have removed the hardcoding of network in preview too.
=> fix: Preview doesn't assume local sim

radix-engine/src/transaction/transaction_receipt.rs, radix-engine/tests/abi.rs, radix-engine/tests/account.rs, radix-engine/tests/authorization_account.rs, radix-engine/tests/authorization_component.rs, radix-engine/tests/authorization_dynamic.rs, radix-engine/tests/authorization_resource.rs, radix-engine/tests/authorization_vault.rs, radix-engine/tests/bucket.rs, radix-engine/tests/component.rs, radix-engine/tests/data_access.rs, radix-engine/tests/fee.rs, radix-engine/tests/frame.rs, radix-engine/tests/invalid_stored_values.rs, radix-engine/tests/kernel_globalize.rs, radix-engine/tests/kernel_node_create.rs, radix-engine/tests/kv_store.rs, radix-engine/tests/leaks.rs, radix-engine/tests/local_component.rs, radix-engine/tests/metering.rs, radix-engine/tests/package.rs, radix-engine/tests/proof.rs, radix-engine/tests/resource.rs, radix-engine/tests/system.rs, radix-engine/tests/transaction_commit_rollback.rs, radix-engine/tests/vault.rs, radix-engine/tests/worktop.rs
I have reorganized the functions on TransactionReceipt a bit and included 4 more helpful functions:
+ `expect_commit_success()` now returned the exact encrypted transaction output (Last time, the function return a Vector with index [0] return only `[0]`? and index [1] return the transaction output).
+ `expect_commit_failure()` now returned the `RuntimeError` of transaction failure.
+ Change the last `expect_commit_failure()` into `expect_specific_failure()` .
+ Add `fn output()` return the decoded type (user choice) of transaction output (if success).
+ Add 3 functions return the new package, component, resource addresses on the transaction.
=> Helpful functions for TransactionReceipt on RadixEngine

scrypto-derive/src/blueprint.rs, scrypto/src/component/component.rs
Hope we can bring this convenience back again :D
This allows us to do:
```rust
let test_component: TestComponent = self.test_component_address.into();
```
=> Make into great again

assets/template/tests/lib.rs, radix-engine/Cargo.toml, radix-engine/src/wasm/wasmer.rs, radix-engine/src/wasm/wasmi.rs, radix-engine/tests/fuzz_transactions.rs
* Fix a downcast panic which occurs if `send_value` errors
* Update `send_value` error to use invoke error if the error is an actual downstream error
* Implemented a simple fuzz transaction tester
=> Alphanet Bugfix: Fix transaction panic

radix-engine/src/engine/modules/execution_trace.rs, radix-engine/src/engine/track.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/tests/account.rs, radix-engine/tests/execution_trace.rs, radix-engine/tests/execution_trace/src/execution_trace.rs, scrypto-unit/src/test_runner.rs, simulator/src/resim/cmd_set_current_epoch.rs
Current situation:
Fee payments are not being recorded in execution trace resource changes.
Desired situation:
Resource changes should include fee payments.
Proposed solution:
Nearly all needed information to keep track of the changes is already in FeeSummary. What's missing is vault's component addresses. Execution trace stores those addresses and later combines them with fee summary to create corresponding ResourceChange entries.
=> Add fee payments to ExecutionTrace resource changes receipt

radix-engine/benches/radix_engine.rs, radix-engine/src/engine/kernel.rs, radix-engine/src/model/nodes/resource_manager.rs, radix-engine/src/model/nodes/transaction_processor.rs, radix-engine/tests/authorization_account.rs, radix-engine/tests/authorization_component.rs, radix-engine/tests/local_component.rs, radix-engine/tests/preview.rs, transaction/src/validation/transaction_validator.rs
This commit is the result of running
```
cargo clippy --fix -- --allow clippy::all --warn clippy::redundant-clone
```
> What it does
> Checks for a redundant clone() (and its relatives) which clones an owned value that is going to be dropped without further use.
>
> Why is this bad?
> It is not always possible for the compiler to eliminate useless allocations and deallocations generated by redundant clone()s.
>
> Known problems
> False-negatives: analysis performed by this lint is conservative and limited.
=> lint: fix `clippy::redundant_clone`

radix-engine/src/engine/kernel.rs, radix-engine/src/model/nodes/transaction_processor.rs, radix-engine/src/transaction/transaction_executor.rs, sbor-derive/src/decode.rs, sbor-derive/src/describe.rs, sbor-derive/src/encode.rs, sbor-derive/src/type_id.rs, sbor/src/decode.rs, sbor/src/encode.rs, sbor/src/type_id.rs
This PR can give us increased performance with SBOR encoding 👍
By using the "Cow" (copy-on-write) smart pointer: https://doc.rust-lang.org/std/borrow/enum.Cow.html we can now have a typed struct which can _encode_ a reference or owned, and output an owned value ✨. I've then shown an example of how it can be used to reduce the cloning in the transaction processor.
To complete this magic, I had to extend the Encode/Decode/TypeId macros to work with generics.
I have also added a nicer error message for Describe when used with a type with generics. The SBOR schema doesn't currently support generics (for eg recreation of the code), and I didn't fancy adding that! But at least we get a clearer error message that generics aren't supported.
=> SBOR generics, refs and Cow support

scrypto/src/math/decimal.rs
The square root of a Decimal. Uses a standard Babylonian method.
Referring to [this](https://docs.rs/rust_decimal/latest/src/rust_decimal/maths.rs.html#328) implementation.
Related to #431
=> The square root of a Decimal.

radix-engine/benches/radix_engine.rs, radix-engine/src/engine/interpreters/scrypto_interpreter.rs, radix-engine/src/engine/kernel.rs, radix-engine/src/ledger/bootstrap.rs, radix-engine/src/transaction/preview_executor.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/src/wasm/traits.rs, radix-engine/src/wasm/wasmer.rs, radix-engine/src/wasm/wasmi.rs, radix-engine/tests/fuzz_transactions.rs, radix-engine/tests/transaction_executor.rs, scrypto-unit/src/test_runner.rs, simulator/src/resim/cmd_set_current_epoch.rs, simulator/src/resim/mod.rs
Trying to merge the changes into the node, I realised that ScryptoInterpreter still wasn't `Sync`... And it transpires that's because of the `PhantomData<I>` which captures the WasmEngine's `WasmModule` type. I realised that this could become an Associated Type - which is much nicer for all our type signatures, and also fixes the Sync problem.
[PhantomData<T>](https://doc.rust-lang.org/std/marker/struct.PhantomData.html) is intended to be used to pretend to the compiler that the type contains a type that behaves like `T` - and is intended for use on FFI, to eg capture lifetimes, or the fact something isn't Sync/Send. In contrast, I think our use of PhantomData is due to us not previously finding the associated type solution. And so does not relate to any want for ScryptoInterpreter to act …
=> refactor: WasmEngine trait changes, ScryptoInterpreter is Sync

radix-engine-interface/src/math/decimal.rs, radix-engine-interface/src/math/integer.rs, radix-engine-interface/src/math/precise_decimal.rs
Implements `sqrt`, `cbrt` and `nth root` functions for integers, decimals and precise decimals using implementations from `BigInt`, the type behind integers.
=> Root functions for integers, decimals and precise decimals

radix-engine-interface/Cargo.toml, radix-engine-interface/src/address/display.rs, radix-engine-interface/src/data/custom_type_id.rs, radix-engine-interface/src/data/mod.rs, radix-engine-interface/src/data/value_formatter.rs, radix-engine-interface/src/data/value_serializer.rs, simulator/Cargo.lock, test.sh, utils/Cargo.toml, utils/src/contextual_display.rs, utils/src/contextual_serialize.rs, utils/src/lib.rs
Both simple and invertible modes are supported - I'll opt for "simple" for now in the Core API sbor responses and see how it goes down.
Eventually, I'd like to support a choice in the Core and Gateway APIs between what kind of SBOR response you want (raw_hex / simple / invertible / simple_from_schema).
I decided to implement this in scrypto instead of import the toolkit's values for a couple of reasons:
* I don't want to require updating the toolkit in order to pull an updated scrypto into the node - adding an extra layer into the update cycle would cause real pain
* I don't want to have to remap the scrypto value to encode it / I wanted an implementation consistent with the other code in the repo (ie ContextDisplayable)
**Breaking changes**: None
=> feature: Can serialize a scrypto value

transaction/src/manifest/decompiler.rs
This PR fixes two issues with the decompilation of `NonFungibleId`s to their manifest representation:
1. Decompilation of `NonFungibleId`s used `Set` instead of `Array`.
2. `NonFungibleId`s decompilation was done by converting them to a string. This creates syntactically incorrect manifests.
=> Fix `NonFungibleId` decompilation

assets/blueprints/Cargo.lock, examples/hello-world/Cargo.lock, radix-engine-interface/src/data/value_serializer.rs, radix-engine-interface/src/model/resource/access_rules.rs, radix-engine/Cargo.toml, radix-engine/src/engine/modules/execution_trace.rs, radix-engine/src/engine/track.rs, radix-engine/src/fee/fee_reserve.rs, radix-engine/src/fee/fee_summary.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/src/transaction/transaction_receipt.rs, radix-engine/tests/execution_trace.rs, radix-engine/tests/royalty.rs, sbor/Cargo.toml, sbor/src/codec/collection.rs, sbor/src/type_id.rs, simulator/Cargo.lock
Various fixes / minor changes that I've made as part of integrating the Core API:
* Adds `indexmap` support in SBOR
* Renames fields in Fee Summary to be clearer on units
* Adds `vault_payments_xrd` which tracks the resultant fee payment changes (it's only present on commit, not on rejection)
* Adds getters to read values from AccessRules
* Minor change to how SBOR enums are serialized to JSON
**Breaking changes:**
* Renames of fields in FeeSummary
=> Fixes for Core API

CONTRIBUTING.md, README.md, clean.sh, test.sh, test_extra.sh, test_utils.sh
Changes:
- use cargo workspaces to build crates
building crates within a workspace allows to share build artifacts in one target folder, which helps to avoid unnecessary compilation
- use `cargo nextest` (if available on the host) instead of `cargo test` built-in test runner 
`cargo nextest` is much faster - it runs tests in parallel. Additionally it presents results in more consistent way.
It is also capable of detecting slow tests.
Installation: `cargo install cargo-nextest`
More details: https://nexte.st/
Additionally it is recommended to use `sccache` (shared cache compiler) as a wrapper for Rust compiler.
Installation:
`cargo install sccache`
Usage:
add below entry to `$HOME/.cargo/config.toml`
```
[build]
rustc-wrapper = "/path/to/sccache"
```
More details on sccache: …
=> Refactor test scripts to reduce execution time

radix-engine/benches/radix_engine.rs, radix-engine/src/ledger/bootstrap.rs, radix-engine/src/transaction/preview_executor.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/tests/fuzz_transactions.rs, radix-engine/tests/preview.rs, radix-engine/tests/transaction_executor.rs, scrypto-unit/src/test_runner.rs, simulator/src/resim/mod.rs, transaction/src/model/executable.rs, transaction/src/model/system_transaction.rs, transaction/src/model/test_transaction.rs, transaction/src/validation/transaction_validator.rs
This change comes from wanting a nice/easy way to remove the need to lock fee for validator transactions on betanet, which will speed the network up a little :)
**Breaking changes:**
* Removed `execute_tranasction_with_fee_reserve` methods, replaced with FeeConfig being an enum on each transaction executable, which can be used to disable fee payment
=> feature: Executable specifies if it needs fees

transaction/src/manifest/generator.rs
This PR makes the `generate_value` function public. This is needed for the RET testing.
=> Make the `generate_value` function public

sbor/src/codec/collection.rs, sbor/src/encoder.rs, sbor/src/rust.rs, sbor/src/type_id.rs
So that we can use indexset and indexmap in the engine (just add the `indexmap` feature to sbor in the Cargo.toml if it's not there already - but I think it is)
=> feat: Add indexset to sbor

radix-engine-interface/src/math/integer.rs, radix-engine-interface/src/math/integer/basic.rs, radix-engine-interface/src/math/integer/test.rs, scrypto/src/prelude/mod.rs
Things like I256::MAX.to_string() panicked for all large safe types. Now it is fixed.
=> Fix/max formatting for large Integer and Unsigned types

simulator/tests/resim.sh, transaction/src/builder/manifest_builder.rs
Resim bucket syntax for NFIds doesn't require a starting # - both are now supported, but the suggested format is now:
```
resim call-method $account deposit "U32#54,U32#55,U32#103,resource_address"
```
=> tweak: Resim bucket syntax for NFIds doesn't require a starting #

radix-engine/tests/common_transactions.rs, simulator/src/resim/addressing.rs, simulator/src/resim/cmd_new_badge_fixed.rs, simulator/src/resim/cmd_new_badge_mutable.rs, simulator/src/resim/cmd_new_simple_badge.rs, simulator/src/resim/cmd_new_token_fixed.rs, simulator/src/resim/cmd_new_token_mutable.rs, simulator/tests/resim.sh, transaction/examples/account/multi_account_resource_transfer.rtm, transaction/examples/account/resource_transfer.rtm, transaction/examples/faucet/free_funds.rtm, transaction/examples/package/publish_with_owner.rtm, transaction/examples/resources/creation/fungible/no_initial_supply.rtm, transaction/examples/resources/creation/fungible/with_initial_supply.rtm, transaction/examples/resources/creation/non_fungible/no_initial_supply.rtm, transaction/examples/resources/creation/non_fungible/with_initial_supply.rtm, transaction/examples/resources/mint/fungible/mint.rtm, transaction/examples/resources/mint/non_fungible/mint.rtm, transaction/src/builder/manifest_builder.rs
* This PR allows for either a `NonFungibleAddress` or `ResourceAddress` to be the minting authority of mutable resources and badges.
* Added some comments to the common manifests and made some minor changes to them.
=> Fix handling of `NonFungibleAddress`es for some Resim subcommands

sbor-derive/src/decode.rs, sbor-derive/src/encode.rs, sbor-derive/src/type_id.rs, sbor-derive/src/utils.rs
Small, independent change that may as well be merged in separately from the type schema work.
Basically it enables you to do this now - with a generic type parameter like `T`:
```
#[derive(Debug, Clone, PartialEq, Eq, Default, TypeId, Encode, Decode)]
pub struct NumericValidation<T> {
pub min: Option<T>,
pub max: Option<T>,
}
```
And the macro now expands to the following - which includes the bound `T: ::sbor::Encode<X, E>`
```
impl<T: ::sbor::Encode<X, E>, E: ::sbor::encoder::Encoder<X>, X: ::sbor::type_id::CustomTypeId>
::sbor::Encode<X, E> for NumericValidation<T>
{
#[inline]
fn encode_type_id(&self, encoder: &mut E) -> Result<(), ::sbor::EncodeError> {
encoder.write_type_id(::sbor::type_id::SborTypeId::Tuple)
}
#[inline]
fn encode_body(&self, encoder: &mut E) -> Result<(), …
```
=> feat: Improved Encode/Decode derive to work with generics

.github/workflows/ci.yml
This will remove some deprecation warnings regarding nodejx12 actions.
=> Upgrade the cancel workflow action

doc.sh
I just added the `--document-private-items` flag so that more things are displayed in the documentation like `FungibleResourceBuilder` and `NonFungibleResourceBuilder`
=> Added --document-private-items to doc generation

radix-engine/tests/time.rs, scrypto-unit/src/test_runner.rs
This adds `set_current_time` and `get_current_time` to the latest changes to `TestRunner`
=> Add set_current_time & get_current_time to TestRunner (develop)

.github/workflows/ci.yml
Updates:
- Added shared key for `rust-cache` (between resim and scrypto CLI tests)
- Removed sccache (use one cache to mitigate `429 Too Many Requests` error, hopefully!)
- Removed unnecessary Windows tests
=> Use explicit shared key

scrypto-unit/src/test_runner.rs, transaction/src/errors.rs
fix: Removed leftover transaction header validation error value from enum
=> fix: Removed leftover transaction header validation error value from enum

radix-engine/src/model/transaction_processor/executables.rs
Adds Send + Sync for NativeOutput. Needed in order to share state_manager reference between threads inside `babylon-node`.
=> add Send + Sync for NativeOutput

examples/no-std/src/lib.rs
Remove feature `default_alloc_error_handler`, which has been stabilised in `nightly` channel.
Hopefully, we will be able to use `stable` channel soon.
=> Remove default_alloc_error_handler

check.sh
Additionally get rid of hardcoded workspace packages by fetching them from Cargo.toml.
=> continue code format checking even if failed for some package

.github/workflows/ci.yml, radix-engine-constants/src/lib.rs, radix-engine/benches/radix_engine.rs, radix-engine/src/engine/interpreters/wasm_runtime.rs, radix-engine/src/fee/fee_table.rs, radix-engine/src/model/fee/module.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/tests/fee.rs, radix-engine/tests/metering.rs, radix-engine/tests/wasm_metering.rs
Rough and dirty to make a spin-loop in a modified `should_be_aborted_when_loan_repaid` test run out of juice in 350ms (on my laptop).
Also adjusted the system loan. There's still a _lot_ of adjustment to do here, which is waiting on a more holistic review.
=> fix: Tweak cost unit multipliers

radix-engine-stores/src/hash_tree/mod.rs, radix-engine-stores/src/hash_tree/test.rs, radix-engine-stores/src/hash_tree/tree_store.rs, scrypto-unit/src/test_runner.rs
A refactoring requested at https://github.com/radixdlt/babylon-node/pull/298/files#r1097250673.
=> Moving JMT's codec code to scrypto repo (using SBOR derive)

radix-engine-stores/src/hash_tree/tree_store.rs, radix-engine/src/kernel/track.rs, radix-engine/src/ledger/traits.rs, radix-engine/src/state_manager/state_diff.rs
A small follow-up to https://github.com/radixdlt/radixdlt-scrypto/pull/806.
The convenience method should be useful in Node, at https://github.com/radixdlt/babylon-node/pull/298/files#diff-5230880996b770cf628e475ce1143be291e99fd9801f307fd1702a525c351aadR971-R972.
=> Minor renames + Convenience method in StateDiff

assets/template/src/lib.rs, examples/hello-world/README.md, examples/hello-world/src/lib.rs, radix-engine/tests/blueprints/bucket/src/badge.rs, radix-engine/tests/blueprints/bucket/src/bucket.rs, radix-engine/tests/blueprints/component/src/component.rs, radix-engine/tests/blueprints/core/src/lib.rs, radix-engine/tests/blueprints/execution_trace/src/execution_trace.rs, radix-engine/tests/blueprints/fee/src/lib.rs, radix-engine/tests/blueprints/kv_store/src/precommitted.rs, radix-engine/tests/blueprints/kv_store/src/ref_check.rs, radix-engine/tests/blueprints/leaks/src/lib.rs, radix-engine/tests/blueprints/non_fungible/src/lib.rs, radix-engine/tests/blueprints/resource/src/lib.rs, radix-engine/tests/blueprints/stored_resource/src/lib.rs, radix-engine/tests/blueprints/stored_values/src/lib.rs, radix-engine/tests/blueprints/vault/src/vault.rs, scrypto/src/resource/mod.rs, scrypto/src/resource/resource_builder.rs, simulator/tests/blueprints/src/nfts.rs, simulator/tests/blueprints/src/proofs.rs
Many improvements to the ResourceBuilder
Notably:
* `initial_supply` replaced by `mint_initial_supply`
* `initial_supply_uuid` replaced by `mint_initial_supply`
* `no_initial_supply` replaced by `create_with_no_initial_supply`
* `no_initial_supply_with_owner(x)` replaced by `owner_non_fungible_badge(x).create_with_no_initial_supply()`
* `initial_supply_with_owner(x, y)` replaced by `owner_non_fungible_badge(x).mint_initial_supply(y)`
* Much improved rust docs
* Much cleaner / less duplicated code 👍
Example:
=> feature: Many improvements to the ResourceBuilder

radix-engine/src/model/epoch_manager/validator.rs
As noted on slack by Les - currently you can't stake a non-whole-number of tokens.
=> fix: Staking LP token has divisibility 18

radix-engine-derive/src/describe.rs, sbor-derive-common/src/describe.rs, sbor-derive-common/src/utils.rs
Tiny fix which fixes the `ScryptoSbor` derive
=> fix: Fix Describe for code larger than 1024 bytes

clean.sh
`clean.sh` was failing due to missing `assets/blueprints/account`.
Updated it so it hopefully handles changing paths.
Additionally added cleaning root workspace.
=> Do not use hardcoded paths in cleanup script

radix-engine-interface/src/macros.rs, radix-engine-interface/src/math/bnum_integer.rs, radix-engine-interface/src/math/bnum_integer/bits.rs, radix-engine-interface/src/math/bnum_integer/convert.rs, radix-engine-interface/src/math/bnum_integer/test.rs, radix-engine-interface/src/math/decimal.rs, radix-engine-interface/src/math/integer_test_macros.rs, radix-engine-interface/src/math/precise_decimal.rs, radix-engine-tests/tests/auth_account.rs, radix-engine-tests/tests/auth_resource.rs, radix-engine-tests/tests/common_transactions.rs, radix-engine-tests/tests/resource.rs, transaction/src/manifest/generator.rs
Fix conversions for `Decimal,` `PreciceDecimal` and `BnumXYZ` types.
This PR fix conversions according to the Rust approach:
- `From` used for conversions that not fail
- `TryFrom` used for conversion that can fail
Affected conversions:
- `Decimal`/`PreciseDecimal` from `BnumXYZ`
- `Decimal`/`PreciseDecimal` from string types
- `BnumXYZ` from `BigInt`
- `BnumXYZ` from builtin integer types
Unit tests updated accordingly to test modified conversions.
Some conversions used so far are no longer available, eg.
| No longer available           | What to use now                                               |
|-------------------------------|------------------------------------------------------------   |
|`Decimal::from("0.9")`         | `dec!("0.9")` or `Decimal::from_str("0.9").unwrap()` …
=> Fix conversions for Decimal, PreciceDecimal and BnumXYZ types.

radix-engine-tests/tests/account.rs, radix-engine-tests/tests/execution_trace.rs, radix-engine/src/kernel/track.rs, radix-engine/src/ledger/bootstrap.rs, radix-engine/src/system/kernel_modules/execution_trace/module.rs, radix-engine/src/transaction/transaction_receipt.rs
Previously, resource changes exposed the changes that happened throughout the transaction as a whole which lead to some lost resolution when trying to use the resource changes to determine how a specific instruction impacted it.
This PR changes the resource changes from being a flat vector of changes to being a map where the key is the instruction index and the value is a vector of resource changes that happened as a result of this instruction.
=> Resource changes per instruction

radix-engine-interface/src/api/types/indexed_value.rs, radix-engine/src/blueprints/transaction_processor/executables.rs, radix-engine/src/transaction/transaction_receipt.rs
This change makes the transaction receipts SBOR encodable which simplifies some of the complexity in the Radix Engine Toolkit.
=> SBOR Encodable Receipts

simulator/tests/m1.rtm, simulator/tests/m2.rtm, transaction/examples/access_controller/new.rtm, transaction/examples/access_rule/access_rule.rtm, transaction/examples/access_rule/assert_access_rule.rtm, transaction/examples/account/multi_account_resource_transfer.rtm, transaction/examples/account/resource_transfer.rtm, transaction/examples/call/call_function.rtm, transaction/examples/call/call_method.rtm, transaction/examples/faucet/free_funds.rtm, transaction/examples/metadata/metadata.rtm, transaction/examples/package/publish.rtm, transaction/examples/resources/creation/fungible/no_initial_supply.rtm, transaction/examples/resources/creation/fungible/with_initial_supply.rtm, transaction/examples/resources/creation/non_fungible/no_initial_supply.rtm, transaction/examples/resources/creation/non_fungible/with_initial_supply.rtm, transaction/examples/resources/mint/fungible/mint.rtm, transaction/examples/resources/mint/non_fungible/mint.rtm, transaction/examples/resources/worktop.rtm, transaction/examples/royalty/royalty.rtm, transaction/examples/values/values.rtm, transaction/src/manifest/ast.rs, transaction/src/manifest/generator.rs, transaction/src/manifest/lexer.rs, transaction/src/manifest/parser.rs
Drop support of PackageAddress, ComponentAddress and ResourceAddress in Manifest
You can use `Address("bech32_address")` instead.
=> Drop support for PackageAddress, ComponentAddress and ResourceAddress in Manifest

assets/blueprints/Cargo.lock, radix-engine/Cargo.toml, radix-engine/src/lib.rs, simulator/Cargo.lock
This PR replaces jemalloc with mimalloc for better cross-platform support (the Rust binding).
- [`tikv/jemallocator`](https://github.com/tikv/jemallocator) only supports limited platforms, as stated on the home page;
- [`purpleprotocol/mimalloc_rust`](https://github.com/purpleprotocol/mimalloc_rust) is tested by CI on Ubuntu, MacOS and Windows.
---
Interestingly, contradictory to Microsoft's claim, the performance is slightly worse than jemalloc.
**First CI Run**
Test | Base | PR | %
-- | -- | -- | --
Radiswap::run | 4.9±0.09ms | 5.1±0.09ms | +4.08%
SpinLoop::run | 154.3±5.20ms | 156.9±5.82ms | +1.69%
Transfer::run | 1381.5±21.88µs | 1530.0±55.96µs | +10.75%
**Second CI Run**
Test | Base | PR | %
-- | -- | -- | --
Radiswap::run | 4.9±0.05ms | 5.0±0.02ms | +2.04%
SpinLoop::run | …
=> Replace jemalloc with mimalloc

radix-engine/src/errors.rs, radix-engine/src/kernel/interpreters/scrypto_interpreter.rs, radix-engine/src/system/client_api_impl.rs, radix-engine/src/system/kernel_modules/events/error.rs, sbor/src/schema/payload_validation/payload_validator.rs, sbor/src/schema/typed_traversal/events.rs, sbor/src/schema/typed_traversal/full_location.rs, sbor/src/schema/typed_traversal/mod.rs, sbor/src/traversal/events.rs, sbor/src/traversal/traverser.rs, sbor/src/value_kind.rs
Adds a more detailed error message when schema validation fails, which includes the value path (including logical type names, where we have them!) to where the error occurred.
Example path:
"MyStruct.hello[0]->MyEnum::Option2{1}.inner[0]->MyEnum::Option1{0}.[0]->Map[0].Value->Array[0]->Tuple.[0]->Enum::{6}.[0]->Tuple.[1]->Map[0].Key"
Have added a test in `payload_validator.rs`
=> feat: Improved schema validation error message

.github/workflows/ci.yml, .vscode/settings.json, build.sh, radix-engine-common/src/data/scrypto/value_serializer.rs, simulator/Cargo.toml
So... `value_serializer` wasn't actually building(!) - and the code didn't compile... it must have been broken in the last week or so since the last merge of the node.
To fix this I've:
* Ensured the serde feature is on in VSCode, so VSCode users don't miss it ;). This has required a minor workaround to make Rust Analyzer happy...
* Ensure the serde feature is turned on in CI
* Actually fixed the compilation errors
Oh and also I've changed Own to encode the ObjectId.
=> fix: Fix compilation of value serializer

.github/workflows/fuzzing.yml, fuzz-tests/afl.sh, fuzz-tests/fuzz.sh
This PR introduces a "Fuzzing" workflow in Github Actions, which includes Transaction Fuzz job.
Workflow runs transaction fuzzing test for a given time.
Fuzz input parameters are:
- Fuzzing duration [s] - duration of the fuzzing test
- AFL timeout [ms] - maximal test case duration, above which AFL reports timeout
- Transaction fuzz input data generation mode
- `raw`  - do not process the generated raw manifest files.
- `unique` - reduce the input data by making it unique (it is processed with `cargo afl cmin`)
- `minimize` - minimize the unique input data (it is processed with `cargo afl tmin`)
Job is configured to auto-scale (start AFL instances on all available CPU cores).
As a result it should produce a `fuzz_transaction.tgz` artifact, which includes transaction fuzzing stats and data …
=> Fuzz transaction in Github Actions

.github/workflows/fuzzing.yml
Real 'Fuzzing' definition is in 'develop' branch.
This change is to make 'Fuzzing' appear in Github actions.
=> Add 'Fuzzing' stub workflow job

radix-engine-tests/tests/access_rules.rs, radix-engine/src/transaction/reference_extractor.rs
Fix bug in manifest instruction SET_METHOD_ACCESS_RULE where references in AccessRules was not being properly handled.
=> Fix manifest SET_METHOD_ACCESS_RULE references

radix-engine-tests/Cargo.toml, radix-engine-tests/benches/transaction_decompilation.rs, transaction/src/manifest/lexer.rs, transaction/src/manifest/parser.rs
This PR converts the `start` and `end` coordinates of `Token` `Span`s from being a tuple of `(usize, usize)` to being a single `usize` each and removed the `index_to_coordinate` method which was slowing down transaction compilation dramatically for large manifests.
=> Bugfix: compiler performance

.github/workflows/fuzzing.yml, fuzz-tests/afl.sh, fuzz-tests/install_afl.sh, fuzz-tests/process_fuzz_results.sh
Changes:
- Use dedicated `fuzzing` runner
- Set default transaction job timeout to 7 days
- Install additional packets at `fuzzing` runner
- Install `cargo afl` forcefully to make sure it is built with the current `rustc` version
- Add AFL status check interval parameter
- Display input params in summary
- Show current duration and time left
=> Fuzzing workflow improvements

radix-engine-tests/tests/metering.rs, radix-engine/src/kernel/kernel.rs
This PR disables size-based costing for package code loading.
It's a temporary workaround before we fine-tune the fee table and costing rules.
=> Disable size-based costing for package code loading

test_extra.sh
Fixed typo that prevented testing with `no_std` feature
=> Fix typo that prevented no_std testing

radix-engine-interface/src/blueprints/resource/access_rules.rs
Makes `get_default_mutability` public and re-adds pub `get_all_method_mutability` and `get_all_grouped_auth_mutability`.
Also adds a helper method `resolve_entry` which removes some duplication.
=> Expose access rules fields; add resolve_entry helper method

simulator/src/ledger/dumper.rs, simulator/tests/resim.sh
Let `resim show` dump both fungible and non-fungible resources.
This is to fix regression introduced in PR #900 - panic when dumping non-fungible resources:
```
thread 'main' panicked at 'Not a resource manager', ../radixdlt-scrypto/radix-engine/src/system/node_substates.rs:826:13
```
`test/resim.sh` modified to dump all entities in the ledger.
=> Fix 'resim show' non-fungibles

radix-engine-tests/tests/blueprints/transaction_limits/src/transaction_limits.rs, radix-engine-tests/tests/transaction_limits.rs
After recent refactorings, write and read substate callbacks: `on_read_substate()` and `on_write_substate()` has proper substate size argument value - added 2 new tests to validate transaction limits in case of errors: `TransactionLimitsError::MaxSubstateReadSizeExceeded` and `TransactionLimitsError::MaxSubstateWriteSizeExceeded`.
=> SCRY-329 Added new tests

radix-engine-tests/tests/arg_validation.rs, radix-engine-tests/tests/blueprints/Cargo.toml, radix-engine-tests/tests/blueprints/arg_validation/Cargo.toml, radix-engine-tests/tests/blueprints/arg_validation/src/lib.rs, radix-engine/src/transaction/transaction_receipt.rs
Adds some tests related to Atom's report in Discord - notably about confusing errors when passing a bucket/proof where the other is expected.
The relevant tests should be un-ignored when the issue is fixed.
=> tests: Add tests for distinguishing proof/bucket

.github/workflows/fuzzing.yml, fuzz-tests/afl.sh, fuzz-tests/fuzz.sh, fuzz-tests/process_fuzz_results.sh
Few changes to  make fuzzing summary more useful.
* Print fuzzing sessions log tails in summary (especially useful when workflow fails)
* Attempt to generate summary and upload artifacts even if job failed or cancelled
eg. to not loose long-term fuzzing results
* Option to setup timeout when generating fuzz input data
* Fix power schedules setting
=> Fuzzing workfow summary tweaks

.github/workflows/fuzzing.yml, fuzz-tests/Cargo.toml, fuzz-tests/afl.sh, fuzz-tests/src/transaction.rs, radix-engine-common/tests/scrypto_codec.rs, radix-engine-stores/src/hash_tree/jellyfish.rs, radix-engine-stores/src/hash_tree/tree_store.rs, radix-engine-stores/src/memory_db.rs, radix-engine-stores/src/query/accounter.rs, radix-engine-tests/tests/arguments.rs, radix-engine-tests/tests/package_schema.rs, radix-engine/Cargo.toml, radix-engine/src/vm/wasm/wasm_instrumenter.rs, radix-engine/src/vm/wasm/wasmer.rs, radix-engine/src/vm/wasm/wasmi.rs, sbor-tests/tests/deterministic.rs, sbor/Cargo.toml, sbor/src/codec/collection.rs, sbor/src/schema/well_known_types.rs, sbor/src/value.rs, scrypto-unit/src/test_runner.rs, utils/Cargo.toml, utils/src/rust.rs
Introduced few changes to improve consistency across runs for the same input data.
Following changes introduced to increase the consistency:
* Use stub hasher (instead of random one) for hash and index maps/sets
* disabled cache in VM-related stuff (most likely the cache uses some hashing inside)
* initialize static objects outside fuzzing loop
* save TestRunner state before fuzzing loop and restore it upon each fuzzing loop step
* use "resettable" lazy_static when fuzzing
Above changes increased the stability to `~99.5%`, which is good enough (for more info see _Nerd details_ below)
Additionally:
* got rid of `unsafe` when initializing well_known_lookup
It was suspected to impact consistency, but it turned out it does not. But it is always good to get rid of `unsafe` if possible.
* …
=> Fight non-deterministic instrumentation output when fuzzing

fuzz-tests/Cargo.toml
This is to prevent potential collision.
=> Use full git commit hash for resettable 'lazy_static' repo

.github/workflows/ci.yml, simulator/Cargo.toml, simulator/src/bin/rtmd.rs, simulator/src/lib.rs, simulator/src/rtmd/mod.rs
This pull request adds new command line utility `rtmd` which allows to easily decompile binary manifest file. I added this command because it is very useful when working with fuzzing.
Usage:
```bash
Radix transaction manifest decompiler
USAGE:
rtmd [OPTIONS] --output <OUTPUT> <INPUT>
ARGS:
<INPUT>    Input file
OPTIONS:
-b, --blobs                Extract blobls
-h, --help                 Print help information
-n, --network <NETWORK>    Network to Use [Simulator | Alphanet | Mainnet]
-o, --output <OUTPUT>      Path to the output file
-V, --version              Print version information
```
=> Feature: manifest decompiler command (rtmd)

radix-engine-tests/tests/events.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_modules/events/module.rs, simulator/tests/resim.sh
This PR fixes a bug in the events implementation where the event schema of events emitted by NodeModules prior to globalization could not be looked up. This is fixed by doing the appropriate replacements to the events in the event store when a node is globalized.
=> Bug fix: Events emitted by transient nodes

radix-engine-interface/src/blueprints/access_controller/invocations.rs, radix-engine-tests/tests/access_controller.rs, radix-engine/src/blueprints/access_controller/events.rs, radix-engine/src/blueprints/access_controller/package.rs, radix-engine/src/blueprints/access_controller/state_machine.rs
This PR adds the ability for the badge(s) stored in the access controller to be withdrawn. The process of withdrawing it is the same as the recovery process: it must be initiated by one role and confirmed by another role. A difference between badge withdraw and recovery is that badge withdraw can't be "timed" confirmed (i.e., can't just be confirmed after some amount of time has passed)
=> Feature: Access Controller badge withdraw

radix-engine-tests/tests/blueprints/kv_store/src/basic.rs, radix-engine-tests/tests/blueprints/kv_store/src/lib.rs, radix-engine-tests/tests/blueprints/kv_store/src/nested_kv_stores.rs, radix-engine-tests/tests/kv_store.rs, scrypto/src/component/kv_store.rs
Add lifetimes to scrypto kv_store so that it forces user to drop map entry before moving map
There currently exists a problem where locked kv entries to an unowned kv_store do not have their lifetime linked with the kv_store so it was possible in Scrypto to move the KVStore before the entries were unlocked. Radix Engine notices this though and causes an error.
This PR adds a lifetime to the kv_entry so that scrypto compilation will complain if the entry is not dropped before moving the KVStore.
Users of KeyValueStore entries must now drop the entry (e.g. by scoping the entry with brackets) if they would like to move the KeyValueStore afterwards.
=> Feature: Add Scrypto KVStoreEntry lifetime

.github/pull_request_template.md, radix-engine-common/src/address/hrpset.rs, radix-engine-common/src/native_addresses.rs, radix-engine-common/src/types/entity_type.rs, radix-engine-interface/src/api/actor_key_value_entry_api.rs, radix-engine-interface/src/types/node_layout.rs, radix-engine-queries/src/typed_substate_layout.rs, radix-engine/src/blueprints/account/blueprint.rs, radix-engine/src/blueprints/epoch_manager/epoch_manager.rs, radix-engine/src/blueprints/epoch_manager/validator.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_vault.rs
Some minor fixes as part of my merge into the Core API.
Basically added explicit types to the various partition keys and values, and removed entity types for the 
Also added some unit tests for the validator sort key (to help me make sure I understood it correctly to map it back in `typed_substate_layout`).
=> tweak: Fix up typed_substate_layout for partitions

radix-engine-interface/src/types/node_layout.rs, radix-engine-queries/src/typed_substate_layout.rs, radix-engine-tests/tests/epoch_manager.rs, radix-engine-tests/tests/events.rs, radix-engine/src/blueprints/epoch_manager/epoch_manager.rs, radix-engine/src/blueprints/epoch_manager/package.rs, radix-engine/src/vm/wasm/wasmer.rs, scrypto-unit/src/test_runner.rs
In this PR, I add internal tracking of missed/made proposal counters of validators:
- counting on round change;
- resetting on epoch change.
I follow the approach we discussed on Slack (captured as **Q4-B** at https://radixdlt.atlassian.net/wiki/spaces/S/pages/3058827265/REP-83+Calculating+Emissions+and+Handling+Validator+Fees#Unreliability-Penalty).
These numbers are not yet taken into account during Emissions (since Emissions itself is not implemented yet), and in fact, the counting has no externally observable effect on the engine's behavior (which is why I haven't invested much into tests yet - I just fixed a couple of existing tests that were breaking some newly-introduced sanity checks).
=> Tracking missed/made proposals of validators

native-sdk/src/resource/auth_zone.rs, radix-engine-tests/tests/blueprints/proof/src/vault_proof.rs, radix-engine/src/blueprints/transaction_processor/tx_processor.rs, scrypto/src/resource/auth_zone.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/proof.rs, scrypto/src/resource/vault.rs, simulator/Cargo.lock
Rename `ComponentAuthZone` to `LocalAuthZone`, since there is an auth zone for every call frame (except the root), including both component and blueprint functions.
Use `LocalAuthZone` instead of `ComponentAuthZone`
=> Rename ComponentAuthZone to LocalAuthZone

radix-engine-common/src/data/manifest/custom_value.rs, radix-engine-common/src/data/scrypto/custom_value.rs, sbor/src/basic.rs, sbor/src/encoder.rs, sbor/src/path.rs, sbor/src/value.rs
Fixes some crashes noted by Rubin whereby a Value could be encoded but that encoded Value could not be decoded.
It transpires the Value itself wasn't in a valid structure to start with, so arguably it's not too important, but I'll put in this PR for completeness and see if being fully correct impacts the benchmarks at all.
Added a couple of tests for the new behaviour
=> fix: Capture invalid SBOR values at Encode time

sbor/src/schema/schema_validation/type_metadata_validation.rs, sbor/src/schema/type_aggregator.rs, scrypto-derive/Cargo.toml, scrypto-derive/src/blueprint.rs
A small PR to capture the argument names in the blueprint schema.
It's much nicer for generating ABIs from the types (or pretty-printing manifests) if we have names :)
Also:
* Ensures that we flag idents which will be invalid at the macro level, instead of failing when we create or upload the schema. (EG catching names that are too long or don't fit out validation requirements - which are currently quite tight - `idents must match [A-Za-z][0-9A-Za-z_]{{0,99}}`)
* Captures spans a bit better in a few places where these were dropped by converting to a string and back
=> feature: Blueprint macro captures method parameter names

assets/blueprints/Cargo.lock, assets/blueprints/genesis_helper/src/lib.rs, radix-engine-interface/src/blueprints/epoch_manager/invocations.rs, radix-engine-tests/tests/bootstrap.rs, radix-engine-tests/tests/epoch_manager.rs, radix-engine-tests/tests/events.rs, radix-engine/src/blueprints/epoch_manager/epoch_manager.rs, radix-engine/src/blueprints/epoch_manager/events/validator.rs, radix-engine/src/blueprints/epoch_manager/package.rs, radix-engine/src/blueprints/epoch_manager/validator.rs, radix-engine/src/system/bootstrap.rs
⚠️ This PR builds on top of https://github.com/radixdlt/radixdlt-scrypto/pull/1029
This PR **only** introduces structs needed for **Q5-B** of https://radixdlt.atlassian.net/wiki/spaces/S/pages/3058827265/REP-83+Calculating+Emissions+and+Handling+Validator+Fees
(the impl will come in some next PR)
Also, this PR applies a few renames (mostly regarding consistent naming of "stake unit" inside validator) and adds missing rustdocs _(mostly for my own convenience, since I am recently reading a lot of code there and I sometimes forget whether some amount is XRD or SU...)_.
So, **let's use it to establish some naming** (and avoid discussing names in the coming more logic-heavy PRs).
=> Introducing "locked owner su vault" structs-only in validator + Renames

.vscode/settings.json, native-sdk/src/component/mod.rs, native-sdk/src/component/object.rs, native-sdk/src/modules/metadata/metadata.rs, radix-engine-interface/src/blueprints/access_controller/invocations.rs, radix-engine-interface/src/blueprints/resource/non_fungible_global_id.rs, radix-engine-tests/tests/access_controller.rs, radix-engine/src/blueprints/access_controller/package.rs, tx.file
* Upon the instantiation of the access controller component a new resource called the "recovery resource" is created.
* The recovery resource has the component address of the access controller in its metadata
* More of the recovery resource can be minted by the primary and recovery roles. 
There is a minor change to substates where the access controller substate now has an additional `recovery_badge` field. 
Note: The access controller uses a post_instantiation method because of the bug with preallocated addresses and references discussed in slack. Without the post instantiation function, we're unable to get the recovery badge to have the access controller's component address in its metadata.
=> Feature: Access Controller recovery badge

fuzz-tests/install_afl.sh
Current AFL version `0.13.0` suffers from below issue when starting AFL:
```
[-] PROGRAM ABORT : Timeout while initializing fork server (setting AFL_FORKSRV_INIT_TMOUT may help)
Location : afl_fsrv_start(), src/afl-forkserver.c:1184
```
Pin version until the issue resolved.
=> Pin AFL version to 0.12.17

radix-engine-stores/src/memory_db.rs, radix-engine-stores/src/rocks_db.rs, radix-engine/src/track/db_key_mapper.rs, simulator/src/resim/cmd_show_ledger.rs, simulator/tests/resim.sh
This PR fixes `resim show-ledger` command and let it display ledger entries as before.
- Added support for reverse mapping for the `DbPartitionKey` in order to retrieve `NodeId` used to restore ledger addresses.
It was agreed to change `DbPartitionKey` format to:
`HashPrefix(NodeId + ParitionNumber) + NodeId + PartitionNumber`
It extends its size from `32` to `51` bytes, which is the price wa are willing to pay to have the reverse mapping available.
- Implemented `list_partition_keys()` for `InMemorySubstateDatabase` and `RocksdbSubstateStore`
Added test to `resim.sh` to check if 'resim show-ledger' dumps entities.
Node shall be updated to align to the new `DbPartitionKey` format. Database needs to be reset.
=> fix: Let 'resim show-ledger' list items as before

radix-engine-queries/src/typed_substate_layout.rs, radix-engine-tests/tests/bootstrap.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/package.rs
This is a pure refactor (no behavior changes), as promised in https://github.com/radixdlt/radixdlt-scrypto/pull/1052#discussion_r1202637972.
=> Explicit (transparent) structs for different timestamps in ConsensusManager

sbor/src/codec/collection.rs, sbor/src/decoder.rs
As discussed, this adds a `DecodeError::DuplicateKey` if decoding to a typed Set or Map with duplicate keys.
This should catch a number of errors / potential issues - and shouldn't affect any valid payloads/manifests.
Note:
* We currently can't catch this at payload validation time - we don't have an efficient property of "identity" or "uniqueness" with respect to the value model... We could try if we think it were worth it, although there may still be misalignment between `Eq` on a typed object and `Eq` on its corresponding value.
=> feature: Duplicate keys cause decode error when doing a typed SBOR decode

transaction/examples/access_rule/access_rule.rtm, transaction/examples/account/deposit_modes.rtm, transaction/examples/metadata/metadata.rtm, transaction/examples/resources/creation/fungible/no_initial_supply.rtm, transaction/examples/resources/creation/fungible/with_initial_supply.rtm, transaction/examples/resources/creation/non_fungible/no_initial_supply.rtm, transaction/examples/resources/creation/non_fungible/with_initial_supply.rtm, transaction/examples/values/values.rtm, transaction/src/manifest/ast.rs, transaction/src/manifest/e2e.rs, transaction/src/manifest/generator.rs, transaction/src/manifest/lexer.rs, transaction/src/manifest/parser.rs
* A medium-sized refactor to the lexer/parser to separate the concept of lexing an ident, and parsing a particular symbol from that ident.
* Also enables and implements the change from `Enum<"Well::Known">()` to `Enum<Well::Known>()`
* Also fixes a bug that you couldn't specify an `Array<Map>`
As a slight change to https://github.com/radixdlt/radixdlt-scrypto/pull/1050 - enum discriminator aliases are now without quotes, eg:
```
Enum<Well::Known>()
```
=> tweak: Manifest enum variant aliases are idents

radix-engine-tests/benches/radiswap.rs, radix-engine-tests/benches/validation.rs, transaction/src/model/v1/header.rs, transaction/src/model/v1/intent.rs, transaction/src/model/v1/notarized_transaction.rs, transaction/src/model/v1/signed_intent.rs
This PR removes the feature-gated `serde::Serialize` and `serde::Deserialize` derives from a number of types which prevented certain crates from compiling when the `serde` feature is enabled.
The reason why compilation failed is because some of the types used in these structs were not serializable and deserializable, namely `Epoch` and `InstructionV1`. `Epoch` can derive the serde traits with no issues but `InstructionV1` is a bigger problem where we get into Bech32 stuff and network dependence. 
**Note**: The benchmark that's failing is not failing due to anything in this PR, this PR actually fixes the issue in benchmarks so that it works. It's failing since it's trying to benchmark this PR against the last commit in the `release/birch` branch where the benchmarks appear to be broken. It …
=> Bugfix: Serde Serialization

.github/workflows/ci.yml, assets/blueprints/Cargo.lock, examples/hello-world/Cargo.lock, examples/no-std/Cargo.lock, fuzz-tests/Cargo.toml, fuzz-tests/group_crashes.sh, fuzz-tests/src/common.rs, fuzz-tests/src/fuzz_tx.rs, fuzz-tests/src/transaction.rs, radix-engine-common/Cargo.toml, radix-engine-interface/src/api/node_modules/auth/access_rules/invocations.rs, simulator/Cargo.lock, test.sh
* Align fuzzed instructions with current `develop` branch
* Add test to detect not covered instructions
* Get rid of some hardcoded values by getting entries from DB
* Some code cleanup 
The test `test_check_fuzzed_instruction_coverage` checks for uncovered instructions.
If it finds such it panics with message `Found not covered instruction`. In such case please follow below guidelines to add support for the uncovered instructions.
For easier maintenance instructions in the huge match in `build_manifest()` are
- ordered alphabetically
- enumerated monotonically and no gaps between numbers
In order to get the list of the currently supported instructions below command might be used:
`cat transaction/src/manifest/ast.rs | awk '/pub enum Instruction/,/^}/ {print $0}' | grep -E "^[ …
=> Fuzzing updates and some tweaks

.github/workflows/bench.yml, .github/workflows/ci.yml, .github/workflows/fuzzing.yml, fuzz-tests/src/fuzz_tx.rs, radix-engine-interface/src/blueprints/resource/vault.rs
CI fixes:
- added missing instructions to the fuzzer
- pinned rust to `1.69.0`
With the rust 1.70.0 following error is being observed leading to CI failures
```
thread 'can_instantiate_with_preallocated_address' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidWasm(DeserializationError)', /runner/_work/radixdlt-scrypto/radixdlt-scrypto/scrypto-unit/src/test_runner.rs:115:44
```
Error occurs when deserializing the WASM code into a WASM module. The error is:
`UnknownOpcode(192)`
To be reverted as soon as proper fix is implemented
=> Fixes to let CI be great again

.github/workflows/ci.yml, fuzz-tests/Cargo.toml, fuzz-tests/fuzz.sh, radix-engine-queries/Cargo.toml, radix-engine-tests/Cargo.toml, radix-engine/Cargo.toml, radix-engine/src/lib.rs, scrypto-unit/Cargo.toml
This is a small PR that makes the Radix Engine compile to a `wasm32-unknown-unknown` target which is something that the Radix Engine Toolkit is increasingly needing and relying on more.
=> Feature: Radix Engine WASM Builds

.github/workflows/ci.yml, fuzz-tests/fuzz.sh
Fix simple fuzzer build. This build is used for inspecting crashes discovered during fuzzing campaign.
Added simple fuzzer build to the CI.
=> Fix simple fuzzer build

radix-engine-tests/tests/bootstrap.rs, radix-engine-tests/tests/consensus_manager.rs, radix-engine-tests/tests/static_dependencies.rs, radix-engine/src/kernel/kernel.rs, radix-engine/src/system/bootstrap.rs, scrypto-unit/src/test_runner.rs, transaction/src/model/executable.rs, transaction/src/model/v1/system_transaction.rs, transaction/src/model/versioned.rs
Fixes genesis-related issue from #1075 which was blocking merging into the node.
We now map some of the models to their Manifest counterparts, to enable us to pass the non-Manifest models over JNI.
It also improves the abstraction because users can more easily express their intent, and leave the manifest address allocation accounting to the genesis transaction constructor.
=> fix: Genesis data chunks are scrypto encodable

radix-engine-interface/src/blueprints/resource/resource_manager.rs, radix-engine-tests/tests/auth_mutability.rs, radix-engine/src/blueprints/resource/resource_manager_common.rs, radix-engine/src/transaction/transaction_receipt.rs, scrypto-unit/src/test_runner.rs
Previously the `RoleEntry`s on the resource manager were set to "mutable mutable". This meant that you could change eg the `MINT_ROLE` to be updatable by the `BURN_ROLE` instead of by the `MINT_UPDATE_ROLE`.
This breaks common sense / invariants that callers would expect.
So this PR disables the `mutable mutable` flag, and updates the relevant tests.
=> fix: Fix the resource role definitions mutable_mutable

assets/blueprints/Cargo.lock, radix-engine-constants/src/lib.rs, radix-engine-interface/src/blueprints/consensus_manager/invocations.rs, radix-engine-interface/src/types/node_layout.rs, radix-engine-queries/src/typed_substate_layout.rs, radix-engine-tests/tests/balance_changes.rs, radix-engine-tests/tests/bootstrap.rs, radix-engine-tests/tests/consensus_manager.rs, radix-engine-tests/tests/wasm_non_mvp.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/events/validator.rs, radix-engine/src/blueprints/consensus_manager/package.rs, radix-engine/src/blueprints/consensus_manager/validator.rs, radix-engine/src/errors.rs, radix-engine/src/system/bootstrap.rs, radix-engine/src/system/module_mixer.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_callback.rs, radix-engine/src/system/system_modules/auth/auth_module.rs, radix-engine/src/system/system_modules/costing/costing_module.rs, radix-engine/src/system/system_modules/costing/fee_reserve.rs, radix-engine/src/system/system_modules/costing/fee_summary.rs, radix-engine/src/system/system_modules/execution_trace/module.rs, radix-engine/src/system/system_modules/transaction_limits/module.rs, radix-engine/src/transaction/transaction_executor.rs, scrypto-unit/src/test_runner.rs, simulator/src/resim/mod.rs
This PR implements fees and tips distribution, and fixes issues with system modules (deeper refactor required though).
```
Tips: 100% proposer,
Fees: 25% proposer, 25% validator set, 50% burnt
```
Note that `proposer` and `validator set` refer to the validator owners.
These rewards are auto-staked at the end of an epoch into "owner stake units".
New tests added
- A new field `current_leader: Option<ValidatorIndex` is added to `ConsensusManager` substate;
- A new substate `ValidatorRewardsSubstate` is added.
=> Feature: distribute fees and tips to validators

radix-engine-tests/tests/kernel_lock_substate.rs, radix-engine/src/kernel/kernel.rs
I've checked `kernel.rs` and the hack logic (replacing "any" module id with "main") has been removed.
Added a test to verify the kernel behaviour when package substate is not found.
=> Test kernel lock_substate

radix-engine-tests/tests/fee.rs, radix-engine/src/system/system_modules/execution_trace/module.rs, radix-engine/src/transaction/transaction_receipt.rs
This PR adds the amount of fee locks and contingent fee locks to the transaction execution trace. This is needed by the RET and wallet for accurate fee calculation.
=> Add fee locks to execution trace

radix-engine-tests/tests/cached_wasm_limits.rs, radix-engine/src/vm/wasm/wasm_instrumenter.rs, radix-engine/src/vm/wasm/wasmer.rs, radix-engine/src/vm/wasm/wasmi.rs
Use a fixed size cache (1000 as default) for both WASM instrumenter and WASM module caches
Using a fixed size cache simplifies the caching algorithm and prevents cache bugs with the current WASM-size based cache which does not capture all resources used by the WASM module/instrumenter.
Added a `publishing_many_packages_should_not_cause_system_failure` which attempts to publish many packages.
=> Use fixed size WASM cache replacing the wasm length based cache

radix-engine-interface/src/api/node_modules/metadata/invocations.rs
Minor PR tweaking `MetadataVal` and adding some encode/decode tests.
Ideally would add transaction scenario/s for this too, but these can come later.
=> tests: Add metadata encode/decode tests

radix-engine/src/system/bootstrap.rs, radix-engine/src/system/system_modules/costing/fee_summary.rs, radix-engine/src/track/track.rs, radix-engine/src/transaction/state_update_summary.rs, radix-engine/src/transaction/transaction_receipt.rs
To enable us to handle it separately in the node, as it turns out that is the easier approach.
=> feat: Allow FlashReceipt to be converted to TransactionReceipt

assets/blueprints/metadata/src/lib.rs, radix-engine-interface/src/api/node_modules/metadata/invocations.rs, radix-engine-interface/src/blueprints/resource/resource_manager.rs, radix-engine-tests/tests/auth_resource.rs, radix-engine-tests/tests/blueprints/metadata_component/src/lib.rs, radix-engine/src/blueprints/resource/resource_manager_common.rs, radix-engine/src/system/node_modules/metadata/package.rs, scrypto/src/modules/metadata.rs, scrypto/src/resource/resource_manager.rs
Add more granular roles to Metadata
Set the roles of metadata to be:
```
metadata_setter
metadata_setter_updater
metadata_locker
metadata_locker_updater
```
If setting roles for metadata, users must now specify 4 different roles
=> Feature: Add metadata_locker role

fuzz-tests/src/fuzz_tx.rs, transaction/examples/resources/recall.rtm, transaction/src/manifest/ast.rs, transaction/src/manifest/decompiler.rs, transaction/src/manifest/e2e.rs, transaction/src/manifest/generator.rs, transaction/src/manifest/parser.rs
Renames `RECALL_VAULT` to `RECALL_FROM_VAULT`.
=> Rename RECALL_VAULT to RECALL_FROM_VAULT

.github/workflows/bench.yml
Disable bench on push commits. It's been failing all the time, because there is no target to compare against.
=> Disable bench on push commits

radix-engine-tests/tests/metadata_package.rs, radix-engine/src/blueprints/package/package.rs, radix-engine/src/system/bootstrap.rs
Updates package owner badge to use `NonFungibleIdType::Bytes`, to be consistent with other owner badges.
The non-fungible local id of package owner badge is now `NonFungibleLocalId("[<hex encoded raw bytes of address>]`, instead of RUID.
=> Update package owner badge to be consistent with other owner badges

radix-engine/src/blueprints/pool/two_resource_pool/blueprint.rs
A very small PR that changes the amount in the `ContributionEvent` of the two-resource pool from being the amount that the user tried to contribute to the amount that was accepted as a contribution.
=> Minor fix to `ContributionEvent` of the two-resource pool

radix-engine-tests/tests/consensus_manager.rs, radix-engine/src/system/system_modules/module_mixer.rs
- Added tests to reproduce Babylon migration error
- Disabled limits module for system and genesis transactions (before Node has better understanding about the bounds).
=> Disable limits module for genesis and system transactions

radix-engine/src/errors.rs, radix-engine/src/kernel/kernel.rs
Simple naming fix to `DrainSubstatesError`
=> Fix error naming

radix-engine/src/kernel/call_frame.rs
Add error for owned nodes being scanned in scan_sorted_substates
=> Fix FIXME: Add OwnedNodeNotSupported error to scan_sorted_substates

radix-engine-tests/tests/proof_creation.rs, radix-engine/src/blueprints/resource/auth_zone_composition.rs
Remove costing FIXMEs in proof composition. The loop is taken into account through kernel API costing.
=> Feature/remove proof composition FIXMEs

transaction-scenarios/src/accounts.rs, transaction-scenarios/src/scenarios/metadata.rs
Add predefined accounts which will be used as dApp definition addresses for project's team whenever new network is created
=> add dApps related accounts in metadata scenario

fuzz-tests/src/fuzz_tx.rs
Reading nonfungible vault substate values has changed since [this commit](https://github.com/radixdlt/radixdlt-scrypto/commit/c54691544736a1a33c1c4dd6fedc9e0c0240986e)
=> Fix reading nonfungible vault substate values in fuzzer

radix-engine-tests/assets/cost_flash_loan.csv, radix-engine-tests/assets/cost_mint_large_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_mint_small_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_publish_large_package.csv, radix-engine-tests/assets/cost_radiswap.csv, radix-engine/src/vm/wasm/wasm_validator_config.rs
Adjust `call_per_local_cost` calculation 
Reuse already existing `InstructionWeights.call_per_local` (the way [Substrate does](https://github.com/paritytech/substrate/blob/monthly-2023-06/frame/contracts/src/schedule.rs#L747))
Cost metering tests were updated
=> Adjust call_per_local_cost

transaction/src/builder/manifest_builder.rs
ManifestBuilder currently doesn't have a `Default` trait implementation which is useful for the use with e.g. `men::take`
Since the whole ManifestBuilder is not covered by tests yet (?), I tested it manually by using a fork of the Scrypto repo as target in our blueprint tests.
=> Feature / Add Default trait implementation for ManifestBuilder

radix-engine-common/src/math/decimal.rs, radix-engine-common/src/math/precise_decimal.rs, radix-engine-tests/tests/consensus_manager.rs
Fix basic arithmetics for `Decimal` and `PreciseDecimal` types.
- Assure that basic arithmetic operations between: `Decimal` and `PreciseDecimal`, `Decimal` and primitive types, `PreciseDecimal` and primitive types are transitive. Which means they produce  expected type no matter the order of the operand types.
- Additionally results of such operations shall be equal, if operands are derived from the same value
Example 1:
`Decimal(10)` * `PreciseDecimal(10)` = `PreciseDecimal(100)`
`PreciseDecimal(10)` * `Decimal(10)` = `PreciseDecimal(100)`
Example 2:
`Decimal(10)` * `10_u32` = `Decimal(100)`
`10_u32` * `Decimal(10)` = `Decimal(100)`
This PR addresses the [issue reported by the community](https://discord.com/channels/417762285172555786/765994894749597697/1129167191057645709) 
Respective …
=> Fix decimal and precise decimal arithmetics

radix-engine-interface/src/blueprints/account/invocations.rs, radix-engine-tests/assets/cost_flash_loan.csv, radix-engine-tests/assets/cost_mint_large_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_mint_small_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_radiswap.csv, radix-engine-tests/assets/cost_transfer.csv, radix-engine-tests/assets/cost_transfer_to_virtual_account.csv, radix-engine-tests/tests/account_deposit_modes.rs, radix-engine/src/blueprints/account/blueprint.rs, radix-engine/src/blueprints/account/package.rs, scrypto/src/component/stubs.rs, transaction-scenarios/src/scenarios/account_authorized_depositors.rs
More renames to the account interface following #1309. Should have no effect on any downstream clients aside from the toolkit.
=> Cleanup: More Account Renames

radix-engine-tests/tests/package.rs, radix-engine-tests/tests/wasm_validation.rs, radix-engine/Cargo.toml, radix-engine/src/blueprints/package/package.rs, radix-engine/src/vm/wasm/errors.rs, radix-engine/src/vm/wasm/prepare.rs, radix-engine/src/vm/wasm/wasm_validator.rs
All Wasm exported names and Blueprint name and its components should follow Rust Identifier specification
Added new functions: `enforce_export_names()` into `WasmModule` and `validate_names` into `package` module which uses `syn` crate `parse_str()` function to validate `Ident` conformance.
Added new test which verifies if prohibited names are rejected with appropriate error.
If anyone was using non 'Ident' conformant names, such Wasm/Blueprint will fail now.
=> Features/SCRY-452 Blueprint and Wasm export names validation

.github/workflows/ci.yml, radix-engine-common/src/math/bnum_integer.rs, radix-engine-common/src/math/bnum_integer/bits.rs, radix-engine-common/src/math/bnum_integer/test_macros.rs
Assure `bnum_integer` will panic on overflow for `release` variant
Below tests were failing
```
cargo nextest run --release    -p radix-engine-common 
-E '(test(bnum) & test(overflow) & test(test_sh)) | test(test_0b10000001_next_power_of_two)'
```
=> Fix bnum_integer overflows

radix-engine-tests/tests/account_authorized_depositors.rs, radix-engine/src/blueprints/account/blueprint.rs, radix-engine/src/blueprints/account/package.rs, transaction-scenarios/generated-examples/fungible_resource/005--fungible-max-div-freeze-withdraw.rtm, transaction-scenarios/generated-examples/fungible_resource/006--fungible-max-div-freeze-deposit.rtm, transaction-scenarios/generated-examples/fungible_resource/007--fungible-max-div-freeze-burn.rtm, transaction-scenarios/generated-examples/fungible_resource/008--fungible-max-div-recall-frozen-vault.rtm, transaction-scenarios/generated-examples/fungible_resource/009--fungible-max-div-unfreeze-withdraw.rtm, transaction-scenarios/generated-examples/fungible_resource/010--fungible-max-div-unfreeze-deposit.rtm, transaction-scenarios/generated-examples/fungible_resource/011--fungible-max-div-unfreeze-burn.rtm, transaction-scenarios/generated-examples/fungible_resource/012--fungible-max-div-recall-unfrozen-vault.rtm, transaction-scenarios/generated-examples/fungible_resource/013--fungible-max-div-freeze-withdraw-again.rtm, transaction-scenarios/generated-examples/fungible_resource/021--fungible-min-div-recall-correct-granularity.rtm, transaction-scenarios/generated-examples/fungible_resource/022--fungible-min-div-recall-wrong-granularity.rtm, transaction-scenarios/generated-examples/non_fungible_resource/008--non-fungible-resource-freeze-deposit.rtm, transaction-scenarios/generated-examples/non_fungible_resource/009--non-fungible-resource-freeze-deposit.rtm, transaction-scenarios/generated-examples/non_fungible_resource/010--non-fungible-resource-recall-frozen-vault.rtm, transaction-scenarios/generated-examples/non_fungible_resource/011--non-fungible-resource-unfreeze-withdraw.rtm, transaction-scenarios/generated-examples/non_fungible_resource/012--non-fungible-resource-unfreeze-deposit.rtm, transaction-scenarios/generated-examples/non_fungible_resource/013--non-fungible-resource-unfreeze-burn.rtm, transaction-scenarios/generated-examples/non_fungible_resource/014--non-fungible-resource-recall-unfrozen-vault.rtm
This PR changes the behavior of the authorized depositor badge such that it's only checked if it's needed. If the resource deposit is permitted without the authorized depositor badge, then it happens, otherwise, we check the badge.
=> Cleanup authorized depositor badge behavior

assets/blueprints/Cargo.lock, radix-engine/Cargo.toml
The current version of moka (`0.9.4`) has a bug (https://github.com/moka-rs/moka/pull/272). Updated to version `0.9.9` which fixed bug.
=> Update moka version

radix-engine-tests/tests/system_genesis_packages.rs, radix-engine/src/blueprints/package/package.rs
Add owner role to initial boostrapped package object so that we don't induce `SubstateFault` when calling `PackageRoyalty_claim_royalties`
=> Add owner role to initial bootstrapped package objects

radix-engine-common/src/macros.rs, radix-engine-common/src/math/bnum_integer.rs, radix-engine-common/src/math/bnum_integer/bits.rs, radix-engine-common/src/math/bnum_integer/convert.rs, radix-engine-common/src/math/bnum_integer/test.rs, radix-engine-common/src/math/decimal.rs, radix-engine-common/src/math/precise_decimal.rs, radix-engine-interface/src/blueprints/resource/mod.rs, radix-engine-tests/tests/auth_account.rs, radix-engine/src/blueprints/consensus_manager/validator.rs, radix-engine/src/blueprints/resource/fungible/fungible_resource_manager.rs
Examples:
BnumI256 -> I256
BnumU256 -> U256
Revise scrypto code and rename Bnum types accordingly
=> Rename Bnum integer types

radix-engine-tests/tests/common_transactions.rs, radix-engine/src/blueprints/resource/fungible/fungible_resource_manager.rs
Adjust mint limit to 2^152
Tests added to verify the limits.
Make sure to not mint or create resources with inital supply greater than 2^152.
=> Adjust mint limit to 2^152

radix-engine-tests/benches/resources_usage.rs, radix-engine-tests/benches/transfer.rs, radix-engine-tests/tests/bootstrap.rs, radix-engine-tests/tests/common_transformation_costs.rs, radix-engine-tests/tests/fuzz_transactions.rs, radix-engine-tests/tests/kernel_open_substate.rs, radix-engine-tests/tests/preview.rs, radix-engine-tests/tests/system_db_checker.rs, radix-engine-tests/tests/transaction_executor.rs, radix-engine-tests/tests/transaction_multi_threaded.rs, radix-engine-tests/tests/transaction_tracker.rs, radix-engine-tests/tests/typed_substate_layout.rs, radix-engine/src/system/bootstrap.rs, radix-engine/src/transaction/preview_executor.rs, radix-engine/src/transaction/transaction_executor.rs, scrypto-unit/src/test_runner.rs, simulator/src/resim/cmd_publish.rs, simulator/src/resim/cmd_show.rs, simulator/src/resim/cmd_show_ledger.rs, simulator/src/resim/mod.rs, transaction-scenarios/src/runners/dumper.rs
Require explicit network definition when setting up `ExecutionConfig` to prevent wrong definitions from being used
=> Architecture: Explicit network definition

simulator/Cargo.toml, simulator/src/resim/cmd_publish.rs, simulator/src/scrypto/cmd_build.rs, simulator/src/utils/cargo.rs
This PR moves wasm-opt from being a feature flag to being an arg to the scrypto cli tool. By default, wasm-opt is enabled. The wasm-opt arg must be passed in to disable it.
=> Move wasm-opt from feature flag to cli arg

radix-engine-tests/tests/validator.rs, radix-engine/src/blueprints/consensus_manager/validator.rs
Add some Validator Logic cleanup including not panicking on decimal overflows as well as dividing before multiplying when computing redemption value.
=> Some Validator logic cleanup

radix-engine-common/src/constants/transaction_execution.rs, radix-engine-tests/tests/blueprints/transaction_limits/src/transaction_limits.rs, radix-engine-tests/tests/transaction_limits.rs, radix-engine/src/vm/wasm/errors.rs, radix-engine/src/vm/wasm_runtime/scrypto_runtime.rs
Limit the number of buffers in WasmRuntime
New tests added
=> Limit the number of buffers in WasmRuntime

radix-engine-common/src/constants/transaction_execution.rs, radix-engine-common/src/constants/transaction_validation.rs, radix-engine-common/src/constants/wasm.rs, radix-engine-tests/tests/common_transformation_costs.rs, radix-engine-tests/tests/fee.rs, radix-engine-tests/tests/metering.rs, radix-engine-tests/tests/native_vm.rs, scrypto-unit/src/test_runner.rs
- Reduced system loan amount to 4,000,000
- Updated metadata key and value size limit to 100 and 4096 respectively
- Restricted URL and origin length limit to 1024
=> Adjust limits for RCNet v3 (Part 1)

assets/blueprints/genesis_helper/src/lib.rs, radix-engine-common/src/macros.rs, radix-engine-interface/src/blueprints/consensus_manager/invocations.rs, radix-engine-interface/src/blueprints/resource/resource.rs, radix-engine-queries/src/query/accounter.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/validator.rs, radix-engine/src/blueprints/resource/auth_zone/auth_zone_composition.rs, radix-engine/src/blueprints/resource/fungible/fungible_bucket.rs, radix-engine/src/blueprints/resource/fungible/fungible_resource_manager.rs, radix-engine/src/blueprints/resource/fungible/fungible_vault.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_bucket.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_resource_manager.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_vault.rs, radix-engine/src/system/bootstrap.rs, radix-engine/src/system/node_modules/royalty/package.rs, radix-engine/src/system/system_modules/costing/fee_reserve.rs, radix-engine/src/system/system_modules/costing/fee_summary.rs, radix-engine/src/system/system_modules/execution_trace/module.rs, radix-engine/src/transaction/state_update_summary.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/src/transaction/transaction_receipt.rs
Inspect Decimal operations unwraps.
- replace (if necessary) them with proper error handling
- annotate those safe ones
- annotate those to be done later
NOTE: Unwraps in tests were left as is.
=> Decimal arithmetic operation inspection

assets/blueprints/Cargo.lock, examples/everything/Cargo.lock, examples/hello-world/Cargo.lock, examples/no-std/Cargo.lock, radix-engine-derive/Cargo.toml, radix-engine-macros/Cargo.toml, radix-engine-macros/src/lib.rs, radix-engine-profiling/resources-tracker-macro/Cargo.toml, radix-engine/Cargo.toml, sbor-derive-common/Cargo.toml, scrypto-derive/Cargo.toml, scrypto-test/src/environment/env.rs, simulator/Cargo.lock
Use `syn` from `github.com` as there is issue downloading from `crates.io` by CI.
=> Use syn on github.com

radix-engine-stores/src/hash_tree/hash_tree_facade.rs, radix-engine-stores/src/hash_tree/mod.rs, radix-engine-stores/src/hash_tree/test.rs, radix-engine-stores/src/hash_tree/tree_store.rs
This PR fixes a problem discovered while implementing the "partition deletion support in JMT" (https://whimsical.com/babylon-work-tracker-Am2s7hSa7xHd5yCxgub67a@2bsEvpTYSt1HioteqmFu91DtjNfFVJXfM4N) and is not its prerequisite.
The problem is exposed by a newly-added test https://github.com/radixdlt/radixdlt-scrypto/commit/90a2824a54543a73d8f3f9f4393dfb339af21a3a#diff-1af1904ec25c16634db8427a89ec05376f0d9d4973fe831f9578663c4ff9c2feR98 and described at https://github.com/radixdlt/radixdlt-scrypto/commit/b686ddacdfe0b403f1a47ad9574b64638e88d789#diff-38bf4cc229d9101c3b6f8ecb5d5d9707dcc784070c2d9c14f4cabbb3c6905031R126-R132
⚠️ The problem is **not** specific to _batch_ partition deletion.
Rather, it occurs every time _a last-but-one higher-tier leaf (e.g. partition or a ReNode) is entirely …
=> Fix for JMT losing track of lower-tier version after (specific) deletes

radix-engine-common/src/math/decimal.rs, radix-engine-common/src/math/precise_decimal.rs
This PR restores arithmetic operands for decimal types.
Following operands are available: 
- addition: `+` and `+=`
- substraction: `-` and `-=`
- multiplication: `*` and `*=`
- division: `/` and `/=`
- negation: `-`
It is possible to combine above operator for `Decimal`/`PreciseDecimal` with
- primitive integer types
- Radix Engine integer types: `I192`, `U192`, `I256`, `U256`,...
Relevant tests have been added.
NOTE!
These operations will panic in case of overflow or division by zero.
=> Restore arithmetic operands for decimal types

radix-engine/src/system/bootstrap.rs, radix-engine/src/track/track.rs, radix-engine/src/transaction/transaction_executor.rs, scrypto-unit/src/test_runner.rs
As discussed on Slack, this PR:
- drops `database_updates` from receipt struct,
- fixes doc on batch vs individual changes.
=> Minor clean-up of transaction receipt struct

radix-engine/src/transaction/transaction_receipt.rs
For the preview response from the Core API, as mentioned in the doc comment
Core API preview should call `into_versioned()` before scrypto encoding the receipt.
=> feat: Versioned transaction receipt model for the Core API

radix-engine-common/src/data/manifest/model/manifest_proof.rs, radix-engine-tests/tests/transaction.rs, radix-engine/src/blueprints/transaction_processor/tx_processor.rs, transaction/src/model/executable.rs, transaction/src/validation/id_validator.rs
This PR makes some minor clean ups to the transaction processor, fixes a bug in the transaction validator that caused some transactions to be rejected, and adds some tests for the transaction processor. 
Cleaned up the invocation logic in the transaction processor so that it all goes through a single `handle_invocation` function instead of multiple different macros that can go out of sync.
Fixed a bug in the transaction validator whereby instructions like `DROP_NAMED_PROOFS` and `DROP_ALL_PROOFS` dropped the proofs without reducing the ref count in the bucket, this lead the bucket to remain locked and for the transaction to be rejected (this is a rejection and not a failure because this was a bug in the transaction validator, not the engine itself).
The following is an example manifest …
=> Test: Transaction Processor

radix-engine-stores/src/hash_tree/hash_tree_facade.rs, radix-engine-stores/src/hash_tree/mod.rs, radix-engine-tests/tests/jmt_consistency.rs, scrypto-unit/src/hash_tree_support.rs, scrypto-unit/src/test_runner.rs
⚠️ This relies on https://github.com/radixdlt/radixdlt-scrypto/pull/1447 
This PR only adds a test, which runs all scenarios and asserts that `substate_db.list_all_substate_values().map(::hash) == jmt.list_all_leaf_value_hashes`.
I want it since:
- we recently had a bug in JMT (which didn't break core merkle root behaviors, so it was not detected by any high-level tests [because we don't have "generate proof" feature yet])
- I am currently implementing a "delete partition" operation in substate_db and jmt and this test will also cover it nicely
=> Tests: consistency of substate store vs JMT leafs after scenarios

radix-engine-common/src/macros.rs, radix-engine-common/src/math/bnum_integer/bits.rs, radix-engine-common/src/math/bnum_integer/convert.rs, radix-engine-common/src/math/decimal.rs, radix-engine-common/src/math/precise_decimal.rs, radix-engine-interface/src/blueprints/resource/mod.rs
- Various decimal optimizations 
- refactor `truncate()` to `checked_truncate()` with rounding mode as parameter
Optimizations list:
- Add ONE_TENTH constant
- Let `dec!` and `pdec!` macros use decimal constants for elementary values
- Remove `to_vec()` from Integer types
- Remove rotate methods from Integer types 
- Remove By trait from Integer types
- Add conversion to primitive integer types for `Decimal` and `PreciseDecimal`
- Add missing tests for conversion from primitive types
- Add tests for conversion to primitive types
Refactor scrypto sources to  `checked_truncate()`
=> Decimal various optimizations

radix-engine-tests/tests/blueprints/clock/src/lib.rs, scrypto/src/prelude/mod.rs
Add `TimePrecision` to `scrypto::prelude`
Test updated
No longer need to import `TimePrecision` explicitly in scrypto code.
=> Add `TimePrecision` to scrypto::prelude

radix-engine-tests/tests/blueprints/Cargo.toml, radix-engine-tests/tests/blueprints/event-replacement/Cargo.toml, radix-engine-tests/tests/blueprints/event-replacement/src/lib.rs, radix-engine-tests/tests/events.rs, radix-engine/src/system/node_modules/metadata/events.rs
Add tests for event replacements. A quick into into event replacements and why they take place. Any event that is emitted by a node module prior to it being attached need to have replacements done to their event type identifiers to reflect that. As an example, if the metadata module A was created, emitted an event, and then was attached to component B, then the event emitted by module A should be changed to say that it was emitted by the metadata module of component B.
=> Tests for event replacements

transaction/src/validation/transaction_validator.rs
Fix a bug where `args` in `CallDirectVaultMethod` are not used for move static check.
=> Fix a bug in transaction validation

examples/everything/Cargo.lock, examples/everything/src/lib.rs, examples/no-std/Cargo.lock, radix-engine-interface/src/types/level.rs, scrypto-unit/src/test_runner.rs, scrypto/Cargo.toml, scrypto/src/macros.rs, scrypto/src/runtime/logger.rs, simulator/src/resim/cmd_publish.rs, simulator/src/scrypto/cmd_build.rs, simulator/src/utils/cargo.rs, simulator/tests/scrypto.sh
Add `--log-level` to `scrypto build`
Usage:
```
scrypto-build 
Build a Scrypto package
USAGE:
scrypto build [OPTIONS]
OPTIONS:
--disable-wasm-opt
When passed, this argument disables wasm-opt from running on the built wasm
-h, --help
Print help information
--log-level <MIN_LOG_LEVEL>
The max log level, such as ERROR, WARN, INFO, DEBUG and TRACE. The default is INFO
--path <PATH>
The package directory
-t, --trace
Turn on tracing
```
=> Filter logs based on level

radix-engine-tests/tests/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs
- Use total effective stake, instead of total stake, when distributing "validator set rewards", so to hand them out ASAP.
- Reset the `proposer_rewards` at epoch end, for the extreme case where `zero` stake validator is in the validator set
=> Clean up validator rewards distribution

radix-engine-profiling/resources-tracker-macro/scripts/convert.py, radix-engine-profiling/resources-tracker-macro/src/lib.rs, radix-engine/src/kernel/kernel.rs
Added missing `trace_resources` to `kernel_create_node_from` function, cleaned up other `trace_resources` macro calls.
Updated Python conversion script (cleanup + handling of possible overflowed CPU instructions values due to calibration inaccuracy).
Optimised resource tracker CPU instructions reading place.
=> Resource tracker related update

radix-engine-common/src/data/scrypto/custom_well_known_types.rs, radix-engine-common/src/lib.rs, radix-engine-common/src/macros.rs, radix-engine-common/src/math/bnum_integer/convert.rs, radix-engine-common/src/math/decimal.rs, radix-engine-common/src/math/precise_decimal.rs, radix-engine-interface/Cargo.toml, radix-engine-interface/src/lib.rs, radix-engine-interface/src/macros.rs, radix-engine-macros/Cargo.toml, radix-engine-macros/src/decimal.rs, radix-engine-macros/src/lib.rs, radix-engine-macros/src/unwind.rs, radix-engine-tests/tests/decimal.rs, radix-engine-tests/tests/error_injection.rs, radix-engine/Cargo.toml, scrypto-derive-tests/tests/math.rs
Macros `dec!()` and `pdec!()` are capable to define a compile-time constant.
Additional changes:
- Remove `dec!()`and `pdec!()` macro variants with shifting
Respective tests have been implemented 
It is possible to declare any `Decimal`/`PreciseDecimal` as a compile-time constant.
```
const a: Decimal = dec!(222);
const b: Decimal = dec!("0.000001");
``` 
The same applies for `PreciseDecimal`
=> Implement compile-time `dec!` and `pdec!` macros

.github/workflows/ci-scrypto-builder.yml
this makes sure that the image built in CI is only published to the private repo where people can't pull from
=> avoid publishing to public registry

.github/workflows/fuzzing.yml, fuzz-tests/fuzz.sh, fuzz-tests/src/bin/decimal.rs, fuzz-tests/src/bin/parse_decimal.rs, fuzz-tests/src/bin/wasm_instrument.rs, fuzz-tests/src/utils/fuzz_template.rs, fuzz-tests/src/utils/mod.rs
- Add `fuzz_template!()` macro to setup all fuzz tests: `libfuzzer`, `afl`, `simple-fuzzer` at once.
- option to create empty input for given fuzzing target
eg. `./fuzz.sh generate-input decimal empty`
=> Some improvements to fuzzing

.vscode/settings.json, fuzz-tests/Cargo.toml, fuzz-tests/fuzz.sh, fuzz-tests/src/bin/attached_modules/role_assignment.rs, fuzz-tests/src/bin/attached_modules/royalty_state.rs, fuzz-tests/src/utils/fuzz_utils.rs, fuzz-tests/src/utils/mod.rs, native-sdk/src/modules/royalty/royalty.rs, radix-engine-common/src/types/royalty_amount.rs, radix-engine-interface/src/api/node_modules/royalty/invocations.rs, radix-engine-interface/src/blueprints/package/invocations.rs, radix-engine-interface/src/types/royalty_config.rs, radix-engine/src/system/checkers/component_royalty_db_checker.rs, radix-engine/src/system/checkers/error.rs, radix-engine/src/system/checkers/mod.rs, radix-engine/src/system/checkers/package_royalty_db_checker.rs, radix-engine/src/system/checkers/role_assignment_db_checker.rs, radix-engine/src/system/checkers/system_db_checker.rs, scrypto-unit/src/test_runner.rs
Added fuzz tests for the component royalty module and the package royalty state. This test checks for the following:
* If the royalty amount could be set to anything negative or above the maximum.
* If royalties could be defined for any function that doesn't exist on the package.
* If the royalty transactions result in a native-vm panic.
This fuzzer invokes the royalty module pre and post attachment for added checks.
The next steps would be to add fuzz tests for the accounting of royalties and to ensure that the final royalties shown in transactions withstand random inputs.
=> Fuzz: Royalty module state

fuzz-tests/install_afl.sh
Update `cargo-afl` to `0.14.1`. To align with `afl` crate.
=> Update cargo-afl to 0.14.1

fuzz-tests/src/bin/system.rs, radix-engine-common/src/types/addresses/global_address.rs, radix-engine-interface/src/types/level.rs, radix-engine/src/system/checkers/component_royalty_db_checker.rs
Speed up System Fuzzer. Add `Sys` system calls to System Fuzzer.
=> Test: System Fuzzer Updates

.github/workflows/cpu_instructions.yml, monkey-tests/Cargo.toml, radix-engine-profiling/resources-tracker-macro/scripts/convert.py
Updated QEMU github workflow.
All tests from `monkey-tests` takes 5~6 hours of QEMU execution, which is very close to github job time limit (6h). Because of that these tests has been divided into two separate jobs (automatic extraction of half of these tests to separate job).
Also updated `convert.pl` script to remove not needed data output.
Successful action run: https://github.com/radixdlt/radixdlt-scrypto/actions/runs/6377443462
=> QEMU workflow update

.github/workflows/fuzzing.yml, fuzz-tests/fuzz.sh, fuzz-tests/list-fuzz-targets.sh, fuzz-tests/process_fuzz_results.sh, fuzz-tests/src/bin/system.rs
* Fix artifact upload
* Fix: detect target in process_fuzz_results.sh 
* Add list-fuzz-targets.sh
* Detect available targets in fuzz.sh
* Do not expect afl binary if 'raw' input mode set
* Remove warning
* Add royalty_state target to fuzzing workflow
=> Fuzzer: some fixes and improvements

radix-engine-stores/Cargo.toml, simulator/Cargo.lock
Updating `rocksdb` version to the latest one. Mainly to fix compilation issue on Fedora 38 (more info: https://rdxworks.slack.com/archives/C01HK4QFXNY/p1696517359860749).
=> Update rocksdb version

simulator/Cargo.lock, simulator/Cargo.toml, simulator/src/replay/cmd_run.rs, simulator/src/replay/cmd_sync.rs, simulator/src/replay/mod.rs
Add `replay sync <state_manager_db> <destination_db>` which will sync and execute the transactions from the state_manager_db. Part of this process will be checking that the state hashes match.
=> Feature: Add "replay sync" command

radix-engine-tests/tests/blueprints/metadata_component/src/lib.rs, radix-engine-tests/tests/metadata_component.rs, radix-engine/src/system/attached_modules/metadata/package.rs
Added verification of metadata key length in calls to functions: `get`, `lock` and `remove`, so the flow of the execution will be stopped in case of too long key and no internal calls to system and kernel layers will be invoked.
Improved memory handling when creating metadata with initial data.
Added new test to validate key length check.
Before this PR, querying with too long key will return `None` (as a metadata for such a key cannot be found in db), after this PR error: `MetadataError::KeyStringExceedsMaxLength` will be returned.
=> [ON HOLD] Metadata module refactoring

radix-engine-common/src/network/mod.rs, simulator/src/replay/cmd_measure.rs, simulator/src/replay/ledger_transaction_execution.rs, simulator/src/replay/mod.rs
Add CLI for measuring execution time and cost.
=> Add CLI for measuring execution time and cost

radix-engine-tests/tests/logging.rs, simulator/src/scrypto_bindgen/mod.rs
A test is failing because of the update in the output of Rust panics. This PR fixes this issue and updates the test to make it more resistant to refactoring
=> Make logging test more resistant to refactoring

radix-engine-interface/src/api/object_api.rs, simulator/src/scrypto_bindgen/mod.rs
Add Serialize/Deserialize to `AttachedModuleId` for the purpose fuzzing
=> Add serde::Serialize/Deserialize to AttachedModuleId

transaction/src/builder/manifest_builder.rs
Use proper method when reserving the proof name.
=> Fix proof name reservation

radix-engine-stores/src/rocks_db_with_merkle_tree/mod.rs, simulator/src/replay/cmd_alloc_dump.rs, simulator/src/replay/cmd_execute.rs, simulator/src/replay/cmd_execute_in_memory.rs, simulator/src/replay/cmd_measure.rs, simulator/src/replay/cmd_sync.rs, simulator/src/replay/ledger_transaction_execution.rs
- Add `--trace` option to replay CLIs
- Do not commit before state comparison
=> Add --trace option to replay CLIs

radix-engine-common/src/data/scrypto/model/non_fungible_local_id.rs
Constant constructors for `NonFungibleLocalId`.
This PR has no behavioral changes. It only adds `const` constructors for `NonFungibleLocalId` to allow it to be used in const contexts.
The previous set of constructors is kept in place with very few changes in order to maintain backward compatibility. A new set of const constructors with the `const` prefix in their name have been added: `const_integer`, `const_ruid`, `const_string`, and `const_bytes`.
Feel free to review each commit separately.
=> Const constructors for `NonFungibleLocalId`s

assets/template/.gitignore, radix-engine-common/Cargo.toml, radix-engine-common/src/constants/transaction_execution.rs, radix-engine-common/src/constants/wasm.rs, radix-engine/Cargo.toml, radix-engine/src/transaction/transaction_executor.rs, radix-engine/src/utils/coverage.rs, radix-engine/src/utils/mod.rs, radix-engine/src/vm/wasm/prepare.rs, radix-engine/src/vm/wasm/wasmer.rs, radix-engine/src/vm/wasm/wasmi.rs, scrypto-unit/Cargo.toml, scrypto-unit/src/test_runner.rs, scrypto/Cargo.toml, scrypto/src/lib.rs, simulator/Cargo.lock, simulator/Cargo.toml, simulator/src/resim/cmd_publish.rs, simulator/src/scrypto/cmd_build.rs, simulator/src/scrypto/cmd_coverage.rs, simulator/src/scrypto/cmd_test.rs, simulator/src/scrypto/error.rs, simulator/src/scrypto/mod.rs, simulator/src/scrypto_bindgen/mod.rs, simulator/src/utils/cargo.rs, simulator/src/utils/coverage.rs, simulator/src/utils/mod.rs, simulator/tests/scrypto_coverage.sh
This PR adds new command `scrypto coverage` which allows to create code coverage report from tests. It was implemented based on https://github.com/hknio/code-coverage-for-webassembly findings.
Please let me know what you think, in same cases I had to use ugly approach like:
```rust
/// The maximum invoke payload size.
#[cfg(not(feature = "coverage"))]
pub const MAX_INVOKE_PAYLOAD_SIZE: usize = 1 * 1024 * 1024;
#[cfg(feature = "coverage")]
pub const MAX_INVOKE_PAYLOAD_SIZE: usize = 32 * 1024 * 1024;
```
If you have better idea how it could be implemented, please let me know.
In the next commit I'll add test_coverage.sh script, the only problem is I'll need to install nightly version of rust and the same version of llvm as nightly rustc is using. Should I add it in Dockerfile or somewhere …
=> Code coverage support for tests (scrypto coverage command)

radix-engine-profiling/src/rocks_db_metrics/mod.rs, radix-engine-queries/src/query/traverse.rs, radix-engine-store-interface/src/interface.rs, radix-engine-stores/src/hash_tree_support.rs, radix-engine-stores/src/memory_db.rs, radix-engine-stores/src/rocks_db.rs, radix-engine-stores/src/rocks_db_with_merkle_tree/mod.rs, radix-engine/src/system/bootstrap.rs, radix-engine/src/system/system_db_reader.rs
This **non-breaking, internal-only change** PR adds a `list_entries_from(from_sort_key)` next to the existing `list_entries()` in `SubstateDatabase`.
Node needs to be capable of starting substate listing from a specific key/prefix, in order to implement pagination in Browse API endpoints (like https://radixdlt.atlassian.net/wiki/spaces/RPNV1/pages/3189211214/RNP-12+-+Browse+API+sub-API+within+Core+API#5.-Object-Collection-Listing).
Node could reach out directly to its RocksDB (and avoid changes to `SubstateDatabase` interface), but Node tries hard (successfully) to implement Browse API through the Engine's `SystemDatabaseReader` API, and that's why I prefer to propagate this change here.
The exact Node `TODO`: https://github.com/radixdlt/babylon-node/pull/741/files#diff-148a2d8426fe568c7f0 …
=> Adding `SubstateDatabase::list_entries_from()` variant

simulator/src/scrypto_bindgen/translation.rs, simulator/src/utils/common_instructions.rs
Add support for missing types: `FungibleBucket` and `NonFungibleBucket`
Respective tests added
=> Fix `resim` buckets parsing

simulator/src/scrypto_bindgen/translation.rs, transaction/src/signing/ed25519/signature.rs, transaction/src/signing/secp256k1/signature.rs
Types added:
- `FungibleProof`
- `NonFungibleProof`
- `FungibleVault`
- `NonFungibleVault`
=> Add missing types `scrypto-bindgen`

radix-engine-tests/tests/stake_reconcilation.rs, radix-engine-tests/tests/stake_reconciliation.rs
Added test which creates a validator and then stakes on it some XRD. Before stake transaction all substate values (hashes) are stored in temporary hash map for value change verification after stake transaction. Also event order and names are validated.
=> Added stake reconciliation test

simulator/src/scrypto_bindgen/ast.rs, simulator/src/scrypto_bindgen/macros.rs, simulator/src/scrypto_bindgen/mod.rs, simulator/src/scrypto_bindgen/schema.rs, simulator/src/scrypto_bindgen/translation.rs
Move the updated stubs generation logic from `ledger-tools` and into this repo such that both `ledger-tools` and `scrypto-bindgen` use the same logic. This is related to radixdlt/ledger-tools#10
=> Update `scrypto-bindgen` implementation

radix-engine-interface/src/blueprints/consensus_manager/invocations.rs, radix-engine/src/blueprints/consensus_manager/validator.rs
Pure refactor/chore PR with no intended functional changes.
We no longer publicly expose `update_validator` (at that time in ConsensusManager), instead it is an internal/helper method. Here I remove the `pub(crate)` and the `CONSENSUS_MANAGER_UPDATE_VALIDATOR_IDENT`.
=> Chore: remove leftover consensus manager method

simulator/src/resim/cmd_new_account.rs, simulator/src/resim/cmd_set_default_account.rs, simulator/src/resim/config.rs, simulator/src/resim/error.rs, simulator/src/resim/mod.rs, transaction/src/signing/secp256k1/private_key.rs
Validate input to `cmd_set_default_account`, ensuring we don't accidentally pass in PublicKey instead of PrivateKey.
In `main` it is possible to accidentally pass in the PublicKey to the PrivateKey value for command `cmd_set_default_account`. This results in confusing state and error when trying to e.g. perform a transfer.
N.B: we don't get any information on what went wrong, that is because of the program panics at [unwrap at line 62](https://github.com/radixdlt/radixdlt-scrypto/blob/main/simulator/src/resim/config.rs#L62), so we never reach the next line, with more info: `Error::NoDefaultPrivateKey`. This should also be fix (I can do another PR), but this PR fixes so that should never happen...
I got into this state since I accidentally copied the PublicKey instead of the PrivateKey, …
=> Disallow PubKey as PrivKey for `cmd_set_default_account` command - display error if user accidentally pass wrong key.

README.md, examples/hello-world/README.md, simulator/src/resim/cmd_show.rs, simulator/src/resim/dumper.rs
Change so that `resim show` is possible, without specifying an address, which will try to use the default account's address.
Make `address` optional for `resim show` command, defaulting to address of default account (set with `set-default-account`).
If `resim show` is called without a default account set, a new error `NoAddressProvidedAndNotDefaultAccountSet` will be thrown.
I've added unit tests and update README.
=> Make it possible to run only 'resim show' using default account's address

.github/actions/setup-env/action.yml, .github/workflows/bench.yml, .github/workflows/ci-scrypto-builder.yml, .github/workflows/ci.yml, .github/workflows/publish-scrypto-builder.yml
```
INSTRUCTIONS:
Use github runner based on EC2 instance to save money
```
```
INSTRUCTIONS:
Run a workflow.
```
```
INSTRUCTIONS:
Run a workflow
```
=> DO-2043 / use ephemeral github runner based on EC2 instance

radix-engine-tests/tests/system/bootstrap.rs, radix-engine/src/system/system_db_reader.rs
This is a fix for a problem I encountered during development of Browse API's "get object collection entry" (see https://github.com/radixdlt/babylon-node/pull/755/files#diff-0a2c5a225e361800cb28568a6b51d0c0bbe1c5b5aded21ca10c783ef6fc0f743R174).
The `SystemDatabaseReader` was handling `ObjectCollectionKey::KeyValue` case just fine (i.e. it expected `KeyValueEntrySubstate<V>` values). However, for `ObjectCollectionKey::Index/SortedIndex` cases, it wrongfully expected the `V` values (without `IndexEntrySubstate<V>/SortedIndexEntrySubstate<V>` wrappers).
I unfortunately had to add the "unit" test in the `radix-engine-tests` (it cannot live next to `SystemDatabaseReader` since the `SubstateDatabase` impl required to run it is not available there).
_(In general, the `SystemDatabaseReader` seems …
=> Fixing the SystemDbReader's handling of Object's Index/SortedIndex entry look-up

examples/hello-world/Cargo.lock, radix-engine-stores/src/hash_tree/mod.rs, radix-engine-stores/src/hash_tree/test.rs, radix-engine-stores/src/hash_tree/tree_store.rs, radix-engine-stores/src/rocks_db_with_merkle_tree/mod.rs, radix-engine-stores/src/rocks_db_with_merkle_tree/state_tree.rs
Remove mut requirement on hash tree methods. Replaced with interior mutability implementation.
=> Architecture: Remove Hash Tree mut Requirement

radix-engine-derive/src/scrypto_describe.rs, sbor-derive-common/src/describe.rs, sbor-derive-common/src/utils.rs, sbor-tests/tests/schema.rs, sbor-tests/tests/transparent.rs
Adds functionality for type name override via `#[sbor(type_name = "NewTypeName")]`.
This is an addition, not a breaking change.
This would allow e.g. us to rename types without affecting their scrypto schema. For example, we could create e.g. `TimePrecisionV2` and rename `TimePrecision` to `TimePrecisionV1`, whilst allowing them both to have an SBOR type name of `TimePrecision`. The latter is required for backwards compatibility.
Tests are in `sbor-tests`.
=> feature: Add type_name override to Describe proc macro

radix-engine-profiling/resources-tracker-macro/scripts/run_tests.sh, radix-engine-tests/tests/system/crypto_utils.rs, radix-engine/src/errors.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_modules/costing/costing_entry.rs, radix-engine/src/system/system_modules/costing/fee_table.rs
Costing is based on instruction count measured by [QEMU costing job](https://github.com/radixdlt/radixdlt-scrypto/actions/runs/7410771396)
For methods that rely on one input [this regression calculator](https://www.socscistatistics.com/tests/regression/default.aspx) was used
Methods:
- `bls12381_v1_verify_cost()` - costing depends on message size
- `bls12381_g2_signature_aggregate_cost()` - depends on signatures count
- `keccak256_hash_cost()` - depends on message size
For methods that rely on two input [this multiple regression calculator](https://www.socscistatistics.com/tests/multipleregression/default.aspx) was used
Methods:
- `bls12381_v1_aggregate_verify_cost()` - costing depends on messages sizes (used average message size for simplicity) and keys count
- …
=> Add costing to `CryptoUtils` API

radix-engine-common/Cargo.toml, radix-engine-common/src/crypto/bls12381/private_key.rs, radix-engine-common/src/crypto/bls12381/public_key.rs, radix-engine-common/src/crypto/bls12381/signature.rs, radix-engine-common/src/crypto/signature_validator.rs, radix-engine-interface/src/api/system_modules/crypto_utils_api.rs, radix-engine-profiling/resources-tracker-macro/scripts/run_tests.sh, radix-engine-tests/assets/blueprints/crypto_scrypto/src/lib.rs, radix-engine-tests/tests/system/crypto_utils.rs, radix-engine/src/errors.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_modules/costing/costing_entry.rs, radix-engine/src/system/system_modules/costing/fee_table.rs, radix-engine/src/vm/wasm/constants.rs, radix-engine/src/vm/wasm/errors.rs, radix-engine/src/vm/wasm/prepare.rs, radix-engine/src/vm/wasm/traits.rs, radix-engine/src/vm/wasm/wasmer.rs, radix-engine/src/vm/wasm/wasmi.rs, radix-engine/src/vm/wasm_runtime/no_op_runtime.rs, radix-engine/src/vm/wasm_runtime/scrypto_runtime.rs, scrypto-test/src/environment/client_api.rs, scrypto/src/crypto_utils/crypto_utils.rs, scrypto/src/engine/wasm_api.rs
This PR adds following API methods to `CryptoUtils`:
- `bls12381_g2_signature_aggregate()`
Aggregate given BLS12-381 G2 signatures into single one
- `bls12381_v1_aggregate_verify()`
Perform BLS12-381 G2 aggregated signature verification of multiple messages, where each is signed with different key
- `bls12381_v1_fast_aggregate_verify()`
Performs BLS12-381 G2 aggregated signature verification of single message signed with different keys
Proposed API was inspired by:
-  [Ethereum Beacon chain](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#bls-signatures)
-  `blst` crate [API](https://docs.rs/blst/0.3.11/blst/min_pk/struct.Signature.html)
TODO: Costing
- some tests added to `bls12381` (in `radix-engine-common`) module implementation
- Test `CryptoUtils` …
=> Add BLS aggregation features to `CryptoUtils` module

radix-engine/src/utils/flash_state_generator.rs, scrypto-unit/src/test_runner.rs
Add state updates for the validator fee fix
=> Add generate_validator_fee_fix_state_updates

radix-engine-interface/src/blueprints/consensus_manager/invocations.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/package.rs, scrypto/src/component/stubs.rs, simulator/src/resim/cmd_publish.rs, simulator/src/resim/cmd_reset.rs, simulator/src/resim/cmd_show.rs, simulator/src/resim/cmd_show_ledger.rs, simulator/src/resim/config.rs, simulator/src/resim/mod.rs, simulator/src/scrypto_bindgen/mod.rs
This PR includes some minor clean ups and performs the protocol update state changes in the simulator environment.
=> Protocol updates in simulator

radix-engine-common/src/crypto/hash.rs, radix-engine-store-interface/src/interface.rs, radix-engine-stores/Cargo.toml, radix-engine-stores/src/rocks_db.rs, radix-engine-stores/src/rocks_db_with_merkle_tree/mod.rs
- Fixed a bug in partition deletion for `RocksdbSubstateStore` and `RocksDBWithMerkleTreeSubstateStore`
- Fixed a bug in `list_partition_keys` for `RocksDBWithMerkleTreeSubstateStore`
_(The two stores are used by `resim` and `ledger-tools` only)_
New tests added.
=> Fix issues in substate stores

radix-engine-common/Cargo.toml, radix-engine-common/src/crypto/bls12381/private_key.rs, radix-engine-common/src/crypto/signature_validator.rs, radix-engine-interface/src/api/system_modules/crypto_utils_api.rs, radix-engine-tests/assets/blueprints/crypto_scrypto/src/lib.rs, radix-engine-tests/tests/system/crypto_utils.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_modules/costing/costing_entry.rs, radix-engine/src/system/system_modules/costing/fee_table.rs, radix-engine/src/vm/wasm/constants.rs, radix-engine/src/vm/wasm/prepare.rs, radix-engine/src/vm/wasm/traits.rs, radix-engine/src/vm/wasm/wasmer.rs, radix-engine/src/vm/wasm/wasmi.rs, radix-engine/src/vm/wasm_runtime/no_op_runtime.rs, radix-engine/src/vm/wasm_runtime/scrypto_runtime.rs, scrypto-test/src/environment/client_api.rs, scrypto/src/crypto_utils/crypto_utils.rs, scrypto/src/engine/wasm_api.rs
Enable BLS aggregate verify for Radix Engine and Scrypto.
For `wasm32` and `no_std` added our local implementation of `aggregate_verify_bls12381_v1_no_threads()` which does not rely on threads.
It follows [CoreAggregateVerify](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-05#name-coreaggregateverify) description.
And is inspired with [`aggregate_verify()` implementation](https://github.com/supranational/blst/blob/master/bindings/rust/src/lib.rs#L1095) from `blst` crate.
Added a few positive and negative tests.
=> Enable BLS aggregate verify

README.md, radix-engine-interface/src/api/node_modules/metadata/models/mod.rs, radix-engine-tests/tests/system/metadata.rs
Merge `main` into `release/anemone`
=> Merge main into release/anemone

radix-engine-interface/src/blueprints/access_controller/invocations.rs, radix-engine-interface/src/blueprints/consensus_manager/invocations.rs
A small PR that adds a number of `ManifestSbor` invocations that the toolkit needs.
=> Add some manifest sbor invocations

simulator/src/resim/dumper.rs
When displaying component details resim shows resource addresses followed by metadata symbols. This PR exchanges the symbols for names
Original
Updated
=> make resim display resource names rather than symbols

monkey-tests/src/lib.rs, radix-engine-interface/src/blueprints/resource/fungible/fungible_resource_manager.rs, radix-engine-interface/src/blueprints/resource/non_fungible/non_fungible_resource_manager.rs, radix-engine-tests/tests/application/common_transactions.rs, radix-engine-tests/tests/blueprints/pool_one_resource.rs, radix-engine-tests/tests/system/auth_scenarios.rs, radix-engine-tests/tests/system/events.rs, radix-engine-tests/tests/system/metadata.rs, radix-engine/src/blueprints/access_controller/blueprint.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/validator.rs, radix-engine/src/system/attached_modules/role_assignment/substates.rs, radix-engine/src/system/bootstrap.rs, simulator/src/resim/cmd_show.rs, simulator/src/scrypto_bindgen/mod.rs, transaction-scenarios/src/scenarios/metadata.rs, transaction-scenarios/src/scenarios/radiswap.rs
=> Fix Rust compiler warnings

radix-engine-tests/src/pool_stubs.rs, radix-engine-tests/tests/kernel/test_environment.rs, radix-engine/src/system/system_modules/module_mixer.rs, radix-engine/src/vm/vm.rs, scrypto-test/src/environment/builder.rs, scrypto-test/src/environment/client_api.rs, scrypto-test/src/environment/env.rs, scrypto-test/src/environment/internal.rs, scrypto-test/src/environment/mod.rs, scrypto-test/src/environment/types.rs, scrypto-test/src/sdk/package.rs, scrypto-test/src/sdk/resource/bucket_factory.rs, scrypto-test/src/sdk/resource/proof_factory.rs
This PR includes a number of changes and improvements to the scrypto-test framework. The following are the changes made:
* Created a new `TestEnvironmentBuilder` that allows for configuring the environment prior to creation. Additionally the `TestEnvironment` can now operate over any database and not just an in-memory database.
* Added a better way for reading state in the testing environment. This new method ensures that the states are opened and closed when they need to be. It also ensures that the references provided as a result of the state reads do not escape outside of the closure.
* Added logging support to the testing environment. It is currently enabled by default and quite rudimentary.
=> Feature: Scrypto Test Builder

transaction/src/builder/manifest_builder.rs, transaction/src/builder/manifest_namer.rs
Small bug fix to enable the test case which I've added. Thanks to Michal for the report.
=> fix: Fix manifest builder complex deposit batch bug

.github/workflows/ci-scrypto-builder.yml, Dockerfile, examples/everything/Cargo.toml_for_scrypto_builder
This PR makes sure that `scrypto-builder` docker image includes the development tools such as `cmake`, `clang`, `llvm`. 
It addresses [the issue reported](https://discord.com/channels/417762285172555786/1202267398921797702/1202286081165492224) by one of the Scrypto developers
<details>
<summary> error occurred: Command "clang" </summary>
```bash
Updating git repository `https://github.com/radixdlt/radixdlt-scrypto`
Updating crates.io index
Updating git repository `https://github.com/radixdlt/const-sha1`
Updating git repository `https://github.com/dtolnay/syn.git`
Updating git repository `https://github.com/radixdlt/wasm-instrument`
Updating git repository `https://github.com/radixdlt/wasmi.git`
Updating git submodule `https://github.com/robbepop/wasm_kernel.git`
Updating git submodule …
```
=> Fix - bake build tools into the `scrypto-builder` docker image

assets/blueprints/faucet/src/lib.rs
Changed Faucet blueprint `free` method magic number specifying count of XRD returned to a constant. We need to use that constant in `radix-engine-toolkit` project in `trusted-worktop` feature. Also updated test which uses this magic number in assertions.
=> Faucet blueprint changed magic number to constant 

substate-store-impls/src/hash_tree/mod.rs, substate-store-impls/src/hash_tree/test.rs
Needed by Node, for https://radixdlt.atlassian.net/browse/LZ-18.
This PR only cares about that one struct being `pub`.
As a drive-by, I remove a few unneeded `&mut`s.
=> Making the JMT's `NestedTreeStore` public (for Node's purposes)

substate-store-impls/src/hash_tree/mod.rs, substate-store-impls/src/hash_tree/test.rs, substate-store-impls/src/hash_tree/tree_store.rs, substate-store-impls/src/rocks_db_with_merkle_tree/state_tree.rs
This PR accomplishes what https://github.com/radixdlt/radixdlt-scrypto/pull/1726 tried, but using another approach
Addresses https://radixdlt.atlassian.net/browse/LZ-20.
It uses the new approach described as **Variant D)** at https://radixdlt.atlassian.net/wiki/spaces/RPNV1/pages/3313532929/RNP-15+-+Historical+State#Rolling-the-history.
Summarizing: JMT now "notifies" the `TreeStore` about `&DbSubstateValue`s associated with JMT-native `NodeKey`s. The Node's implementation of `TreeStore` will store this in a separate table.
Unit test included; Integration tests to be added on Node's side.
No update needed, except for Node developers wanting to use this new capability.
=> LZ-20: Implement JMT associating Substate-Tier leaves with Substate values

scrypto-test/src/ledger_simulator/ledger_simulator.rs
New convenient method of LedgerSimulator (TestRunner) for getting resource total supply during tests.
Tested. Code stolen from here.
https://github.com/radixdlt/radixdlt-scrypto/blob/develop/radix-engine-tests/tests/system/bootstrap.rs#L272
=> get_resource_total_supply method for testrunner

substate-store-impls/src/hash_tree/substate_tier.rs, substate-store-impls/src/hash_tree/test.rs, substate-store-impls/src/hash_tree/tree_store.rs, substate-store-impls/src/rocks_db_with_merkle_tree/state_tree.rs, substate-store-interface/src/interface.rs
This is a minor follow-up to https://github.com/radixdlt/radixdlt-scrypto/pull/1728 (i.e. a tweak to impl of https://radixdlt.atlassian.net/browse/LZ-20).
It turns out that Node may optimize its historical state feature impl when it knows the associated Substates key (apart from value).
We are not sure we will use the Substate key right away, but it is very cheap to just pass it there and thus we prefer to have it available.
Apart from the feature, I squeezed in a slight simplification of the "associate substates" logic (i.e. avoiding some rewrites by reading directly from `&PartitionDatabaseUpdates`).
Adjusted the unit test.
Only Node is supposed to integrate and this will be a trivial API adjustment.
=> Add Substate key to accompany the Substate value associated with a JMT leaf

radix-engine-tests/tests/application/preview.rs, radix-engine-tests/tests/application/transaction.rs, radix-engine-tests/tests/system/events.rs, radix-engine/src/system/system_modules/module_mixer.rs, radix-engine/src/transaction/preview_executor.rs, radix-engine/src/transaction/transaction_executor.rs, transaction/src/model/v1/preview_transaction.rs, transaction/src/validation/transaction_validator.rs
This adds a new `disable_auth` flag to PreviewFlags that allows to completely disable the auth module.
=> Add disable_auth preview flag

substate-store-impls/src/hash_tree/substate_tier.rs, substate-store-impls/src/hash_tree/test.rs, substate-store-impls/src/hash_tree/tree_store.rs, substate-store-impls/src/rocks_db_with_merkle_tree/state_tree.rs, substate-store-interface/src/interface.rs
This fixes a bug found in the impl of https://github.com/radixdlt/radixdlt-scrypto/pull/1728:
It turns out that Node needs to be notified about JMT leaves created during tree restructuring. Previous implementation was deliberately skipping them.
Added a unit test for precisely this behavior (which fails before the fix: see the first commit).
Added another unit test to cover partition resets (which luckily always worked fine, but is just a related area with some bug potential).
Only internal Node devs need to adjust to some small API change.
=> Bugfix: Associate JMT leaves created due to "tree restructuring" with their unchanged Substates

Dockerfile, radix-engine-tests/tests/vm/stack_size.rs
Fix issues caused by rust stable update from `1.76.0` to `1.77.0`
- Relax the `RuntimeError` size requirement in order to let the `test_error_enum_sizes` test pass and unblock failing CI.
It started to fail after rust update to `1.77.0` (see [changelog](https://releases.rs/docs/1.77.0/)), which includes the change:
- [Make i128 and u128 16-byte aligned on x86-based targets.](https://github.com/rust-lang/rust/pull/116672/)
- Use rust `1.76.0` by default in docker images
With rust `1.77.0` WASM size is increased slightly causing job [build-scrypto](https://github.com/radixdlt/radixdlt-scrypto/actions/runs/8387171238/job/22969302472) `Check WASM size` step to fail
=> Fixes after switching to rust `1.77.0`

README.md
```
INSTRUCTIONS:
Fix: change scrypto documentation link in README
```
```
INSTRUCTIONS:
Change https://docs-babylon.radixdlt.com/main/scrypto/introduction.html to https://docs.radixdlt.com/docs/scrypto-1
```
=> Fix: change scrypto documentation link

radix-engine-tests/tests/application/common_transformation_costs.rs, radix-engine-tests/tests/blueprints/transaction_tracker.rs, radix-transactions/src/model/executable.rs, radix-transactions/src/model/v1/validated_notarized_transaction.rs
The Node needs to be able to customize the `abort_when_loan_repaid: true` for running a transaction pending in the mempool.
This PR standardizes the way to do this (and similar, already-existing) customizations.
A refactoring-only: just the regression tests need to pass.
Only the Node developers need to integrate.
=> Refactoring: Exposing customization methods for `Executable`

radix-engine-interface/src/types/node_layout.rs, radix-substate-store-queries/src/typed_substate_layout.rs
A trivial line with mapping needed by Node.
Probably missed at https://github.com/radixdlt/radixdlt-scrypto/pull/1763.
Node's int-tests fail without it, and hopefully will pass with it.
=> Quickfix: Add missed `SystemBoot` typed field + mapping

radix-substate-store-queries/src/typed_substate_layout.rs
A quickfix to the other recent quickfix (https://github.com/radixdlt/radixdlt-scrypto/pull/1773).
A copy-paste error.
This is tested on Node's side (which is how it was detected).
=> Quickfix: Mapping for `SystemBoot` typed value

Cargo.toml, examples/everything/Cargo.lock, radix-clis/Cargo.lock, radix-common/Cargo.toml, radix-common/src/crypto/ed25519/private_key.rs, radix-common/src/crypto/secp256k1/private_key.rs
Added derive of `Zeroize` and `ZeroizeOnDrop` to `Ed25519PrivateKey`. This is required by Sargon project (will be used thorught RET).
=> Add `Zeroize` to private key

radix-engine-tests/src/common.rs, scrypto-test/src/ledger_simulator/compile.rs
Added missing `compile_with_env_vars()` function required for `compile-blueprints-at-build-time` feature in `radix-engine-tests` project.
Also there was an issue when using `compile-blueprints-at-build-time` feature with packages specified to `PackageLoader` in form of path, ex.: `oracle_proxies/oracle_proxy_with_global`. This was fixed in `PackageLoader` by extracting last section from the path.
=> Added missing `compile_with_env_vars()` function

.github/actions/setup-env/action.yml, .github/workflows/bench.yml, .github/workflows/ci.yml, .github/workflows/publish-scrypto-builder.yml, README.md, radix-engine-common/src/lib.rs, radix-engine-interface/src/lib.rs, radix-engine-tests/tests/vm/stack_size.rs, sbor/src/lib.rs, scrypto/src/lib.rs
This PR improves Rust analyzer's performance on the main branch by getting rid of a cyclic path that we had in our crates where things like `scrypto::scrypto::scrypto::scrypto::scrypto::prelude::*` were valid paths.
=> Improve Rust Analyzer's performance on the main branch

radix-common/src/math/decimal.rs, radix-common/src/math/precise_decimal.rs
Added type alias to `Decimal` and `PreciseDecimal` which is needed by Radix Engine Toolkit to have access to `I192` and `I256` types methods in a generic way (from macro).
This is required for Maya integration to convert between `Decimal` and array of bytes.
=> Added `DecimalInternal` type

radix-common/src/constants/mod.rs, radix-common/src/constants/native_blueprints.rs, radix-engine/assets/blueprints/faucet/src/lib.rs
Changed Faucet blueprint `free` method magic number specifying count of XRD returned to a constant. We need to use that constant in `radix-engine-toolkit` project in `trusted-worktop` feature. Also updated test which uses this magic number in assertions.
This PR re-applies PR: https://github.com/radixdlt/radixdlt-scrypto/pull/1706 which now is missing from `develop`.
=> Faucet blueprint changed magic number to constant

.github/actions/setup-env/action.yml
Pins the rust version to 1.77.2 due to an issue with 1.78.0 and wasmer
=> Pin rust version

radix-engine-tests/src/common.rs, radix-engine-tests/tests/system/metadata.rs
CI is failing when the metadata tests try to compile scenario assets. Example: https://github.com/radixdlt/radixdlt-scrypto/actions/runs/8932039773/job/24535207622?pr=1794
This PR resolves the CI issue by loading the compiled artifacts. 
We may consider bumping the dependency of the source blueprints in future.
=> Update metadata tests to use compiled assets

radix-common/src/time/instant.rs, radix-common/src/time/utc_date_time.rs
Add `PartialOrd`/`Ord`/`Hash` derives for `Instant` and `UtcDateTime`.
Resolves https://github.com/radixdlt/radixdlt-scrypto/issues/1757
=> Add derives for Instant and UtcDateTime

radix-engine-tests/tests/flash/crypto_utils.rs, radix-engine-tests/tests/flash/pools.rs, radix-engine-tests/tests/flash/seconds_precision.rs, radix-engine/src/updates/anemone.rs, radix-engine/src/updates/bottlenose.rs, radix-engine/src/updates/mod.rs, radix-engine/src/updates/protocol_builder.rs
This is needed for better integration with "post-protocol-update Scenarios" on the Node's side.
Node wants to execute transaction batches for configured Scenarios after transaction batches of a specific Protocol Update.
The progress across these batches has to survive Node's restarts.
To achieve it, the Node re-uses the same `batch_index` (in the underlying persistence), and thus it needs a way of distinguishing which indices belong to Protocol Update itself, and which represent the post-PU scenarios.
The easiest way is to declare how many batches each PU contains, and it also seems to have no downsides (i.e. doesn't reduce flexibility, since the batch generator was always closer to a random-access than to an iterator, despite its API shape).
Adjusted some test set-up code.
The behavior …
=> Refactor: add `ProtocolUpdateBatchGenerator.batch_count()`

radix-engine-tests/tests/blueprints/account_locker.rs, radix-engine/src/blueprints/locker/blueprint.rs
If any of the limits were exceeded in a manifest that called `airdrop` or `store` on the account locker a `KernelError(SubstateHandleDoesNotExist(3997))` error would be returned. The root cause of this was the use of callback functions in the account locker code which executed a callback, did some additional operations, and then returned the callback result. However, in cases when the callback itself has failed (perhaps due to an event limit or for other reasons) the operations did after the callback execution would also fail. Instead of the function returning the original error it would return the error from the subsequent operations. 
This PR changes how the account locker uses callbacks such that if the callback fails then its error is bubbled up.
=> Improve account locker Errors

examples/hello-world/tests/lib.rs, radix-clis/assets/template/tests/lib.rs, radix-clis/src/scrypto/cmd_coverage.rs, radix-clis/src/utils/cargo.rs, radix-engine-tests/src/common.rs, radix-engine-tests/tests/flash/crypto_utils.rs, radix-engine-tests/tests/vm/system_wasm_buffers.rs, scrypto-compiler/src/lib.rs, scrypto-test/Cargo.toml, scrypto-test/src/ledger_simulator/compile.rs, scrypto-test/src/ledger_simulator/ledger_simulator.rs, scrypto-test/src/sdk/package.rs, scrypto-test/tests/tuple_return.rs
Added `CompilerProfile` to `LedgerSimulator`.
Adding new `scrypto-compiler` crate introduced divergence between default `scrypto build` command compilation options and compilation options used by `LedgerSimulator` and `SDK` in `scrypto-test` project. This PR provides option for the users of `LedgerSimulator` to choose if they want to use standard `scrypto build` compilation options or faster compilation options (WASM optimizations are disabled in that case).
Also refactored `PackageFactory` to use same compiler object as `LedgerSimulator`.
Added new tests which verifies if blueprint compiled using `scrypto build` and `LedgerSimulator` with Standard compilation options are binary same. Also added other validation tests.
=> Scrypto compiler default options for tests

scrypto-test/src/environment/env.rs
Updated function `set_current_time()` to use `ProposerMilliTimestamp` calculated from provided seconds.
Updated function `get_current_time()` to use `TimePrecision::Second`.
=> Added support for seconds precision in `TestEnvironment`

radix-clis/src/scrypto/cmd_coverage.rs
When `--path` argument was specified to `scrypto coverage` command the `COVERAGE_DIRECTORY` passed to test was misaligned with current directory set during tests execution. It is enough to just change `COVERAGE_DIRECTORY` path to absolute path instead of relative.
=> Fixed scrypto coverage command with path argument

.github/workflows/ci.yml
Added execution of CLI test: `scrypto_coverage.sh` to CI workflow.
Successful new job run: https://github.com/radixdlt/radixdlt-scrypto/actions/runs/9127710496/job/25098580548?pr=1817
This PR requires changes done in [fix/scrypt-coverage-with-path](https://github.com/radixdlt/radixdlt-scrypto/tree/fix/scrypt-coverage-with-path) branch - PR https://github.com/radixdlt/radixdlt-scrypto/pull/1816.
=> Added scrypto coverage test to CI script

.github/workflows/ci.yml, Cargo.toml, check_stack_usage.sh, examples/everything/Cargo.lock, examples/hello-world/Cargo.lock, radix-clis/Cargo.lock, radix-engine-tests/build.rs, radix-engine/assets/blueprints/Cargo.lock, scrypto-compiler/Cargo.toml, scrypto-compiler/src/lib.rs, test.sh
This change introduces a protection of Scrypto build artifacts with lock file.
This is important when multiple Scrypto compilation processes are invoked in parallel.
Compilation time for multiple compilations increases slightly.
Additionally:
- produce WASM with schema file *_with_schema.wasm
- implemented scrypto compiler cache to skip second compilation if possible
- run RE tests with O1 optimization level. It increases the build time slightly but reduces the test time
- reduced stack usage test duration - it is executed in the same job as `Run Radix Engine tests` but apparently it was rebuilding RE massively instead of reusing build artifacts from the `cargo nextest run`. Discovered that we need to provide exactly the same list of packages in order to benefit from incremental build. …
=> Protect scrypto compilation with lock file

radix-clis/src/scrypto_bindgen/mod.rs, radix-common/src/data/manifest/custom_extension.rs, radix-common/src/data/scrypto/custom_extension.rs, radix-common/src/data/scrypto/custom_schema.rs, radix-common/src/data/scrypto/custom_well_known_types.rs, radix-engine-tests/tests/system/schema_sanity_check.rs, sbor-tests/tests/schema_comparison.rs, sbor/src/basic.rs, sbor/src/payload_validation/payload_validator.rs, sbor/src/schema/custom_traits.rs, sbor/src/schema/schema.rs, sbor/src/schema/schema_comparison.rs, sbor/src/schema/schema_validation/mod.rs, sbor/src/schema/schema_validation/type_kind_validation.rs, sbor/src/schema/schema_validation/type_metadata_validation.rs, sbor/src/schema/schema_validation/type_validation_validation.rs, sbor/src/schema/type_aggregator.rs, sbor/src/schema/type_data/mod.rs, sbor/src/schema/type_data/type_kind.rs, sbor/src/schema/type_link.rs, sbor/src/traversal/typed/typed_traverser.rs, sbor/src/vec_traits.rs, scrypto-bindgen/src/schema.rs
Minor refactor to improve the type hell when dealing with schemas.
Builds on top of #1836 (will need merging after)
Notably it:
* Swaps `CustomSchema::CustomTypeKind<L>` for explicit `CustomSchema::CustomLocalTypeKind` and `CustomSchema::AggregatorLocalTypeKind` which simplifies a lot
* Introduces some aliases to make using these types much less boilerplatey
```rust
pub type LocalTypeKind<S> = TypeKind<<S as CustomSchema>::CustomLocalTypeKind, LocalTypeId>;
pub type AggregatorTypeKind<S> =
TypeKind<<S as CustomSchema>::CustomAggregatorTypeKind, RustTypeId>;
pub type LocalTypeData<S> = TypeData<<S as CustomSchema>::CustomLocalTypeKind, LocalTypeId>;
pub type AggregatorTypeData<S> =
TypeData<<S as CustomSchema>::CustomAggregatorTypeKind, RustTypeId>;
```
Adds a …
=> refactor: Remove some type hell with SchemaTypeLinks

Cargo.toml
Fix CI coverage tests - pin `minicov` to `0.3.3`
=> Fix CI - pin `minicov`

radix-engine-tests/assets/blueprints/non_fungible/src/big_vault.rs, radix-engine-tests/assets/blueprints/non_fungible/src/non_fungible_test.rs, radix-engine-tests/assets/blueprints/proof/src/vault_proof.rs, radix-engine-tests/assets/blueprints/resource/src/lib.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/proof.rs, scrypto/src/resource/vault.rs
Implement `as_fungible()` and `as_non_fungible()` methods only Generic types.
In https://github.com/radixdlt/radixdlt-scrypto/pull/1782 these methods were implemented for all three types:
- generic
- fungible
- non-fungible
It allowed to create such combinations as below:
```
let vault = FungibleVault::with_bucket(some_bucket).as_non_fungible();  
```
It is not possible to get `NonFungibleVault` from `FungibleVault`.
Tests were updated accordingly.
=> Implement `as_fungible()` and `as_non_fungible()` methods only Generic types.

.github/workflows/ci.yml, Cargo.toml
- Setup Rust 1.81.0-nightly and LLVM 18 in CI
- Bump `minicov` to 0.3.5
TODO: update documentations before release
=> Update rust and llvm for coverage

scrypto-test/src/sdk/resource/bucket_factory.rs
`validate_resource_specifier()` function returns wrong result for proper input data: non fungible resource with at least two ids.
Added two test to verify `validate_resource_specifier()` function, on current develop 1st test: `verify_validate_resource_specifier_method()` is failing, but should succeed.
=> Fixed `validate_resource_specifier()` function

radix-engine-monkey-tests/tests/fuzz_kernel.rs, radix-engine-tests/tests/kernel/kernel.rs, radix-engine-tests/tests/kernel/kernel_open_substate.rs, radix-engine-tests/tests/vm/native_vm.rs, radix-engine/src/kernel/kernel.rs, radix-engine/src/kernel/kernel_callback_api.rs, radix-engine/src/system/module.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_callback.rs, radix-engine/src/system/system_modules/costing/costing_module.rs, radix-engine/src/system/system_modules/limits/module.rs, radix-engine/src/system/system_modules/module_mixer.rs, scrypto-test/src/environment/builder.rs, scrypto-test/src/ledger_simulator/inject_costing_err.rs
This reverts commit 50ab8d22357283593e1fd77aad6a717b4f7c22a5.
=> Revert "pass the current depth as an argument to modules"

.github/workflows/ci.yml
Assure LLVM 18 tools are installed for for CI scrypto coverage test.
=> Fix scrypto coverage CI test

scrypto-test/src/environment/env.rs
`TestEnvironment` from `scrypto-test` module have incomplete implementation of `set_current_time()` function which lacks setting of Minute timestamp field.
Implemented fix adds writing Minutes filed in `set_current_time()` function.
There is an example code provided by Community member which reproduces the issue: https://github.com/yr12345678/bored_clock_club/
Added new unit test `test_time_set()` which sets current time and verifies if values returned for both precisions: Seconds and Minutes are equals. On current develop branch time returned for Minute precision is 0 instead of 60.
=> Fixed `scrypt-test` `set_current_time()` function

.github/workflows/ci.yml
Use exactly the same version as recommended in the scrypto docs.
=> Update 1.81.0-nightly version for coverage test

radix-engine-interface/src/blueprints/resource/bucket.rs, radix-engine-interface/src/blueprints/resource/proof.rs, radix-engine-tests/src/pool_stubs.rs, radix-engine-tests/tests/blueprints/pool_arithmetic.rs, radix-engine/src/blueprints/account/blueprint.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/validator.rs, radix-engine/src/blueprints/identity/package.rs, radix-engine/src/blueprints/locker/blueprint.rs, radix-engine/src/blueprints/pool/v1/v1_0/multi_resource_pool_blueprint.rs, radix-engine/src/blueprints/pool/v1/v1_0/one_resource_pool_blueprint.rs, radix-engine/src/blueprints/pool/v1/v1_0/two_resource_pool_blueprint.rs, radix-engine/src/blueprints/pool/v1/v1_1/multi_resource_pool_blueprint.rs, radix-engine/src/blueprints/pool/v1/v1_1/one_resource_pool_blueprint.rs, radix-engine/src/blueprints/pool/v1/v1_1/two_resource_pool_blueprint.rs, radix-engine/src/blueprints/resource/fungible/fungible_bucket.rs, radix-engine/src/blueprints/transaction_processor/tx_processor.rs, radix-engine/src/blueprints/util/securify.rs, radix-native-sdk/src/resource/bucket.rs, radix-native-sdk/src/resource/proof.rs, radix-native-sdk/src/resource/resource_manager.rs, scrypto-test/src/sdk/resource/bucket_factory.rs, scrypto-test/src/sdk/resource/proof_factory.rs, scrypto-test/src/sdk/resource/resource_builder.rs
After reports from a user on Telegram struggling with the `TestEnvironment`, and observing some issues using `FungibleBucket` / `NonFungibleBucket` in Radquest, this fixes:
* `FungibleBucket` and `NonFungibleBucket` to have features like `.resource_manager()` and not need manually converting into a `Bucket`. 
* `native-sdk`'s `ResourceManager` and `scrypto-test`'s `ResourceBuilder` to return `FungibleBucket` / `NonFungibleBucket` from relevant methods
Builds on top of `system-api-interface-refactor` #1857 (and actually motivated it).
Note this PR doesn't fully split fungible/non-fungible-specific functionality out of `NativeBucket` and `NativeProof` as those would be breaking changes - but maybe we should; as I have introduced breaking changes to `ResourceBuilder` and `ResourceManager` to …
=> fix: Better align `NativeProof` / `NativeBucket` functionality with Scrypto

radix-engine-tests/assets/blueprints/transaction_limits/src/transaction_limits.rs, radix-engine-tests/benches/costing.rs, radix-engine-tests/tests/system/transaction_limits.rs
Various benches to gauge effectiveness of #1860
=> benches: Explicit benches relevant to #1860

radix-engine-monkey-tests/tests/fuzz_kernel.rs, radix-engine-tests/tests/kernel/kernel.rs, radix-engine-tests/tests/kernel/panics.rs, radix-engine-tests/tests/vm/native_vm.rs, radix-engine/src/blueprints/package/package.rs, radix-engine/src/kernel/kernel.rs, radix-engine/src/kernel/kernel_api.rs, radix-engine/src/kernel/kernel_callback_api.rs, radix-engine/src/object_modules/role_assignment/package.rs, radix-engine/src/object_modules/royalty/package.rs, radix-engine/src/system/module.rs, radix-engine/src/system/payload_validation.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_callback.rs, radix-engine/src/system/system_callback_api.rs, radix-engine/src/system/system_modules/auth/auth_module.rs, radix-engine/src/system/system_modules/costing/costing_module.rs, radix-engine/src/system/system_modules/execution_trace/module.rs, radix-engine/src/system/system_modules/kernel_trace/module.rs, radix-engine/src/system/system_modules/limits/module.rs, radix-engine/src/system/system_modules/module_mixer.rs, radix-engine/src/system/system_modules/transaction_runtime/module.rs, radix-engine/src/system/system_type_checker.rs, radix-engine/src/vm/vm.rs, scrypto-test/src/environment/builder.rs, scrypto-test/src/environment/env.rs, scrypto-test/src/environment/system_api.rs, scrypto-test/src/environment/types.rs, scrypto-test/src/ledger_simulator/inject_costing_err.rs
Refactors the Engine traits for much better encapsulation, notably:
* Using associated types to capture things like the callbacks and the errors
* Introduced `SystemBasedKernelApi` trait to capture "a Kernel API which knows its callback is System", and can therefore access both Kernel API and System APIs.
* Creating a new `SystemModuleApi` trait, to abstract away the kernel from system modules
* Made the `KernelCallbackObject` trait more consistent:
* By having each property take an API (either a KernelInternalApi, or in some cases, a KernelApi).
* By moving all the api parameters to the end
I toyed with getting rid of a `SystemService` struct, and replacing it with a `SystemServiceApi` trait... but when you try to do `impl<Y: SystemBasedKernelApi> SystemFieldApi<RuntimeError> for Y` you …
=> Refactor engine internal traits for better encapsulation

radix-engine-tests/benches/costing.rs, radix-engine-tests/benches/radiswap.rs, radix-engine-tests/tests/application/common_transactions.rs, radix-engine-tests/tests/application/metering.rs, radix-engine-tests/tests/application/preview.rs, radix-engine-tests/tests/application/stake_reconciliation.rs, radix-engine-tests/tests/application/storage.rs, radix-engine-tests/tests/blueprints/access_controller.rs, radix-engine-tests/tests/blueprints/account_deposit_modes.rs, radix-engine-tests/tests/blueprints/account_locker.rs, radix-engine-tests/tests/blueprints/non_fungible.rs, radix-engine-tests/tests/blueprints/pool_multi_resource.rs, radix-engine-tests/tests/blueprints/pool_one_resource.rs, radix-engine-tests/tests/blueprints/pool_two_resource.rs, radix-engine-tests/tests/db/substate_database_overlay.rs, radix-engine-tests/tests/flash/access_controller.rs, radix-engine-tests/tests/flash/account.rs, radix-engine-tests/tests/flash/pools.rs, radix-engine-tests/tests/flash/role_assignment.rs, radix-engine-tests/tests/system/auth_account.rs, radix-engine-tests/tests/system/consensus_manager.rs, radix-engine-tests/tests/system/core.rs, radix-engine-tests/tests/system/events.rs, radix-engine-tests/tests/system/role_assignment.rs, radix-engine-tests/tests/system/royalty_edge_cases.rs, radix-engine-tests/tests/system/toolkit_receipt.rs, radix-engine-tests/tests/vm/logging_limits.rs, scrypto-test/src/ledger_simulator/ledger_simulator.rs
After discussions with Yulong, this PR disables kernel trace by default in the `LedgerSimulator`.
Kernel trace causes tests to run a little slower, and causes lots of pretty indecipherable logs to appear in test output.
It can be re-enabled when needed using `.with_kernel_trace()` (basically by us for engine determinism debugging).
NOTE: Ensure this PR's base is updated to `develop` before merging.
You may wish to add `.with_kernel_trace()` to your LedgerSimulator if debugging a gnarly test execution.
=> fix: LedgerSimulator disables kernel trace by default

radix-common/src/state/state_updates.rs, radix-common/src/types/node_and_substate.rs, radix-engine-tests/tests/application/stake_reconciliation.rs, radix-engine-tests/tests/kernel/kernel_open_substate.rs, radix-engine-tests/tests/kernel/panics.rs, radix-engine-tests/tests/vm/native_vm.rs, radix-engine/src/init.rs, radix-engine/src/kernel/kernel.rs, radix-engine/src/kernel/kernel_callback_api.rs, radix-engine/src/lib.rs, radix-engine/src/system/bootstrap.rs, radix-engine/src/system/system_callback.rs, radix-engine/src/system/system_callback_api.rs, radix-engine/src/track/interface.rs, radix-engine/src/track/track.rs, radix-engine/src/transaction/transaction_executor.rs, radix-engine/src/updates/bottlenose.rs, radix-engine/src/updates/cuttlefish.rs, radix-engine/src/vm/versions.rs, radix-engine/src/vm/vm.rs, radix-substate-store-interface/src/interface.rs, radix-transaction-scenarios/generated-protocol-updates/cuttlefish/receipts/00-00-00--cuttlefish-protocol-system-logic-updates.txt, radix-transactions/src/model/execution/executable_common.rs, radix-transactions/src/model/v1/system_transaction.rs, scrypto-test/src/environment/builder.rs, scrypto-test/src/ledger_simulator/inject_costing_err.rs, scrypto-test/src/ledger_simulator/ledger_simulator.rs
This PR explores the idea of moved the reading of the boot substates higher up in the boot process, just before we execute, and storing this onto the `XInit` parameter objects, along with any generics, so that the `XInit` can fully specify `X`.
This simplifies [transaction_executor.rs](https://github.com/radixdlt/radixdlt-scrypto/pull/1924/files#diff-796f5fb2614f1a182ebb4c1d13b67f246cd4265f76d2e9f04624e23fbcd3c192) and anywhere else we need to execute transactions with different set-ups.
I've:
* Created utility methods `XInit::load` for loading these `Boot` methods from the Database, and removed the `BootStore` trait.
* The `XInit` fully capture the generics of their corresponding `X` which allows it to be used to _create_ an `X`. This means we don't have to separately provide generics …
=> refactor: Streamline engine init

radix-engine/src/updates/cuttlefish.rs, radix-transaction-scenarios/generated-protocol-updates/cuttlefish/protocol_update_summary.txt, radix-transaction-scenarios/generated-protocol-updates/cuttlefish/receipts/00-00-03--cuttlefish-update-metadata.txt, update-protocol-updates.sh
Updates the `info-url` metadata in Cuttlefish to a new URL scheme.
Existing tests pass.
=> update: Tweak info-urls in cuttlefish

radix-common/src/crypto/public_key_hash.rs, radix-common/src/data/manifest/model/manifest_expression.rs, radix-common/src/math/bnum_integer.rs, radix-common/src/math/decimal.rs, radix-common/src/math/traits.rs, radix-common/src/types/entity_type.rs, radix-common/src/types/node_and_substate.rs, radix-common/src/types/non_fungible_global_id.rs, radix-engine-interface/src/blueprints/account/invocations.rs, radix-engine-interface/src/blueprints/pool/multi_resource_pool/invocations.rs, radix-engine-tests/tests/application/static_resource_movements_visitor.rs, radix-engine-tests/tests/blueprints/account_authorized_depositors.rs, radix-engine-tests/tests/flash/pools.rs, radix-transactions/src/builder/manifest_builder.rs, radix-transactions/src/builder/manifest_namer.rs, radix-transactions/src/manifest/static_manifest_interpreter.rs, radix-transactions/src/manifest/static_resource_movements/effect.rs, radix-transactions/src/manifest/static_resource_movements/error.rs, radix-transactions/src/manifest/static_resource_movements/typed_invocation.rs, radix-transactions/src/manifest/static_resource_movements/types.rs, radix-transactions/src/manifest/static_resource_movements/visitor.rs, radix-transactions/src/validation/transaction_validator.rs
Reworks some implementation of #1909  to be more powerful.
=> rework: Rework the manifest resource interpreter

radix-transactions/src/manifest/manifest_instructions.rs, radix-transactions/src/model/v1/instruction_v1.rs, radix-transactions/src/model/v2/instruction_v2.rs, sbor-derive-common/src/categorize.rs
Trivial PR to:
* Re-order instructions into a more sensible order.
* Move the discriminators into an ID associated constant of the `ManifestInstruction` trait, to keep them all together nicely.
Existing tests pass, including the instruction schema tests.
=> tweak: Trivial instruction refactors

radix-common/src/data/manifest/model/manifest_resource_assertion.rs, radix-transactions/src/manifest/static_manifest_interpreter.rs, radix-transactions/src/manifest/static_resource_movements/types.rs
Permits `GeneralResourceConstraint` to be more widely valid, notably we no longer require that the bound is "normalized", i.e. that:
* `required_ids.len() <= lower_bound`
* `upper_bound <= allowlist.len()`
But rather that the bound is "satisfiable", i.e. that there is an overlap between the numeric bounds and the id bounds: 
* `required_ids.len() <= upper_bound`
* `lower_bound <= allowlist.len()`
Also tweaks:
* `ResourceBounds` in the static analyzer to wrap a `GeneralResourceConstraint`.
* Improve rustdocs on all these types to be more accurate and more explantory.
Existing tests pass (e.g. in `static_resource_movements_visitor.rs`).
=> tweak: Widen validity of general resource constraint

radix-engine/src/blueprints/package/package.rs
The warning appears newly in new builds of rustc 1.81.0.
The warning arose because we were collecting void results into `_`, where `()` was previously inferred. But now it want to make it explicit. Or in compiler speak:
```text
in edition 2024, the requirement `!: std::iter::FromIterator<()>` will fail
> rustc(dependency_on_unit_never_type_fallback)
```
It was originally written using a `map => collect::<Result<_, _>>() => map_err` pattern in https://github.com/radixdlt/radixdlt-scrypto/commit/c04412b43f63ec6c12df9927834364922c34852f. 
Instead, I decided to rewrite this into a loop which I believe is semantically much cleaner than using a map for this use case, as we're not actually caring what the primary result is, we're just using it to fail early. In my mind the `for` loop is shorter, …
=> fix: Fixes compiler warning in latest compiler.

.github/actions/setup-env/action.yml, .github/workflows/ci-scrypto-builder.yml, Dockerfile, README.md
Updates to use [current stable rust](https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html) (1.81.0) for Cuttlefish, which we can then update to in the node.
=> update: Use rust 1.81.0 for cuttlefish

radix-transactions/src/builder/transaction_builder.rs, radix-transactions/src/manifest/any_manifest.rs, radix-transactions/src/manifest/decompiler.rs, radix-transactions/src/manifest/generator.rs, radix-transactions/src/manifest/manifest_traits.rs, radix-transactions/src/manifest/static_manifest_interpreter.rs, radix-transactions/src/model/test_transaction.rs, radix-transactions/src/model/v2/child_subintent_hashes_v2.rs, radix-transactions/src/model/v2/intent_core_v2.rs, radix-transactions/src/model/v2/mod.rs, radix-transactions/src/model/v2/signed_partial_transaction_v2.rs, radix-transactions/src/model/v2/subintent_manifest_v2.rs, radix-transactions/src/model/v2/transaction_manifest_v2.rs, radix-transactions/src/model/versioned.rs, radix-transactions/src/validation/transaction_validator.rs
A few things:
* Adds a `manifest` method to the v2 transaction builders -- for use in sargon
* Renames `ChildIntent` to `ChildSubintentSpecifier`
* Existing tests pass
* Trialled using this locally and it worked
=> feature: Add a `manifest` method to the v2 transaction builders

radix-engine-tests/assets/blueprints/fee/src/lib.rs, radix-engine-tests/tests/application/metering.rs, radix-engine/src/transaction/transaction_executor.rs
Add test to verify a system loan just about covers locking a fee in a scrypto component, with a badge check.
=> test: Add test of system loan limitations

radix-common-derive/src/decimal.rs, radix-common/src/math/decimal.rs, radix-common/src/math/precise_decimal.rs, radix-engine-interface/src/blueprints/resource/mod.rs, radix-engine-monkey-tests/src/lib.rs, radix-engine-tests/tests/application/common_transactions.rs, radix-engine-tests/tests/blueprints/pool_arithmetic.rs, radix-engine-tests/tests/blueprints/pool_multi_resource.rs, radix-engine-tests/tests/blueprints/pool_one_resource.rs, radix-engine-tests/tests/blueprints/pool_two_resource.rs, radix-engine-tests/tests/blueprints/validator.rs, radix-engine-tests/tests/system/auth_account.rs, radix-engine-tests/tests/system/royalty_edge_cases.rs, radix-engine-tests/tests/vm/decimal.rs, radix-engine/src/blueprints/consensus_manager/validator.rs, radix-engine/src/blueprints/resource/fungible/fungible_resource_manager.rs, radix-transactions/src/model/execution/executable_common.rs
* Makes the internal value of `Decimal` / `PreciseDecimal` private - this avoids some gotchas that us and the community have experienced - where they intend to e.g. create 2 from `Decimal(2.into())` but instead get 2 attos.
* Makes some of the functions `const`
* Adds `Decimal::ONE_ATTO`, `PreciseDecimal::ONE_ATTO`, `Decimal::ONE_SUBUNIT` and `PreciseDecimal::ONE_PRECISE_SUBUNIT` constants.
Whilst this is a "breaking change" for people who chose to update to Cuttlefish scrypto, I think it is a low-risk break, in that:
* I imagine it’s very rare for people to actually do this (or actually do this intentionally), so it likely won’t affect too much code in the wild.
* The change is very simple - `Decimal(x)` to `Decimal::from_attos(x)` - and is signposted on the `Decimal` / `PreciseDecimal` …
=> tweak: `Decimal` and `PreciseDecimal` subunits are no longer `pub`

radix-engine-tests/assets/blueprints/Cargo.lock, radix-engine-tests/assets/blueprints/Cargo.toml, radix-engine-tests/assets/blueprints/threading/Cargo.toml, radix-engine-tests/assets/blueprints/threading/src/lib.rs, radix-engine-tests/tests/system/mod.rs, radix-engine-tests/tests/system/threading.rs, radix-transactions/src/builder/transaction_builder.rs
Add some reference related tests.
=> Add some reference related tests

radix-common/src/constants/transaction_execution.rs, radix-engine-tests/assets/blueprints/Cargo.lock, radix-engine-tests/assets/blueprints/Cargo.toml, radix-engine-tests/assets/blueprints/wasm_limits/Cargo.toml, radix-engine-tests/assets/blueprints/wasm_limits/src/lib.rs, radix-engine-tests/tests/vm/mod.rs, radix-engine-tests/tests/vm/wasm_limits.rs, radix-engine/src/vm/wasm_runtime/scrypto_runtime.rs
Decrease max number of buffers from `32` to `4`.
=> Decrease max number of buffers

radix-engine-tests/tests/blueprints/account_deposit_modes.rs
Described in the test case - but this test checks that an empty bucket can't be used to pass resource assertions and then deposit to an account in a user-signed transaction (unbeknownst to a user in the wallet) in order to get around the `DefaultDepositRule::AllowExisting` setting in a future externally-initiated transaction.
Just adds the test case. The test currently passes due to behaviour of the worktop, rather than the account, which feels a little indirect for my liking, but it prevents the issue (at least via the manifest, and I'm much less concerned about non-manifest issues, as scrypto code is unlikely to be dealing with asserting against unknown empty buckets or interacting with an account with an `AllowExisting` deposit rule).
See new test.
=> test: Add test case for mitigating AllowExisting workaround

radix-engine-tests/assets/blueprints/Cargo.lock, radix-engine-tests/assets/blueprints/Cargo.toml, radix-engine-tests/assets/blueprints/sha256_in_scrypto/Cargo.toml, radix-engine-tests/assets/blueprints/sha256_in_scrypto/src/lib.rs, radix-engine-tests/benches/costing.rs
- Replaced `spin_loop` with `spin_loop_v1`, which now uses ScryptoRuntime.
- Removed `spin_loop_v3` (which is redundant to `spin_loop_v1`).
- Added `sha256_in_scrypto` benchmark.
=> Clean up spin_loop benchmarks

.github/actions/setup-env/action.yml, radix-clis/assets/template/rust-toolchain.toml_template, radix-clis/src/scrypto/cmd_new_package.rs
Add `rust-toolchain.toml` to scrypto package template
Existing tests and manual local test.
=> Add rust-toolchain.toml to scrypto package template

radix-engine-tests/tests/application/static_resource_movements_visitor.rs, radix-transactions/src/manifest/static_resource_movements/typed_invocation.rs
Fixed a bug in the static resource analyzer where `DirectMethod`s were not being considered in one of the match statements generated by the macro which lead to unreachable code being reached.
=> Add direct method handling in the `TypedInvocation` generation macro.

radix-engine-tests/tests/system/nullification.rs, radix-engine-tests/tests/system/transaction_tracker.rs, radix-engine/src/errors.rs, radix-engine/src/system/system_callback.rs
This PR adds intent hash to the rejection error code, so clients can know whether transaction intent hash or subintent hash was failing.
=> Add intent hash to the error code

radix-transactions/src/validation/transaction_validator.rs
Changed the visibility on some of the tx validator methods so that they're public.
=> Make some tx validator methods public

radix-transactions/examples/resources/auth_zone.rtm, radix-transactions/src/manifest/e2e.rs, radix-transactions/src/manifest/manifest_instructions.rs
Fixes a sheepish typo in `DropAuthZoneRegularProofs::IDENT`...
... and ensures this instruction is covered in `e2e.rs`
=> fix: Fix `PUSH_TO_AUTH_ZONE` instruction compilation

radix-engine-tests/src/lib.rs, radix-engine-tests/src/prelude.rs, radix-engine-tests/tests/application_folder.rs, radix-engine-tests/tests/blueprints_folder.rs, radix-engine-tests/tests/db_folder.rs, radix-engine-tests/tests/flash_folder.rs, radix-engine-tests/tests/kernel_folder.rs, radix-engine-tests/tests/protocol_folder.rs, radix-engine-tests/tests/system/subintent_auth.rs, radix-engine-tests/tests/system/subintent_verify_parent.rs, radix-engine-tests/tests/system_folder.rs, radix-engine-tests/tests/vm_folder.rs, radix-transactions/src/model/test_transaction.rs
Adds tests:
* `subintent_processor_uses_transaction_processor_global_caller()`
* `subintent_should_not_be_able_to_use_proofs_from_other_subintents()`
* `verify_parent_should_only_work_against_proofs_in_parent_intent()`
Also adds a `crate::prelude::*` for the `radix-engine-tests`, and a few new methods on transaction builder to reduce the boilerplate of making empty test subintents.
=> tests: Add further subintent and verify parent auth tests

radix-common/src/types/non_fungible_global_id.rs, radix-engine-tests/assets/blueprints/steal/src/lib.rs, radix-engine/src/blueprints/resource/auth_zone/auth_zone_substates.rs, radix-engine/src/blueprints/resource/package.rs, radix-engine/src/system/actor.rs, radix-engine/src/system/system_callback.rs, radix-engine/src/system/system_modules/auth/auth_module.rs, radix-engine/src/system/system_modules/auth/authorization.rs, radix-engine/src/system/system_modules/costing/costing_module.rs, radix-engine/src/system/transaction/multithread_intent_processor.rs
Covers mark-ups for:
* [#1910](https://github.com/radixdlt/radixdlt-scrypto/pull/1910#pullrequestreview-2305612174) - done
* Includes adding some more docs
* Includes adding some clearer versioned logic branches, and some field renames
* Includes adding some related docs and variable naming to the new AuthZone method which I noticed as I worked on the other bits
Markups for all these will follow in a separate PR (but may not make RC.1)
* [#1913](https://github.com/radixdlt/radixdlt-scrypto/pull/1913#pullrequestreview-2305642260)
* [#1914](https://github.com/radixdlt/radixdlt-scrypto/pull/1914#pullrequestreview-2306341233)
* [#1916](https://github.com/radixdlt/radixdlt-scrypto/pull/1916)
=> tweak: Markups for #1910, and some auth-zone neatenings

.github/actions/setup-env/action.yml, .github/workflows/ci.yml
- Warn (instead of return error) when no tests to run for `nextest`
(nextest changed default behaviour since version `0.9.85`)
- Update Rust version comments
=> CI fix + update Rust version comments

.github/actions/setup-env/action.yml, scrypto-install-scripts/install-scrypto-debian.sh, scrypto-install-scripts/install-scrypto-macos.sh, scrypto-install-scripts/install-scrypto-windows.ps1
Add Scrypto toolchain install scripts for macOS, Linux (Debian based distros) and Windows.
=> Add scrypto toolchain install shell scripts

scrypto-install-scripts/install-scrypto-macos.sh
- Add Homebrew install to macOS install script
- Fix check for LLVM in PATH variable
Manually tested on macOS
=> Add Homebrew install to macOS install script

examples/everything/src/lib.rs, examples/hello-world/README.md, examples/hello-world/src/lib.rs, radix-clis/assets/template/src/lib.rs
Update `Vault` and `Bucket` types to `Fungible` and `NonFungible` versions in examples and template.
- Existing tests pass.
- Manually tested updated `Hello` blueprint template
=> tweak: use fungible and non-fungible types in template and examples

radix-engine-tests/assets/blueprints/logger/src/lib.rs, radix-engine-tests/tests/vm/logging.rs, scrypto-compiler/src/lib.rs, scrypto-test/src/ledger_simulator/compile.rs, scrypto/src/macros.rs
Improve logging macros to work with IDEs better
Respective tests added
Change is backward-compatible. No actions required
=> Improve logging macros to work with IDEs better

.github/workflows/ci-scrypto-dev-container.yml, .github/workflows/publish-scrypto-dev-container.yml
Add CI to build and publish scrypto-dev-container docker target
=> feat: add ci for scrypto-dev-container docker target

.github/workflows/publish-cargo-crates.yml
- Mask AWS role and secret for crates on Github Workflow
=> ci: Add secrets to crate token

Cargo.toml
Following discussions with the wallet team integrating into sargon, who had some issues with the regex version being fixed, I'm just pulling together a PR to unfix this version, in the hopes that it makes it easier to integrate as a library.
The node still uses a fixed version courtesy of the lock file of course.
Existing tests pass 
N/A
=> tweak: Change dependency version fixing

radix-common/src/data/manifest/model/manifest_address_kinds.rs, radix-common/src/data/manifest/model/manifest_blob.rs, radix-common/src/lib.rs, radix-engine-interface/src/blueprints/access_controller/invocations.rs, radix-engine-interface/src/blueprints/account/invocations.rs, radix-engine-interface/src/blueprints/component.rs, radix-engine-interface/src/blueprints/consensus_manager/invocations.rs, radix-engine-interface/src/blueprints/locker/invocations.rs, radix-engine-interface/src/blueprints/macros.rs, radix-engine-interface/src/blueprints/package/invocations.rs, radix-engine-interface/src/blueprints/resource/fungible/fungible_resource_manager.rs, radix-engine-interface/src/blueprints/resource/non_fungible/non_fungible_resource_manager.rs, radix-engine-interface/src/blueprints/resource/proof_rule.rs, radix-engine-interface/src/blueprints/resource/resource_manager.rs, radix-engine-interface/src/blueprints/resource/vault.rs, radix-engine-interface/src/blueprints/transaction_tracker/invocations.rs, radix-engine-tests/tests/blueprints/account_locker.rs, radix-engine-tests/tests/misc/mod.rs, radix-engine-tests/tests/misc/typed_manifest_invocation.rs, radix-engine-tests/tests/misc_folder.rs, radix-rust/src/rust.rs, radix-transaction-scenarios/src/scenarios/account_locker.rs, radix-transactions/src/manifest/static_resource_movements/effect.rs, radix-transactions/src/manifest/static_resource_movements/typed_invocation.rs, sbor/src/schema/schema_comparison/schema_comparison_settings.rs
This PR adds tests to ensure that the `TypedManifestNativeInvocation` type has all of the functions and methods that are defined on blueprints that we support. This is because clients such as the toolkit are heavily relying on this and it must cover all functions
* Added a test that does NOT check that all blueprints are supported but that all functions, methods, and direct methods of the blueprints we've supported are supported.
=> Add tests for the typed invocations type

radix-engine-interface/src/blueprints/component.rs, radix-engine-tests/tests/blueprints/account_locker.rs, radix-transaction-scenarios/src/scenarios/account_locker.rs, sbor/src/schema/schema_comparison/schema_comparison_settings.rs
Implemented `From<ComponentAddress>` for `GenericGlobal<ManifestComponentAddress, M>`
=> Easier way to construct typed manifest globals

radix-engine-tests/tests/application/static_resource_movements_visitor.rs, radix-transactions/src/manifest/static_resource_movements/effect.rs
This PR improves the static analyzer so that it understands that some invocations will return resources that we know are not the input resources. This is particularly useful in staking transactions.
Tested that the XRD state is known in the worktop after a stake.
=> Improve the static analyzer to understand that some resources are not returned in invocations
