radixdlt/radixdlt-scrypto

scrypto/src/types/decimal.rs
Fixes https://github.com/radixdlt/radixdlt-scrypto/issues/92
=> Fix decimal negative division

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE
Resolves https://github.com/radixdlt/radixdlt-scrypto/issues/66
=> Add open source information

scrypto/src/types/decimal.rs
Fix https://github.com/radixdlt/radixdlt-scrypto/issues/67
=> Fix Decimal::one()

radix-engine/src/engine/process.rs
=> Check dangling locked buckets

radix-engine/tests/account/Cargo.toml, radix-engine/tests/account/src/account.rs, radix-engine/tests/account/src/lib.rs, radix-engine/tests/integration.rs, scrypto/src/core/account.rs
This fixes issue #107 and add a very basic test infrastructure for account.
=> Fix Account withdraw

.gitignore
Add pattern to .gitignore to ignore emacs backup files.
=> Be emacs friendly

.github/workflows/ci.yml, assets/template/tests/lib.rs, examples/hello-world/tests/lib.rs, examples/no-std/Cargo.toml, examples/no-std/rust-toolchain, examples/no-std/src/lib.rs, examples/no-std/tests/lib.rs, radix-engine/src/transaction/executor.rs, radix-engine/tests/account.rs, radix-engine/tests/bucket.rs, radix-engine/tests/component.rs, radix-engine/tests/core.rs, radix-engine/tests/lazy_map.rs, radix-engine/tests/non_fungible.rs, radix-engine/tests/resource_def.rs, radix-engine/tests/vault.rs, scrypto/src/macros.rs, scrypto/src/misc/cargo.rs, scrypto/src/misc/mod.rs, scrypto/src/misc/panic.rs, scrypto/src/misc/slice.rs, scrypto/src/prelude/mod.rs, simulator/src/scrypto/cmd_new_package.rs, simulator/src/utils/cargo.rs, test.sh
- Added `compile_package` macro
- Renamed `include_code` to `include_package`
=> Add compile package macro

radix-engine/src/engine/process.rs, radix-engine/tests/non_fungible.rs, radix-engine/tests/non_fungible/src/non_fungible.rs, scrypto/src/engine/api.rs, scrypto/src/resource/resource_def.rs
Add a non_fungible_exists() method, that will return true if it does and false otherwise.
A engine call has also been implemented. And radix engine process also updated.
=> Scry 82 add a way to check if a nft with id exists

simulator/src/ledger/dumper.rs, simulator/src/ledger/radix_engine_db.rs
Fix issue with `resim show $component` and `resim show-ledger`
=> Fix ledger state dump

tags.sh
Adds tag for vim and xemacs users for easy browsing code. This is extremely helpful if you want to understand code.
=> Scry 128 add tags generator for vim and xemacs users for browsing code easily

radix-engine/src/engine/process.rs, radix-engine/src/model/transaction.rs, radix-engine/src/model/worktop.rs, radix-engine/tests/bucket.rs
To allow creation of empty buckets in manifest
=> Fix empty bucket creation error

sbor-derive/src/decode.rs, sbor-derive/src/encode.rs, sbor-tests/tests/decode.rs, sbor-tests/tests/encode.rs, sbor/src/decode.rs, scrypto-derive/src/blueprint.rs, scrypto-tests/tests/empty_blueprint.rs
This PR fix an issue with empty blueprint compilation.
=> Fix empty blueprint compilation

scrypto/src/math/decimal.rs
Decimal::powi(&self, exp:i32) -> Decimal function is now implemented with approximation. This solution will also work once we make Decimal::SCALE mutable.
=> powi(i32) function for Decimal implemented

radix-engine/src/ledger/traits.rs, simulator/src/ledger/dumper.rs, simulator/src/ledger/radix_engine_db.rs
One of the recent PRs introduced changes to the substate_ids which lead the resim show and show-ledger commands to stop functioning correctly. This PR fixes these issues.
=> Fix resim show and show-ledger issues

radix-engine-stores/src/memory_db.rs, radix-engine-stores/src/rocks_db.rs, radix-engine/src/engine/kernel.rs, radix-engine/src/engine/node_ref.rs, radix-engine/src/engine/track.rs, radix-engine/src/engine/track_support.rs, radix-engine/src/ledger/bootstrap.rs, radix-engine/src/ledger/memory.rs, radix-engine/src/ledger/traits.rs, radix-engine/src/state_manager/staging.rs, radix-engine/src/state_manager/state_diff.rs, radix-engine/tests/stored_external_component.rs, radix-engine/tests/stored_external_component/src/lib.rs, radix-engine/tests/stored_local_component.rs
Don't allow child components to be called directly
=> Feature: root and child components

scrypto-abi/src/types.rs
Mini PR to help me debug some failing unit tests on the Java side 👍
=> Fix/ Improve custom codec decode error

radix-engine-stores/Cargo.toml, radix-engine-stores/src/rocks_db.rs
This is to suppress security warning.
=> Update rocksdb version

radix-engine/src/engine/track_support.rs, radix-engine/tests/non_fungible.rs, radix-engine/tests/non_fungible/src/lib.rs
Resolves https://github.com/radixdlt/radixdlt-scrypto/issues/509
=> Fix vault becoming illiquid after proof generation

radix-engine/benches/radix_engine.rs, radix-engine/src/constants.rs, scrypto-unit/src/test_runner.rs
- 10x cost unit limit
- 0.1x cost unit price
=> Change default parameters

radix-engine/src/engine/errors.rs, radix-engine/src/engine/wasm_runtime.rs, radix-engine/src/model/nodes/auth_zone.rs, radix-engine/src/model/nodes/bucket.rs, radix-engine/src/model/nodes/component.rs, radix-engine/src/model/nodes/package.rs, radix-engine/src/model/nodes/proof.rs, radix-engine/src/model/nodes/resource_manager.rs, radix-engine/src/model/nodes/system.rs, radix-engine/src/model/nodes/vault.rs, radix-engine/src/model/nodes/worktop.rs
Implemented `From<RuntimeError>` so that error cruft is reduced
=> Architecture: Cleanup InvokeError::Downstream

radix-engine/src/engine/interpreters/scrypto_interpreter.rs, radix-engine/src/wasm/wasmer.rs
=> docs: Improve wasmer/scrypto interpreter docs

radix-engine-interface/src/math/precise_decimal.rs
There were two bugs:
1. We use `truncate()` function to convert `PreciseDecimal` to `Decimal`. The implementation was wrong. Now its corrected.
2. `PreciseDecimal::from(decimal)` - the `from()` gave plain wrong results.
Tests were also added to make sure this does not happen again.
=> truncate() bugfix, and dec -> pdec conversion bugfix

radix-engine/tests/time.rs, scrypto-unit/src/test_runner.rs
This brings in `set_current_time` and `get_current_time` to `TestRunner`
=> add set_current_time and get_current_time to test_runner

radix-engine/tests/wasm/deep_sbor_response.wat
Following questions from Yulong and experience writing other bits of WASM manually, I thought I'd rewrite it to be a little clearer about that it's doing
=> Refactor: Neaten deep sbor response wasm

radix-engine-interface/src/api/types/actor.rs, radix-engine-interface/src/model/access_controller/invocations.rs, radix-engine/src/model/access_controller/executables.rs, radix-engine/src/model/access_controller/state_machine.rs, radix-engine/src/model/access_controller/substates.rs, radix-engine/tests/access_controller.rs
No real logic changes, just a `git revert` :)
=> Fix: Revert Nonced Recovery

radix-engine-stores/src/hash_tree/hash_tree_facade.rs, radix-engine-stores/src/hash_tree/mod.rs, radix-engine-stores/src/hash_tree/test.rs, radix-engine-stores/src/hash_tree/tree_store.rs
A demonstration for Jakub about what I meant regarding making Payload generic.
=> tweak: Implement compile time genericism for tree nodes

radix-engine/src/system/kernel_modules/transaction_limits/module.rs
Compilation fix after merging PR https://github.com/radixdlt/radixdlt-scrypto/pull/839
=> Compilation fix after develop merge

radix-engine/src/system/kernel_modules/execution_trace/module.rs
Caught here: https://github.com/radixdlt/babylon-node/pull/339#discussion_r1120544766
This one is only about ordering within the `receipt.resource_changes`. The transaction results were fine (i.e. this non-det bug was not affecting execution or substate store).
That ordering became important only because babylon-node starts to track ledger receipt hashes (in a receipt tree).
=> Switching from HashMap to IndexMap for deterministic order of resource changes

radix-engine-tests/tests/account.rs, radix-engine/src/system/kernel_modules/execution_trace/module.rs
Add back `ResourceAddress` to `ResourceChange` which we will need for gateway transaction preview
=> Add back ResourceAddress to ResourceChange

radix-engine-tests/tests/execution_trace.rs, radix-engine/src/system/kernel_modules/execution_trace/module.rs, radix-engine/src/transaction/transaction_receipt.rs
Added a method which derives the worktop changes from the execution trace output.
=> Per instruction worktop changes

simulator/Cargo.lock, transaction/Cargo.toml, transaction/src/manifest/generator.rs
Simply adding a small test for Les to help with generating Schema commands for the manifest.
=> tweak: Add non fungible schema generate manifest instruction test

assets/blueprints/Cargo.lock, examples/hello-world/Cargo.lock, transaction/Cargo.toml, transaction/examples/resources/creation/non_fungible/with_initial_supply.rtm, transaction/src/manifest/decompiler.rs, transaction/src/manifest/e2e.rs, transaction/src/manifest/generator.rs
Fixes a compilation and decompilation issue with the `CREATE_NON_FUNGIBLE_RESOURCE_WITH_INITIAL_SUPPLY` instruction.
=> Bugfix: decompilation issue with `CREATE_NON_FUNGIBLE_RESOURCE_WITH_INITIAL_SUPPLY`

radix-engine-common/src/data/scrypto/model/non_fungible_local_id.rs
To decrease the risk of issues with using the string format for ids, we now enforce that the numerical ids must be canonical, the following forms are no longer accepted:
* `##`
* `#+3#`
* `#003#`
Added a few more automated test cases
Ensure that if you ever create a string representation of a numeric NFId, then you use the canonical format (eg #123# instead of #0123#)
=> fix: Requires canonical format for integer NFIDs eg #124#

CONTRIBUTING.md
As discussed at https://rdxworks.slack.com/archives/C01M90Y2448/p1680096808582729?thread_ts=1680025525.204779&cid=C01M90Y2448
=> Documenting the conventions around deterministic execution (mostly HashMap usage)

fuzz-tests/afl.sh
Try different power schedules to diversify fuzzing mutations
=> Use different power schedules per fuzzing session

.github/workflows/fuzzing.yml, fuzz-tests/process_fuzz_results.sh
Changes:
- Group collected crash/hang files by crash type
- Show processing results int Fuzzing workflow
- Allow processing local fuzzing results.
Exemplary processing output:
```
Crash/hang info
command : radixdlt-scrypto/fuzz-tests/target/release/transaction <file>
panic   :
file    : afl/transaction/transaction_1_explore/hangs/id:000000,src:003019+003702,time:192834768,execs:271690000,op:splice,rep:4
file    : afl/transaction/transaction_1_explore/hangs/id:000001,src:000585,time:209756340,execs:295734000,op:havoc,rep:16
panic   : thread 'main' panicked at 'Amount checked upfront: ParseIntError { kind: PosOverflow }', /Users/lukaszrubaszewski/work/radixdlt/radixdlt-scrypto/fuzz-tests/run_4598208804/radixdlt-scrypto/radix-engine/src/blueprints/resource/auth_zone_composition.rs:78:48
file …
```
=> Group crash files by crash type

simulator/tests/resim.sh
Merge `release/rcnet_v1` into `develop`
Changes:
- #952  - In fact the `resim` issue has been indirectly fixed on develop by #930 , but we want to merge the test for the issue.
=> Merge `release/rcnet_v1` to `develop`

radix-engine/src/system/bootstrap.rs
Add `icon_url` metadata for XRD token.
=> Add XRD icon url

sbor/src/decoder.rs
Disallows trailing zeros in LEB128 to ensure unique size representation.
=> Disallow trailing zeros in LEB128

radix-engine/src/vm/vm.rs
Very minor change - addresses this comment in this PR: https://github.com/radixdlt/radixdlt-scrypto/pull/984#discussion_r1181973193
=> fix: Panic on package instantiation failure

radix-engine-interface/src/blueprints/resource/worktop.rs, radix-engine-tests/tests/own.rs, radix-engine/src/vm/vm.rs
(Note - the bench doesn't work below because the _current_ develop doesn't compile 😅)
=> fix: Minor compile issues from merge clash

radix-engine/Cargo.toml, radix-engine/src/system/module_mixer.rs
Replacing repetitive code blocks in `module_mixer.rs` with macro which generates module calls basing on passed function name and parameters.
=> Refactor/Module Mixer calls dispatcher

assets/blueprints/Cargo.lock, examples/hello-world/Cargo.lock, radix-engine-tests/tests/epoch_manager.rs, simulator/Cargo.lock
Added more tests to epoch manager
=> Architecture: Add more epoch manager tests

radix-engine-tests/tests/epoch_manager.rs, radix-engine/src/track/mod.rs, radix-engine/src/track/test.rs, radix-engine/src/track/track.rs, radix-engine/src/track/utils.rs
⚠️ This is built on top of https://github.com/radixdlt/radixdlt-scrypto/pull/1021 since it addresses a TODO that was encountered there (and it fixes some tests there)
=> Implementing an "overlying iterator" returning [db values + tracked changes] for sorted listing

radix-engine-interface/src/blueprints/epoch_manager/invocations.rs, radix-engine-tests/tests/epoch_manager.rs, radix-engine-tests/tests/events.rs, radix-engine/src/blueprints/epoch_manager/epoch_manager.rs, radix-engine/src/blueprints/epoch_manager/events/epoch_manager.rs, radix-engine/src/blueprints/epoch_manager/events/validator.rs, radix-engine/src/blueprints/epoch_manager/package.rs, radix-engine/src/blueprints/epoch_manager/validator.rs, radix-engine/src/transaction/transaction_receipt.rs, simulator/Cargo.lock
This applies the solution **Q10-B** of https://radixdlt.atlassian.net/wiki/spaces/S/pages/3058827265/REP-83+Calculating+Emissions+and+Handling+Validator+Fees
(some discussion on what fields to include: https://rdxworks.slack.com/archives/C01HK4QFXNY/p1683742356023449?thread_ts=1683570653.786939&cid=C01HK4QFXNY)
=> Emitting an event on validator's reward received

radix-engine/src/blueprints/account/blueprint.rs
There is no longer special casing for XRD except in the `AllowExisting` mode where XRD deposits are always allowed.
=> Feature: No special casing of XRD deposits

scrypto-unit/src/lib.rs, scrypto-unit/src/utils.rs
A small utility function for dumping manifest required for some work that @jakerdxworks is doing.
=> Feature: Dump manifest utility function

radix-engine-queries/src/typed_substate_layout.rs, radix-engine-tests/tests/bootstrap.rs, radix-engine/src/system/node_modules/metadata/package.rs, radix-engine/src/system/system.rs, scrypto-unit/src/test_runner.rs
Previous branch still required some cleanup but was merged! This is just some additional cleanup
=> Feature: Tombstone cleanup

.github/workflows/bench.yml, .github/workflows/ci.yml, radix-engine-common/src/network/mod.rs, transaction/src/manifest/e2e.rs
This PR contains 4 additional tests in e2e suite. All of them modelling simple transfer transactions which should be supported by Ledger App. Few minor related changes enable generation of test data not only for simulator but for any defined network.
=> Add typical transfers to e2e test suite for use by Ledger App

.github/workflows/bench.yml, radix-engine/src/errors.rs, radix-engine/src/system/system.rs
This PR removes `SchemaCache` in favour of system schema cache.
=> Remove SchemaCache

radix-engine-interface/src/blueprints/resource/resource.rs, radix-engine-tests/benches/radiswap.rs, radix-engine-tests/benches/resources_usage.rs, radix-engine-tests/benches/transfer.rs, radix-engine-tests/tests/fuzz_transactions.rs, radix-engine-tests/tests/preview.rs, radix-engine-tests/tests/transaction_executor.rs, radix-engine-tests/tests/transaction_limits.rs, radix-engine-tests/tests/transaction_multi_threaded.rs, radix-engine/src/blueprints/resource/fungible/fungible_bucket.rs, radix-engine/src/blueprints/resource/fungible/fungible_vault.rs, radix-engine/src/system/system_modules/costing/fee_reserve.rs, radix-engine/src/system/system_modules/costing/fee_summary.rs, radix-engine/src/transaction/transaction_executor.rs, scrypto-unit/src/test_runner.rs, simulator/src/resim/mod.rs, transaction-scenarios/src/runners/mod.rs, transaction/src/model/v1/system_transaction.rs
- Added sanity check in fee distribution
- Fixed execution configs in TestRunner
=> Add fee sanity checks and fix TestRunner

radix-engine-tests/tests/proof_creation.rs, radix-engine/src/blueprints/resource/auth_zone_composition.rs
Adds test for composing non-fungible proof with large amount.
=> Add test for composing proof with large amount

transaction/src/manifest/e2e.rs
Minor change in simple transfers tests, which enable checking how XRD resource detection works in Babylon Ledger App
=> Enable testing XRD detection in ledger app

radix-engine-interface/src/blueprints/account/invocations.rs, radix-engine-tests/tests/metering.rs, radix-engine/src/blueprints/account/blueprint.rs, radix-engine/src/blueprints/account/package.rs
* Remove create local account function
=> Remove create local account

radix-engine-queries/src/typed_substate_layout.rs
Remove unused package field value
=> Bugfix: Remove unused typed package field value

radix-engine-interface/src/blueprints/resource/access_rules.rs, radix-engine/src/blueprints/resource/resource_manager_common.rs
Lock resource manager roles when possible
=> Lock resource manager roles when possible

radix-engine/src/system/bootstrap.rs
Expose API for generating a flash receipt and merging it with a system transaction receipt. To be used for genesis generation.
=> Feature: Expose api for generating a flash receipt

radix-engine-tests/tests/vault_freeze.rs, transaction-scenarios/generated-examples/fungible_resource/008--fungible-max-div-recall-frozen-vault.rtm, transaction-scenarios/generated-examples/non_fungible_resource/010--non-fungible-resource-recall-frozen-vault.rtm, transaction-scenarios/src/scenarios/fungible_resource.rs, transaction-scenarios/src/scenarios/non_fungible_resource.rs
=> Clean up tests

radix-engine/src/blueprints/resource/non_fungible/non_fungible_vault.rs
Cleans up `take_by_amount` implementation.
=> Clean up take_by_amount for non-fungible vault

radix-engine-tests/tests/blueprints/proof/src/receiver.rs, radix-engine-tests/tests/proof.rs, radix-engine-tests/tests/proof_creation.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/proof.rs, scrypto/src/resource/vault.rs
- Improve error message for check failure
- Add `check_with_message` for custom messages
=> Improve error messaging

radix-engine-common/benches/math/macros.rs, radix-engine-common/benches/schema.rs, radix-engine-tests/Cargo.toml, radix-engine-tests/benches/costing.rs, radix-engine-tests/benches/radiswap.rs, radix-engine-tests/benches/resources_usage.rs, radix-engine-tests/benches/transaction_processing.rs, radix-engine-tests/benches/transaction_validation.rs, radix-engine-tests/benches/transfer.rs
Update bench names for consistency (easier to review on Github PR).
=> Clean up bench names

radix-engine-stores/src/rocks_db_with_merkle_tree/mod.rs, radix-engine-tests/benches/radiswap.rs
- Pre-fill database with accounts instead of packages
- Use "random" accounts to interact with the `Radiswap` component
=> Update radiswap bench

.github/workflows/ci.yml, assets/template/src/lib.rs, assets/template/tests/lib.rs, examples/hello-world/src/lib.rs, radix-engine-tests/tests/preview.rs, radix-engine/src/system/system_modules/costing/fee_summary.rs, radix-engine/src/transaction/transaction_executor.rs, transaction/src/model/v1/preview_transaction.rs
- Fixed preview transaction payload size
- Fixed an issue with previewing without locking fee
- Updated the hello world template
=> Fix transaction preview issues

radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/vm/wasm/prepare.rs
Get rid of compilation warnings
=> Get rid of compilation warnings

radix-engine-tests/tests/blueprints/vault/src/lib.rs, radix-engine-tests/tests/blueprints/vault/src/vault_deposit_events.rs, radix-engine-tests/tests/vault.rs
Adds a simple test to verify deposit event for vault creation.
=> Verify deposit event for creating vault

simulator/src/ledger/dumper.rs, simulator/src/resim/cmd_show_ledger.rs
Restore metadata display for RESIM.
=> Restore RESIM metadata display

radix-engine-tests/tests/blueprints/scrypto_env/src/lib.rs, radix-engine-tests/tests/bootstrap.rs, radix-engine/src/system/bootstrap.rs, radix-engine/src/transaction/system_structure.rs
This properly fixes the 🛑 described at https://github.com/radixdlt/babylon-node/pull/620#issuecomment-1685974132.
=> Returning substate system structures in system flash receipt

transaction/src/manifest/e2e.rs
Add tests for new format of simple transfers
=> Add tests for new format of simple transfers

scrypto/src/resource/resource_manager.rs
Allow Resource Manager in scrypto to burn `FungibleBucket` and `NonFungibleBucket`
=> Feature: Allow ResourceManager to burn any Into<Bucket>

transaction-scenarios/generated-examples/metadata/001--metadata-create-package-with-metadata.rtm, transaction-scenarios/generated-examples/metadata/002--metadata-create-component-with-metadata.rtm, transaction-scenarios/generated-examples/metadata/003--metadata-create-resource-with-metadata.rtm, transaction-scenarios/src/scenarios/metadata.rs
Add name to origin metadata item
=> Add name to origin metadata item

sbor/src/schema/schema_validation/mod.rs
Verify duplicate field name behaviour
=> Verify duplicate field name behaviour

radix-engine-tests/benches/costing.rs
Add benchmark for decoding and validating type `Vec<u8>`
=> Add benchmark for decoding and validating Vec<u8>

radix-engine/src/blueprints/transaction_tracker/package.rs, radix-engine/src/transaction/transaction_executor.rs
Add transaction tracker version wrappers
=> Architecture: Transaction Tracker Version Wrappers

radix-engine-tests/assets/cost_flash_loan.csv, radix-engine-tests/assets/cost_mint_large_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_mint_small_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_publish_large_package.csv, radix-engine-tests/assets/cost_radiswap.csv, radix-engine-tests/assets/cost_transfer.csv, radix-engine-tests/assets/cost_transfer_to_virtual_account.csv, radix-engine-tests/tests/common_transformation_costs.rs, radix-engine-tests/tests/preview.rs, radix-engine/src/system/system_modules/costing/costing_module.rs, radix-engine/src/system/system_modules/module_mixer.rs, radix-engine/src/transaction/transaction_executor.rs, scrypto-unit/src/test_runner.rs, transaction/src/builder/manifest_builder.rs, transaction/src/model/executable.rs, transaction/src/model/v1/preview_transaction.rs, transaction/src/model/v1/system_transaction.rs, transaction/src/model/v1/test_transaction.rs, transaction/src/model/v1/validated_notarized_transaction.rs, transaction/src/signing/signer.rs, transaction/src/validation/transaction_validator.rs
- Fixed a bug in number of signature counting
- Updated manifest transformation cost estimations
=> Fix a bug in number of signature validations

radix-engine-tests/tests/consensus_manager.rs, radix-engine/src/blueprints/consensus_manager/validator.rs
Fix decimal overflow panic in `Validator::start_unlock_owner_stake()`
=> Fix decimal overflow unwrap in start_owner_unlock

.vscode/settings.json, radix-engine-tests/tests/pool_multi_resource.rs, radix-engine-tests/tests/pool_one_resource.rs, radix-engine-tests/tests/pool_two_resource.rs, radix-engine/src/blueprints/pool/multi_resource_pool/blueprint.rs, radix-engine/src/blueprints/pool/multi_resource_pool/error.rs, radix-engine/src/blueprints/pool/one_resource_pool/blueprint.rs, radix-engine/src/blueprints/pool/one_resource_pool/error.rs, radix-engine/src/blueprints/pool/two_resource_pool/blueprint.rs, radix-engine/src/blueprints/pool/two_resource_pool/error.rs, radix-engine/src/system/system_modules/kernel_trace/module.rs
Add checks and errors in case of `Decimal` overflows to the Pool package
=> Bugfix: Fix Pool Decimal Handling

radix-engine-tests/tests/validator.rs, radix-engine/src/blueprints/consensus_manager/validator.rs, scrypto-unit/src/test_runner.rs
Fix Decimal computation bug in `get_redemption_value` of Validator Component
=> Bugfix: Fix Validator get_redemption_value()

radix-engine-tests/tests/blueprints/resource/src/lib.rs, radix-engine-tests/tests/resource.rs, radix-engine/src/blueprints/resource/bucket_common.rs, radix-engine/src/blueprints/resource/fungible/fungible_bucket.rs, radix-engine/src/blueprints/resource/fungible/fungible_vault.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_bucket.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_vault.rs, radix-engine/src/blueprints/resource/vault_common.rs
Fix take_advanced method in Bucket/Vault
=> Bugfix: Fix take_advanced method in Bucket/Vault

.gitignore, radix-engine-queries/src/typed_native_events.rs, radix-engine-tests/tests/blueprints/scrypto_env/src/lib.rs, radix-engine/src/blueprints/account/blueprint.rs, scrypto-unit/src/test_runner.rs
Some minor cleanups to support Source Based Coverage
=> Architecture: Support Source Based Coverage

radix-engine-profiling/resources-tracker-macro/scripts/convert.py, radix-engine-tests/assets/cost_flash_loan.csv, radix-engine-tests/assets/cost_mint_large_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_mint_small_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_publish_large_package.csv, radix-engine-tests/assets/cost_radiswap.csv, radix-engine-tests/assets/cost_transfer.csv, radix-engine-tests/assets/cost_transfer_to_virtual_account.csv, radix-engine/src/system/system_modules/costing/fee_table.rs
Ported PR https://github.com/radixdlt/radixdlt-scrypto/pull/1402 to rcnet-v3.
=> SCRY-455 costing fixme #01

radix-engine/src/blueprints/consensus_manager/consensus_manager.rs, radix-engine/src/blueprints/models/keys.rs, radix-engine/src/blueprints/models/native_blueprint_state_macro.rs, radix-engine/src/system/system_substates.rs
Really tiny PR to tweak an SBOR work-around
=> tweak: Minor tidy up of system substate wrappers

radix-engine-common/src/address/hrpset.rs, radix-engine-common/src/types/addresses/internal_address.rs, radix-engine-common/src/types/entity_type.rs, radix-engine-queries/src/typed_native_events.rs, radix-engine-queries/src/typed_substate_layout.rs, radix-engine-tests/assets/cost_transfer_to_virtual_account.csv, radix-engine/src/system/id_allocation.rs, radix-engine/src/utils/native_blueprint_call_validator.rs, scrypto/src/prelude/mod.rs
- Remove `InternalAccount` entity type and HRP prefix
- Add `Url` alias for `UncheckedUrl`
=> Two minor changes

radix-engine-common/src/constants/transaction_execution.rs, radix-engine-common/src/constants/wasm.rs
=> Adjust limits for RCNet v3 (Part 2)

radix-engine-common/src/crypto/public_key_ed25519.rs
Fix `Ed25519PublicKey::to_hash`
=> Fix Ed25519PublicKey::to_hash

radix-engine-common/src/math/decimal.rs, radix-engine-common/src/math/precise_decimal.rs, radix-engine-common/src/math/rounding_mode.rs, radix-engine-interface/src/blueprints/resource/mod.rs, radix-engine-tests/tests/consensus_manager.rs, radix-engine/src/blueprints/pool/multi_resource_pool/blueprint.rs, radix-engine/src/blueprints/pool/one_resource_pool/blueprint.rs, radix-engine/src/blueprints/pool/two_resource_pool/blueprint.rs, radix-engine/src/blueprints/resource/fungible/fungible_bucket.rs, radix-engine/src/blueprints/resource/fungible/fungible_resource_manager.rs, radix-engine/src/blueprints/resource/fungible/fungible_vault.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_bucket.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_resource_manager.rs, radix-engine/src/blueprints/resource/non_fungible/non_fungible_vault.rs
Implemented safe arithmetical operations for decimals.
- Implemented safe arithmetical methods:
-  `abs()` replaced with `safe_abs()`
- `round()` replaced with `safe_round()`
- `ceiling()` replaced with`safe_ceiling()`
- `floor()` replaced with `safe_floor()`
These methods return: 
- `None` in case of overflow, 
-  `Some(result)` in case of successful operation
Tests have been refactored to support new methods.
Scrypto code shall be revised in terms of usage of the above methods.
=> Refactor decimal overflow handling - part 2

radix-engine-common/src/constants/transaction_execution.rs, radix-engine-tests/benches/costing.rs, radix-engine/src/utils/package_extractor.rs, transaction/src/model/v1/preview_transaction.rs
=> Bump PREVIEW_CREDIT_IN_XRD

radix-engine-interface/src/api/node_modules/metadata/models/url.rs
Relax URL regex to allow fragment
=> Relax URL regex to allow fragment

radix-engine/src/blueprints/access_controller/blueprint.rs, radix-engine/src/blueprints/access_controller/state_machine.rs
Cleanup Access Controller
* Removed `this_package` role
* Replaced `Own` with `Vault`
* Removed `ComponentRoyalty` from AccessController
=> Cleanup access controller

radix-engine-tests/tests/auth_scenarios.rs, radix-engine-tests/tests/blueprints/Cargo.toml, radix-engine-tests/tests/blueprints/auth_scenarios/Cargo.toml, radix-engine-tests/tests/blueprints/auth_scenarios/src/lib.rs
=> Test: Auth Scenarios

radix-engine-tests/tests/common_transformation_costs.rs
Add assertion to prevent regression
=> Add assertion to prevent regression

radix-engine-interface/src/api/object_api.rs
Fix `AttachedModuleId` type data
=> Fix AttachedModuleId type data

radix-engine-common/src/data/manifest/model/manifest_address.rs, radix-engine-common/src/data/manifest/model/manifest_address_reservation.rs, radix-engine-common/src/data/manifest/model/manifest_blob.rs, radix-engine-common/src/data/manifest/model/manifest_bucket.rs, radix-engine-common/src/data/manifest/model/manifest_decimal.rs, radix-engine-common/src/data/manifest/model/manifest_expression.rs, radix-engine-common/src/data/manifest/model/manifest_non_fungible_local_id.rs, radix-engine-common/src/data/manifest/model/manifest_precise_decimal.rs, radix-engine-common/src/data/manifest/model/manifest_proof.rs, radix-engine-common/src/network/mod.rs, radix-engine-common/src/types/addresses/component_address.rs, radix-engine-common/src/types/addresses/global_address.rs, radix-engine-common/src/types/addresses/internal_address.rs
Added new unit tests to `radix-engine-common` module.
=> New tests for radix-engine-common

native-sdk/src/resource/bucket.rs, native-sdk/src/resource/proof.rs
Fix native-sdk `get_outer_object_id`.
=> Fix native-sdk get_outer_object_id

radix-engine-tests/Cargo.toml, radix-engine-tests/tests/blueprints/reference/src/lib.rs, radix-engine-tests/tests/reference.rs, radix-engine/src/kernel/call_frame.rs
Just more tests for storing DA references.
=> Test: add DA reference to substate tests

radix-engine-tests/assets/cost_flash_loan.csv, radix-engine-tests/assets/cost_mint_large_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_mint_small_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_publish_large_package.csv, radix-engine-tests/assets/cost_radiswap.csv, radix-engine-tests/assets/cost_transfer.csv, radix-engine-tests/assets/cost_transfer_to_virtual_account.csv, radix-engine-tests/tests/common_transformation_costs.rs, radix-engine-tests/tests/storage.rs, radix-engine/src/system/system_modules/transaction_runtime/module.rs
=> Fix event size counting

radix-engine-tests/tests/blueprints/system/src/lib.rs, radix-engine-tests/tests/system.rs, radix-engine/src/system/type_info.rs
Add address reservation tests.
=> Test address reservation

radix-engine-tests/tests/blueprints/system/src/lib.rs, radix-engine-tests/tests/system.rs, radix-engine/src/system/system_modules/kernel_trace/module.rs, scrypto/src/component/component.rs, scrypto/src/modules/metadata.rs, scrypto/src/modules/role_assignment.rs
Adds tests for writing after locking.
=> Test writing after locking

radix-engine-tests/tests/blueprints/system/src/lib.rs, radix-engine-tests/tests/system.rs, scrypto/src/modules/role_assignment.rs
Add random tests for role assignment
=> Random role assignment tests

radix-engine-tests/tests/auth_account.rs, radix-engine-tests/tests/blueprints/auth_scenarios/src/lib.rs, radix-engine/src/system/system_modules/auth/authorization.rs
Fix a bug in system auth for `CountOf` evaluation.
=> Bugfix: fix ProofRule::CountOf evaluation

radix-engine/src/errors.rs, radix-engine/src/transaction/transaction_executor.rs
=> Panic instead of abort

radix-engine-common/src/constants/transaction_execution.rs, radix-engine-interface/src/blueprints/resource/role_assignment.rs, radix-engine-tests/tests/package.rs, radix-engine/src/blueprints/package/package.rs, transaction-scenarios/generated-examples/non_fungible_resource_with_remote_type/001--non-fungible-resource-with-remote-type-registration.rtm, transaction-scenarios/generated-examples/non_fungible_resource_with_remote_type/002--non-fungible-resource-with-remote-type.rtm, transaction-scenarios/src/scenarios/non_fungible_resource_with_remote_type.rs
* Add tests for some of the package error paths.
* Add name checks to types.
=> Add tests around unexecuted error paths

simulator/src/utils/common_instructions.rs
Add support for parsing `GlobalAddress` in `resim`
=> Add support for parsing `GlobalAddress` in `resim`

radix-engine-tests/assets/cost_mint_large_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_mint_small_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_publish_large_package.csv, radix-engine-tests/assets/cost_radiswap.csv, radix-engine-tests/assets/cost_transfer_to_virtual_account.csv, radix-engine/src/system/checkers/system_db_checker.rs, radix-engine/src/system/system_type_checker.rs, simulator/src/utils/common_instructions.rs
* Add bootstrap flash of transient fields Fix
* Add transient field checks in system db checker
=> BugFix: Fix bootstrap flashing of transient fields and add system db checker

radix-engine-tests/tests/blueprints/clock/src/lib.rs, radix-engine-tests/tests/clock.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs
Fix Epoch Manager compare current time overflows
=> Fix compare_current_time overflows

radix-engine/src/system/checkers/system_db_checker.rs, radix-engine/src/track/track.rs
Don't store transient substates
=> Fix transient substates

assets/blueprints/radiswap/src/lib.rs
A small PR that adds a single event to Radiswap that uses the function emitter as requested by the Gateway team.
=> Add function emitter event to Radiswap

monkey-tests/tests/fuzz_system.rs, scrypto-unit/src/test_runner.rs
Implement simple System Layer fuzz/monkey test
=> Test: Fuzz System Layer

radix-engine-tests/Cargo.toml, radix-engine-tests/tests/blueprints/Cargo.toml, radix-engine-tests/tests/blueprints/tuple-return/Cargo.toml, radix-engine-tests/tests/blueprints/tuple-return/src/lib.rs, radix-engine-tests/tests/test_environment.rs, scrypto-derive/Cargo.toml, scrypto-derive/src/blueprint.rs
This PR fixes tuple returns in `scrypto-test`.
=> Bugfix: fix tuple returns in `scrypto-test`.

radix-engine-tests/tests/bootstrap.rs, radix-engine/src/blueprints/consensus_manager/consensus_manager.rs
Make sure we don't exceed validator index.
=> Fix validator index exceeded

radix-engine-common/src/constants/wasm.rs, radix-engine-tests/assets/cost_flash_loan.csv, radix-engine-tests/assets/cost_mint_large_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_mint_small_size_nfts_from_manifest.csv, radix-engine-tests/assets/cost_publish_large_package.csv, radix-engine-tests/assets/cost_radiswap.csv, radix-engine/src/vm/wasm_runtime/scrypto_runtime.rs
Fix potential overflow in consume_wasm_execution_units
=> Fix potential overflow in consume_wasm_execution_units

assets/blueprints/max_transaction/src/lib.rs, radix-engine-tests/tests/blueprints/scrypto_env/src/lib.rs, radix-engine-tests/tests/scrypto_env.rs
Test that scrypto cannot create a proof from a signature resource
=> Test: Scrypto read sig

radix-engine-tests/assets/cost_flash_loan.csv, radix-engine/src/kernel/call_frame.rs, radix-engine/src/kernel/kernel.rs
Add costing for `close_all_substates`
=> Cost close_all_substates

radix-engine/src/vm/wasm/errors.rs, radix-engine/src/vm/wasm/prepare.rs
Small clean-ups to the WASM VM preparation stage.
=> WASM VM Small cleanup

radix-engine-common/src/math/precise_decimal.rs
=> Port fixed TryFrom slice from Decimal to PreciseDecimal

radix-engine-macros/src/decimal.rs
Just fixed an error message I missed updating last night. The decimal one is already correct.
=> fix: Improve error message in pdec! for overflow

.github/workflows/fuzzing.yml, fuzz-tests/Cargo.toml, fuzz-tests/fuzz.sh, fuzz-tests/src/bin/decimal.rs, fuzz-tests/src/bin/parse_decimal.rs, fuzz-tests/src/bin/transaction.rs, fuzz-tests/src/bin/wasm_instrument.rs, fuzz-tests/src/lib.rs, fuzz-tests/src/transaction/fuzz_tx.rs, fuzz-tests/src/utils/mod.rs, fuzz-tests/src/utils/simple_fuzzer.rs, radix-engine-common/Cargo.toml, radix-engine-common/src/math/bnum_integer.rs, radix-engine-common/src/math/decimal.rs, radix-engine-common/src/math/rounding_mode.rs
- Add AFL support for decimal tests
- Add 'simple_fuzzer' support for decimal tests
- Let 'simple_fuzzer' work with Arbitrary types
=> Support AFL and simple_fuzzer for decimal fuzz tests 

radix-engine/src/system/system.rs
Validate features for both inner and outer blueprints. This interface is exposed to native blueprints only.
=> Validate features for all

fuzz-tests/src/bin/system.rs
Fix some of the system fuzzer's coverage by using explicit keys and adding more system apis into the fuzzer.
=> Test: Fix fuzz system coverage

radix-engine-interface/src/api/blueprint_api.rs, radix-engine/src/system/system.rs, radix-engine/src/system/system_callback.rs, radix-engine/src/system/system_type_checker.rs, scrypto-test/src/environment/client_api.rs
Avoid scrypto schema clone, which improves genesis transaction processing by ~20%.
=> Improve schema cache

.github/actions/setup-env/action.yml, .github/actions/setup-job/action.yml, .github/workflows/ci.yml, .github/workflows/cpu_instructions.yml
- Use common GH action to setup GH job environment
This is mainly to apply env changes in one place. 
(especially useful when setting up Rust toolchain version)
=> Use common GH action `setup-env`

simulator/src/resim/cmd_publish.rs, simulator/tests/resim.sh
Fixes resim publish when a .wasm file is provided.
Resolves: #1622
=> Fix resim publish wasm file

radix-engine-common/src/crypto/hash_accumulator.rs, transaction-scenarios/src/runners/dumper.rs
Assert scenario execution end state.
=> Assert scenario end state

simulator/src/rtmd/mod.rs
Updated `rtmd` cli tool - added decoding of versioned transaction manifest.
=> [CLI] Added decoding of versioned transaction manifest

radix-engine-interface/src/api/node_modules/metadata/models/mod.rs, radix-engine-tests/tests/metadata.rs
Fixed the `NonFungibleGlobalid` metadata discriminator
=> Bugfix: `NonFungibleGlobalid` metadata discriminator

README.md
```
Update README file with Radix License 1.0 header
```
=> add Radix License 1.0 header to README

radix-engine-common/src/data/manifest/mod.rs, radix-engine-common/src/data/scrypto/mod.rs, radix-engine-common/src/lib.rs, radix-engine-interface/src/api/node_modules/metadata/roles.rs, radix-engine-interface/src/lib.rs, radix-engine-stores/src/rocks_db.rs, radix-engine/src/blueprints/transaction_processor/package.rs, radix-engine/src/lib.rs, radix-engine/src/system/system_modules/module_mixer.rs, radix-engine/src/types.rs, radix-engine/src/utils/mod.rs, radix-engine/src/vm/wasm/wasmer.rs, sbor/src/basic.rs, sbor/src/codec/array.rs, sbor/src/codec/integer.rs, sbor/src/codec/misc.rs, sbor/src/codec/mod.rs, sbor/src/codec/string.rs, sbor/src/codec/tuple.rs, scrypto/src/lib.rs, scrypto/src/prelude/mod.rs, simulator/src/resim/mod.rs, transaction-scenarios/src/lib.rs
Additionally fixed feature 'radix_engine_tests' handling in `wasmer`, which was breaking `build.sh`.
=> Fix more rust warnings

radix-engine/src/system/system_modules/costing/fee_table.rs
Improve costing calculation for BLS related methods
more details available in this spreadsheet [here](https://docs.google.com/spreadsheets/d/1rV0KyB7UQrg2tOenbh2MQ1fo9MXwrwPFW4l0_CVO-6o/edit?usp=sharing)
=> Improve costing calculation for BLS related methods

.github/workflows/ci-scrypto-builder.yml, assert_file_size.sh, radix-engine-common/Cargo.toml, radix-engine-common/src/crypto/secp256k1/mod.rs, radix-engine-common/src/crypto/signature_validator.rs, radix-engine/Cargo.toml, transaction/Cargo.toml
- Add `secp256k1_sign_and_validate` feature flag
- Add test to prevent WASM size regression
=> Add secp256k1_sign_and_validate feature flag

update-assets.sh
Path in update-assets.sh was incorrect
=> Correct invalid path in update-assets.sh

substate-store-impls/src/hash_tree/mod.rs
This is a quick adjustment of the recent https://github.com/radixdlt/radixdlt-scrypto/pull/1722.
Turns out the Node has a real variety of `NestedTreeStore` usages: needs to be able to pass a reference or an owned object there.
This is only a syntactic refactoring. If anyone used that struct so far (which means, necessarily with `&`), it will just keep working.
=> [Refactor] Migrating the JMT's `NestedTreeStore` from `&` to `Deref`

radix-engine-tests/tests/db/single_substate_database_overlay.rs, substate-store-impls/src/memory_db.rs, substate-store-impls/src/single_substate_database_overlay.rs, utils/src/rust.rs
=> feature: The DatabaseOverlay is mergeable into its root store

scrypto-test/src/ledger_simulator/ledger_simulator.rs
Add documentation for `publish_package_at_address`
=> Document publish_package_at_address

.github/workflows/ci.yml, assets/blueprints/Cargo.lock, assets/blueprints/radiswap/Cargo.toml, assets/blueprints/radiswap/tests/lib.rs, scrypto-test/src/prelude.rs, substate-store-impls/src/rocks_db_with_merkle_tree/state_tree.rs
=> Fix Radiswap tests

README.md
System path update step improved to take into account `zsh` shell users.
=> Update README for macOS

.github/workflows/ci-scrypto-builder.yml, .github/workflows/publish-scrypto-builder.yml
```
INSTRUCTIONS:
Add summary - one or two sentences explaining the purpose of this PR.
```
```
INSTRUCTIONS:
Provide further details about the changes, or how they fit into the roadmap.
You can delete this section if it's not useful.
```
```
INSTRUCTIONS:
Further details about the tests you've added or manually performed.
You can delete this section if it's not useful.
```
```
INSTRUCTIONS:
This section is to provide recommendations to consumers of this repo about how they
should handle breaking changes, or integrate new features. The two key stakeholder
groups are dApp Developers and Internal Integrators, and there are separate sections
for each.
In order to allow us to compile aggregated update instructions across PRs, please tag the PR
with 0+ of the relevant labels:
* scrypto-lib - …
```
=> Chore: cleanup docker gcr

radix-engine-interface/src/blueprints/package/substates.rs, radix-engine-tests/tests/system/system_global_address.rs, radix-engine/src/system/bootstrap.rs, radix-engine/src/updates/state_updates.rs, radix-engine/src/vm/native_vm.rs
Replaces native code ID constants with a proper enum, for name consistency and better compiler checks.
=> Refactor Native Code ID

radix-engine-tests/tests/system/package.rs, radix-engine-tests/tests/vm/scrypto_costing.rs
=> Fix long role key test compilation error

radix-substate-store-queries/src/typed_substate_layout.rs, radix-transaction-scenarios/generated-examples/access-controller-v2/001--access-controller-v2-instantiate.rtm, radix-transaction-scenarios/generated-examples/access-controller-v2/002--access-controller-v2-deposit-fees-xrd.rtm, radix-transaction-scenarios/generated-examples/access-controller-v2/003--access-controller-v2-lock-fee-and-recover.rtm, radix-transaction-scenarios/src/executor.rs, radix-transaction-scenarios/src/runners/dumper.rs, radix-transaction-scenarios/src/scenarios/access_controller_v2.rs, radix-transaction-scenarios/src/scenarios/mod.rs
A small PR that adds an AccessController v2 scenario.
=> Access Controller v2 Scenario

radix-engine-tests/tests/application/preview.rs, radix-transactions/src/model/v1/blobs.rs, radix-transactions/src/model/v1/preview_transaction.rs
This PR fixes a bug where `notary_is_signatory` flag was being ignored in previews.
=> Fix notary is signatory in tx preview

radix-engine-tests/assets/blueprints/resource/src/lib.rs, radix-engine-tests/tests/blueprints/non_fungible.rs, scrypto/src/resource/bucket.rs, scrypto/src/resource/proof.rs, scrypto/src/resource/vault.rs
Add getter method `non_fungible_global_id`.
=> Add non-fungible global id getter

.github/workflows/ci.yml, .github/workflows/phylum-daily-analysis.yaml, .phylum_project
Propagate phylum integration changes to main branch
=> ci: Phylum integration

.github/workflows/phylum-daily-analysis.yaml
Not include release/babylon and release/anemone on phylum daily analysis
=> ci: Not analyze release/babylon and release/anemone on phylum daily analysis

.github/actions/setup-env/action.yml, Dockerfile, README.md
- use Rust 1.80.1 in CI
- use Rust 1.80.1 in Docker image
- update README
=> Update rust to 1.80.1

scrypto/src/resource/resource_manager.rs
Fixed something by changing something
=> Fixed the name of the role when calling set_burnable()

radix-engine-tests/assets/wasm/loop_v2.wat, radix-engine-tests/benches/costing.rs, radix-engine/src/vm/wasm/wasmi.rs, radix-engine/src/vm/wasm_runtime/scrypto_runtime.rs
Optimize the gas host function implementation.
Results on `Macbook Pro 16-inch, 2021 - Apple M1 Max`:
```rust
costing::spin_loop_v2   time:   [1.9165 s 1.9216 s 1.9277 s]                                   
change: [-28.394% -27.953% -27.554%] (p = 0.00 < 0.05)
Performance has improved.
```
=> Optimize gas host function

radix-common/src/network/mod.rs, radix-engine-tests/tests/application/static_resource_movements_visitor.rs, radix-transactions/src/manifest/static_resource_movements/effect.rs, radix-transactions/src/manifest/static_resource_movements/error.rs, radix-transactions/src/manifest/static_resource_movements/types.rs, radix-transactions/src/manifest/static_resource_movements/visitor.rs
To better serve the possible future needs of the wallet review, multiple deposits / withdraws are aggregated together in static resource movement analysis.
Added some new tests detailing the changes.
=> feature: Can also resolve total/aggregated account deposits and withdraws

.github/workflows/ci.yml, build.sh, radix-common/src/data/manifest/model/manifest_address.rs, radix-common/src/data/scrypto/model/non_fungible_local_id.rs, radix-engine-interface/src/blueprints/resource/non_fungible/non_fungible_resource_manager.rs, radix-engine-toolkit-common/src/receipt/receipt/runtime.rs, radix-transactions/src/manifest/ast.rs, radix-transactions/src/manifest/generator.rs, radix-transactions/src/manifest/parser.rs, radix-transactions/tests/assets/manifest_parser_error_invalid_number_of_values_1.diag, radix-transactions/tests/assets/manifest_parser_error_invalid_number_of_values_3.diag, radix-transactions/tests/assets/manifest_parser_error_invalid_number_of_values_3.rtm, radix-transactions/tests/test_manifest_compiler_error_diagnostics.rs, run-code-coverage.sh
Fix parsing of manifest values within parenthesis with expected length of 1
Test added
=> Fix manifest parsing

.github/workflows/dispatch-release.yml
```
Automated publishing job is missing crates token
```
=> Add crates token

.github/workflows/publish-cargo-crates.yml
```
Use public reusable action instead
=> Fix the reusable action

.github/workflows/publish-cargo-crates.yml
- ci: Add secrets related with crate token in ci.yml file
=> ci: Add secrets to crate token

.github/CODEOWNERS
=> tweak: Update CODEOWNERS

.github/workflows/publish-cargo-crates.yml
- ci: Add secrets related with crate token in ci.yml file
=> ci: Add secrets to crate token (#2046)

clean.sh, radix-engine-profiling/src/info_alloc/mod.rs, scrypto-test/src/ledger_simulator/compile.rs, scrypto-test/tests/blueprints/tuple-return/src/lib.rs, test.sh
- Fixed few tests
- Updated `test.sh` and `clean.sh`
=> Fixed some tests

radix-common/src/data/manifest/model/manifest_address_kinds.rs, radix-common/src/data/manifest/model/manifest_blob.rs, radix-common/src/lib.rs, radix-engine-interface/src/blueprints/access_controller/invocations.rs, radix-engine-interface/src/blueprints/account/invocations.rs, radix-engine-interface/src/blueprints/component.rs, radix-engine-interface/src/blueprints/consensus_manager/invocations.rs, radix-engine-interface/src/blueprints/locker/invocations.rs, radix-engine-interface/src/blueprints/macros.rs, radix-engine-interface/src/blueprints/package/invocations.rs, radix-engine-interface/src/blueprints/resource/fungible/fungible_resource_manager.rs, radix-engine-interface/src/blueprints/resource/non_fungible/non_fungible_resource_manager.rs, radix-engine-interface/src/blueprints/resource/proof_rule.rs, radix-engine-interface/src/blueprints/resource/resource_manager.rs, radix-engine-interface/src/blueprints/resource/vault.rs, radix-engine-interface/src/blueprints/transaction_tracker/invocations.rs, radix-engine-tests/tests/blueprints/account_locker.rs, radix-engine-tests/tests/misc/mod.rs, radix-engine-tests/tests/misc/typed_manifest_invocation.rs, radix-engine-tests/tests/misc_folder.rs, radix-rust/src/rust.rs, radix-transaction-scenarios/src/scenarios/account_locker.rs, radix-transactions/src/manifest/static_resource_movements/effect.rs, radix-transactions/src/manifest/static_resource_movements/typed_invocation.rs, sbor/src/schema/schema_comparison/schema_comparison_settings.rs
Merging Pr #2058 into release/cuttlefish
=> Adding typed invocation tests to cuttlefish

radix-transactions/src/manifest/static_resource_movements/typed_invocation.rs
This PR adds additional types to the manifest typed native invocations for methods, direct methods, and functions and conversions into these new types.
=> Add more typed to typed invocations
